### ISSUE TITLE
Throwing an exception when serializing a large object

### ISSUE THREAD

**Issue by 1ssqq1lxr** [EsotericSoftware/kryo#1003]
**Describe the bug**

**To Reproduce**
Provide a minimal reproducible example of the problem, ideally in the form of a runnable test-case.

**Environment:**
 - OS: [e.g. Ubuntu]
 - JDK Version: [8]
 - Kryo Version: [e.g. 5.4.0]

**Additional context**
 Exception in thread "main" java.lang.ArrayStoreException: java.lang.Float
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:356)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:777)
	at io.github.quickmsg.common.serialize.kryo.KryoObjectSerializer.read(KryoObjectSerializer.java:41)
	at io.github.quickmsg.eventbus.TransportProcessor.read(TransportProcessor.java:27)
	at io.github.quickmsg.Test.main(Test.java:35)

**Comment by 1ssqq1lxr** [comment]
If it is a serialized small object, then there is no problem

**Comment by 1ssqq1lxr** [comment]
我是序列化的对象数组   当小于序列化1000容量时候报错  100则一切正常

**Comment by 1ssqq1lxr** [comment]
I am a serialized object array. If I report an error of 100 when it is less than the serialization capacity of 1000, everything will be normal
