### ISSUE TITLE
Could not serialize Lambda. If anyone knows this, then please response.

### ISSUE THREAD

**Issue by sahibsingh0612** [EsotericSoftware/kryo#1036]
Caused by: java.lang.RuntimeException: Could not serialize lambda
	at com.esotericsoftware.kryo.serializers.ClosureSerializer.write(ClosureSerializer.java:69)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
	... 70 more
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.clients.producer.internals.Sender$SenderMetrics$$Lambda$1580/0x0000000840bb8c40.writeReplace()
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at com.esotericsoftware.kryo.serializers.ClosureSerializer.write(ClosureSerializer.java:60)
	... 72 more

**Comment by theigl** [comment]
Please provide more detail: JDK version, Kryo version, and ideally a simple reproducer.

**Comment by sahibsingh0612** [comment]
java-11-openjdk-amd64, Spark version - 3.1.2, scala version - 2.12.10

**Comment by theigl** [comment]
Which version of Kryo do you use?

I don't know your use-case, but are you sure that you really need to serialize `org.apache.kafka.clients.producer.internals.Sender$SenderMetrics`?

**Comment by sahibsingh0612** [comment]
The Kryo version is not showing in the spark application logs as well as in the environment of our local host. The default version of Kryo was used in my case. But, I am sure to serialize the lambda function.

**Comment by theigl** [comment]
Please try to provide a minimal test-case that reproduces the issue. I have no experience with Kafka or Scala and cannot help you without it.

**Comment by theigl** [comment]
Closing for now. Please re-open if you can provide more information.
