### ISSUE TITLE
readClassAndObject error when ArrayList size over 500

### ISSUE THREAD

**Issue by MyAuntIsPost90s** [EsotericSoftware/kryo#1126]
**Describe the bug**
readClassAndObject error when ArrayList size over 500

**To Reproduce**
```java
 public static void main(String[] args) throws Exception {
        List<String> productIds = new ArrayList<>();
        for(int i=0;i<1000;i++) {
            productIds.add(UUID.randomUUID().toString());
        }
        long begin = System.currentTimeMillis();
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        ByteBufferOutput output = new ByteBufferOutput(new ByteArrayOutputStream());
        kryo.writeClassAndObject(output, productIds);
        byte[] buff = output.toBytes();
        System.out.println(System.currentTimeMillis() - begin);

        begin = System.currentTimeMillis();
        kryo.readClassAndObject(new ByteBufferInput(buff));
        System.out.println(System.currentTimeMillis() - begin);

        System.out.println("length:" + buff.length);
    }
```

**Environment:**
 - OS: MacOS
 - JDK Version: 8
 - Kryo Version: 5.5.0

**Additional context**
```
Exception in thread "main" com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1241226120
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
	at com.pupu.predict.common.util.ObjSerializeUtil.main(ObjSerializeUtil.java:93)
```

it is maybe over int type limit?
<img width="816" alt="image" src="https://github.com/user-attachments/assets/33788d29-d151-4023-bb12-76740843edfb">

**Comment by MyAuntIsPost90s** [comment]
Please take some time to help take a look. Thank you very much

**Comment by MyAuntIsPost90s** [comment]
I found a way. set "buffSize" when use collection
```java
// set buffSize = 100000
ByteBufferOutput output = new ByteBufferOutput(new ByteArrayOutputStream(), 100000);
```
