### ISSUE TITLE
ArrayIndexOutOfBoundsException in IdentityMap.clear()

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#115]
_From [tcmarti...@yahoo.com](https://code.google.com/u/116741318305277927722/) on June 24, 2013 22:27:59_

<b>What steps will reproduce the problem?</b>
1. Instantiate Kryo instance.&#13;
2. Instantiate fairly complex composite Java class (my project uses one that I can't share)&#13;
3. Create 100+ copies of the complex instance in a loop&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Expect all 100+ copies to be made, but instead, I'm getting an ArrayIndexOutOfBoundsException at some point.&#13;
&#13;
&#13;
<b>What version of the Kryo are you using?</b>
2.19, 2.20, 2.21&#13;
&#13;
&#13;
<b>Please provide any additional information below.</b>
This problem does NOT exhibit itself in 2.17 or lower. It pops up only in 2.19 and above. I recognize the problem is probably very specific to the nature of my complex, composite Java object that I'm cloning (copying) and therefore may be difficult for you guys to replicate. If time permits, I may try to troubleshoot this for you, however, I can clearly see something must have changed between 2.17 &amp; 2.19 that affects IdentityMap.clear() to cause this. Perhaps you guys will be able to see the difference and arrive at a conclusion fairly easily. If not, let me know and I'll try to have a deeper look myself when I get an opportunity. In the meantime, I'll go just use 2.17.&#13;
&#13;
Thanks&#13;

_Original issue: http://code.google.com/p/kryo/issues/detail?id=115_

**Comment by mateuszef** [comment]
came across same issue as mentioned above (https://github.com/EsotericSoftware/kryo/issues/115#issuecomment-54282567), when serializing data...

```
java.lang.ArrayIndexOutOfBoundsException: 536870951
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.clear(IdentityObjectIntMap.java:466)
        at com.esotericsoftware.kryo.util.MapReferenceResolver.reset(MapReferenceResolver.java:65)
        at com.esotericsoftware.kryo.Kryo.reset(Kryo.java:888)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:559)

```

I am using kryo 4.0.0 I will let you know some details, if I can manage to collect the... Interesting that in content of exception same number shows up as in ApacheSpark library - 536870951

**Comment by xguo27** [comment]
Interestingly I see the exact same index number which throws exception.
```
java.lang.ArrayIndexOutOfBoundsException: 536870951
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.clear(IdentityObjectIntMap.java:382)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.reset(MapReferenceResolver.java:65)
	at com.esotericsoftware.kryo.Kryo.reset(Kryo.java:865)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:241)
	at org.apache.spark.serializer.SerializationStream.writeValue(Serializer.scala:134)
```

@mateuszef , how did you solve it?

**Comment by NathanSweet** [comment]
FWIW, all the Kryo maps have been updated recently in the `master` branch.

**Comment by Heltman** [comment]
I got this problem when use spark2.3.2:
`java.lang.ArrayIndexOutOfBoundsException: 536870951
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.clear(IdentityObjectIntMap.java:382)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.reset(MapReferenceResolver.java:65)
	at com.esotericsoftware.kryo.Kryo.reset(Kryo.java:865)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:241)
	at org.apache.spark.serializer.SerializationStream.writeValue(Serializer.scala:134)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:241)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.org$apache$spark$util$collection$ExternalAppendOnlyMap$$spillMemoryIteratorToDisk(ExternalAppendOnlyMap.scala:233)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.spill(ExternalAppendOnlyMap.scala:185)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.spill(ExternalAppendOnlyMap.scala:55)
	at org.apache.spark.util.collection.Spillable.maybeSpill(Spillable.scala:97)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:159)
	at org.apache.spark.Aggregator.combineValuesByKey(Aggregator.scala:41)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:90)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.CoGroupedRDD$$anonfun$compute$2.apply(CoGroupedRDD.scala:141)
	at org.apache.spark.rdd.CoGroupedRDD$$anonfun$compute$2.apply(CoGroupedRDD.scala:137)`
