### ISSUE TITLE
ByteBufferInput.eof NPE

### ISSUE THREAD

**Issue by yaitskov** [EsotericSoftware/kryo#280]
Version are 3.0.0 and 2.24.0.

It looks like eof calls not overridden the option method.

``` java
    @Test
    public void eof() {
        ByteBufferInput in = new ByteBufferInput(new ByteArrayInputStream(new byte[] {123,0,0,0}));
        Assert.assertFalse(in.eof());
    }
```

```
java.lang.NullPointerException
    at java.io.ByteArrayInputStream.read(ByteArrayInputStream.java:178)
    at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
    at com.esotericsoftware.kryo.io.Input.optional(Input.java:201)
    at com.esotericsoftware.kryo.io.Input.eof(Input.java:226)
    at com.github.moneystream.KryoTest.eof(KryoTest.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:236)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:134)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)

```

**Comment by magro** [comment]
@NathanSweet consider for 5.0?
