### ISSUE TITLE
Cannot remove a Field from FieldSerializer

### ISSUE THREAD

**Issue by seveneves** [EsotericSoftware/kryo#285]
Hi, 

I'm having a custom serializer that extends FieldSerializer. 

```
class MyCustomSerializer(kryo: Kryo) extends FieldSerializer[MyClass](kryo, classOf[MyClass]) {

  override def initializeCachedFields(): Unit = {
    getFields.find(_.getField.getName == "myField").foreach(field => super.removeField(field.getField.getName))
  }
```

When i do that in previous version of kryo, ie 2.22, it worked. Now it does not. 

The problem might be on line 565 when reassigning `fields` array in method `com.esotericsoftware.kryo.serializers.FieldSerializer#removeField(java.lang.String)`

and then another removal is happening on line 254 of class `com.esotericsoftware.kryo.serializers.FieldSerializer` which results into 

```
Field "myField" not found on class: com.example.MyClass
java.lang.IllegalArgumentException: Field "myField" not found on class: com.example.MyClass
	at com.esotericsoftware.kryo.serializers.FieldSerializer.removeField(FieldSerializer.java:586)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:254)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:156)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:133)
```

**Comment by seveneves** [comment]
Seems, the custom impletation chaged and now protected field `removedFeilds` has to be used. 

I suppose correct code has to be written as 

```
class MyCustomSerializer(kryo: Kryo) extends FieldSerializer[MyClass](kryo, classOf[MyClass]) {

  override def initializeCachedFields(): Unit = {
    getFields.find(_.getField.getName == "myField").foreach(removedFields.add)
  }
}
```

**Comment by seveneves** [comment]
The latest code does not work as well. Since `removeFields` can be called multiple times during lifetime of a Serializer. It removes fields first time when called and then it fails on next call with similar error as above. This happens because of call `rebuildCachedFields` might be called multiple times and it delegates to `removeFields`. 

The working example of an Custom serializer will look like this

```
class MyCustomSerializer(kryo: Kryo) extends FieldSerializer[MyClass](kryo, classOf[MyClass]) {

  override def initializeCachedFields(): Unit = {
    getFields.find(_.getField.getName == "myField").foreach(removedFields.add)
    
    override def removeField(fieldName: ArtifactId): Unit = scala.util.Try(super.removeField(fieldName))

    override def removeField(removeField: CachedField[_]): Unit = scala.util.Try(super.removeField(removeField))
 }
}
```

It just suppresses exceptions thrown by `removeField` method and it's a bad practice to do so.

**Comment by NathanSweet** [comment]
Sorry, I don't have time to play with Scala. A number of people here do though, maybe they can take a look.

**Comment by s-j-park** [comment]
I hit this issue in Kryo 3.0.3.  The problem is that the `com.esotericsoftware.kryo.serializers.FieldSerializer#rebuildCachedFields(boolean)` method has this loop towards the end:

```for (CachedField field : removedFields) removeField(field);```

The method called within the loop, `com.esotericsoftware.kryo.serializers.FieldSerializer#removeField(com.esotericsoftware.kryo.serializers.FieldSerializer.CachedField)`, has two problems:

1. A reference equality check, where I suspect a field name check should be carried out instead (`if (cachedField == removeField) { ... }`).
2. It attempts to modify the `removedFields` collection as its being iterated; this line should not be here, as far as I can tell (`removedFields.add(cachedField)`).

**Comment by magro** [comment]
A good thing would be to have a failing unit test as a start, then the fix can be explored. @s-j-park Do you want to submit a pull request for this? 

(answering from my phone, currently on vacation)
