### ISSUE TITLE
Deserialization fails when sth is registered with id between 0 and 8

### ISSUE THREAD

**Issue by maciejjaskowski** [EsotericSoftware/kryo#287]
Is this a bug or I am missing something?

```
public class IntegrationTest extends TestCase {

    public Kryo kryo() {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(true);

        kryo.register(double[].class, 7); // "7" is important, double[] is not
        kryo.register(Some.class, new SomeSerializer(), 10);
        return kryo;
    }

    public void testOutputStream () throws IOException {

        {
            Kryo kryo = kryo();
            Some<Integer> s = new Some<Integer>(2);
            ByteArrayOutputStream result = new ByteArrayOutputStream();
            Output output = new Output(result);
            kryo.writeObject(output, s);
            output.flush();

            Input input = new Input(new ByteArrayInputStream(result.toByteArray()));


            Some r = kryo.readObject(input, Some.class); //OK!
            assertEquals(r.get(), 2);
        }

        {
            Kryo kryo = kryo();
            Some<Long> s = new Some<Long>(2L);
            ByteArrayOutputStream result = new ByteArrayOutputStream();
            Output output = new Output(result);
            kryo.writeObject(output, s);
            output.flush();

            Input input = new Input(new ByteArrayInputStream(result.toByteArray()));


            kryo.readObject(input, Some.class); //IndexOutOfBoundException
        }

    }

}

interface Option<T> {
    public T get();
}

class Some<T> implements Option<T> {

    private T t;

    public Some(T t) {
        this.t = t;
    }

    public T get() { return t; }
}

class SomeSerializer extends Serializer<Some> {
    public void write(Kryo kryo, Output output, Some t) {
        kryo.writeClassAndObject(output, t.get());
    }

    public Some read(Kryo kryo, Input input, Class<Some> aClass) {
        return new Some(kryo.readClassAndObject(input));
    }
}
```

**Comment by NathanSweet** [comment]
If something fails, [post the failure](https://github.com/libgdx/libgdx/wiki/Getting-help#exceptions).

Kryo registers 9 types by default, so 0-8 are already used. 7 is long.

**Comment by maciejjaskowski** [comment]
Sure! The stack trace is below:

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:831)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:785)
	at com.esotericsoftware.kryo.SomeSerializer.read(IntegrationTest.java:79)
	at com.esotericsoftware.kryo.SomeSerializer.read(IntegrationTest.java:73)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:683)
	at com.esotericsoftware.kryo.IntegrationTest.testOutputStream(IntegrationTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Yes, I am aware of this but:
1. The documentation to `Kryo.register` says:
```
* @param id Must be >= 0. Smaller IDs are serialized more efficiently. IDs 0-8 are used by default for primitive types and
* String, but these IDs can be repurposed. */
```
2. Indeed changing the number  to 0 and Long to Int causes a similar error.

**Comment by NathanSweet** [comment]
No, they should be configurable. The issue is legit, replacing a registration has bugs.
