### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ThanosFisherman** [EsotericSoftware/kryo#290]
Hey, 
I try to serialize-deserialize some stuff on android
Writing to file seems to work ok with the code below:
```java
   public static void writeVenuesExternal(Context ctx, Object obj)
    {
        File = new File(ctx.getExternalFilesDir(null), "venues.bin");
   
        if (isExternalStorageWritable())
        {
            try
            {
                Output output = new Output(new DeflaterOutputStream(new FileOutputStream(file)));
                kryo.writeObject(output, obj);
                output.close();
            }
            catch (FileNotFoundException e)
            {
                Toast.makeText(ctx, R.string.cant_write, Toast.LENGTH_LONG).show();
            }
        }
        else
        {
            Toast.makeText(ctx, R.string.cant_write, Toast.LENGTH_LONG).show();
        }
    }
```

but when its time to read from that file it fails with an error. Here is my code to read

```java
    public static VenueSearchRoot readVenuesExternal(Context ctx)
    {
        File = new File(ctx.getExternalFilesDir(null), "venues.bin");

        if (file.exists() && file.canRead())
        {
            try
            {
                Input input = new Input(new DeflaterInputStream(new FileInputStream(file)));
                VenueSearchRoot vroot = kryo.readObject(input, VenueSearchRoot.class);
                input.close();
                return vroot;
            }
            catch (FileNotFoundException e)
            {
                Toast.makeText(ctx, R.string.cant_write, Toast.LENGTH_LONG).show();
            }
        }

        return null;
    }
```

And here is the error:

`
java.lang.IndexOutOfBoundsException: Invalid index 118, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:42)
            at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:830)
            at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:680)
            at com.fisherman.wifisherlock.controllers.FileController.readVenuesExternal(FileController.java:87)
            at com.fisherman.wifisherlock.ui.activities.MainActivity.onListFragmentLoaded(MainActivity.java:237)
`

I use the DeflaterInputStream cuz it is supposed to make the file smaller in size? Without this it reads fine.

**Comment by ThanosFisherman** [comment]
Damn I just figured out i had to use InflaterInputStream for the reading but I couldn't find it in the wiki example. Sorryz issue solved
