### ISSUE TITLE
NPE unserializing class with generic type?

### ISSUE THREAD

**Issue by pranahata** [EsotericSoftware/kryo#296]
This is the class

public class UserLogon<T extends User> implements Serializable {
    private final T user;
    private final List<Group> allGroups;
}

Kryo 3.0.1 

com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
allGroups (com.anahata.yam.model.user.UserLogon)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144) ~[kryo-3.0.1.jar:na]
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:557) ~[kryo-3.0.1.jar:na]
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-3.0.1.jar:na]
    at com.anahata.util.transport.rpc.RpcStreamer.deserialize(RpcStreamer.java:279) ~[classes/:na]
    at com.anahata.util.transport.rpc.RpcStreamer.receiveStreaming(RpcStreamer.java:269) ~[classes/:na]
    at com.anahata.util.transport.rpc.client.impl.CommonsRpcClientTransport.sendReceive(CommonsRpcClientTransport.java:140) ~[classes/:na]
    at com.anahata.util.transport.rpc.client.impl.CommonsRpcClientTransport$Proxy$_$$_WeldClientProxy.sendReceive(Unknown Source) ~[classes/:na]
    at com.anahata.util.transport.rpc.client.RpcInvocationHandler.invoke(RpcInvocationHandler.java:65) ~[classes/:na]
    at com.sun.proxy.$Proxy55.login(Unknown Source) ~[na:na]
    at com.anahata.yam.ui.jfx.user.UserContext.login(UserContext.java:130) ~[classes/:na]
    at com.anahata.yam.ui.jfx.user.UserContext$Proxy$_$$_WeldClientProxy.login(Unknown Source) ~[classes/:na]
    at com.anahata.yam.ui.jfx.Main.start(Main.java:108) ~[classes/:na]
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863) [jfxrt.jar:na]
    at com.sun.javafx.application.LauncherImpl$$Lambda$65/433701966.run(Unknown Source) [jfxrt.jar:na]
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326) [jfxrt.jar:na]
    at com.sun.javafx.application.PlatformImpl$$Lambda$57/1125614861.run(Unknown Source) [jfxrt.jar:na]
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295) [jfxrt.jar:na]
    at com.sun.javafx.application.PlatformImpl$$Lambda$60/641112538.run(Unknown Source) [jfxrt.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) [na:na]
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294) [jfxrt.jar:na]
    at com.sun.javafx.application.PlatformImpl$$Lambda$58/1825983295.run(Unknown Source) [jfxrt.jar:na]
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) [jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java) [jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) [jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$48/752230403.run(Unknown Source) [jfxrt.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: java.lang.NullPointerException: null
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:234) ~[na:1.8.0_40]
    at java.util.ArrayList.ensureCapacity(ArrayList.java:218) ~[na:1.8.0_40]
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:114) ~[kryo-3.0.1.jar:na]
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~[kryo-3.0.1.jar:na]
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:705) ~[kryo-3.0.1.jar:na]
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-3.0.1.jar:na]
    ... 25 common frames omitted

**Comment by magro** [comment]
Sorry for the late response! Is this still an issue for you?

**Comment by lvdelu** [comment]
yes,how to solve it

**Comment by magro** [comment]
@lvdelu please provide a complete, self contained example.

**Comment by NathanSweet** [comment]
Reopen if provided.
