### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Buffer underflow

### ISSUE THREAD

**Issue by owenludong** [EsotericSoftware/kryo#318]
kryo version  :  3.0.1

when I deserialize the object, kryo throw below exception,have any idea?

2015-06-11 18:00:58,532 ERROR , Buffer underflow.
Serialization trace:
body (x.MessageExt)
com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
body (x.MessageExt)
        at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
        at com.esotericsoftware.kryo.io.Input.readBytes(Input.java:346)
        at com.esotericsoftware.kryo.io.Input.readBytes(Input.java:326)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.read(DefaultArraySerializers.java:60)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.read(DefaultArraySerializers.java:43)
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:763)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:557)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)

**Comment by owenludong** [comment]
call deserialize method is kryo.readObject(input, clazz);
before call readObject, I when call kryo.register(clazz)

**Comment by magro** [comment]
Can you provide a reproducable sample, e.g. a unit test that allows to reproduce the issue?

**Comment by owenludong** [comment]
it happend in concurrent environment  and it's a randomness

**Comment by magro** [comment]
Which resources are shared between threads? According to https://github.com/EsotericSoftware/kryo#threading, neither Kryo nor Input are thread safe.

**Comment by magro** [comment]
@owenludong Any feedback, or can we close this one?

**Comment by mufumbo** [comment]
I have this issue when trying to deserialize a class that has changed methods..

**Comment by magro** [comment]
@mufumbo Changing methods is not supported by FieldSerializer, so it's expected that this produces errors. Use any of the serializers that support compatibility according to your use case.

**Comment by mufumbo** [comment]
makes sense @magro thanks for the reply, i saw that later. 
by the way, the homepage README.md is so extensive and complex that it doesn't mention in bold hightlighted at the top that Kryo doesn't support backward compatibility and people shouldn't use FieldSerializer if saving stuff to the database. Maybe that's a good idea, so I wouldn't need to do a huge db migration right now? :-) completely my fault, but might be worth mentioning it.

**Comment by magro** [comment]
@mufumbo You're right, thanks for the suggestion! And I'm sorry for the inconvenience!

**Comment by duckyduck** [comment]
I had the same error. So, you can try like this.
byte[] data = ....;
........
Input input = new Input(data);
==== upper code change to =====>
Input input = new Input(new ByteArrayInputStream(data));

**Comment by Viyond** [comment]
@duckyduck it's no use.
