### ISSUE TITLE
Unable to find class

### ISSUE THREAD

**Issue by icode** [EsotericSoftware/kryo#319]
```
com.esotericsoftware.kryo.KryoException: Unable to find class: ameba.http.session.SessionStorejava.lang.String
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:156) ~[kryo-3.0.1.jar:na]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-3.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:667) ~[kryo-3.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:778) ~[kryo-3.0.1.jar:na]
	at ameba.cache.util.KryoSerializer$3.execute(KryoSerializer.java:87) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-3.0.1.jar:na]
	at ameba.cache.util.KryoSerializer.asObject(KryoSerializer.java:82) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.cache.util.Serializations.asObject(Serializations.java:32) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.cache.util.Serializations.asObject(Serializations.java:38) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.cache.Cache.get(Cache.java:365) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.http.session.CacheSession.refresh(CacheSession.java:113) ~[ameba-session-0.1.7-20150612.180847-61.jar:na]
	at ameba.http.session.CacheSession.isInvalid(CacheSession.java:74) ~[ameba-session-0.1.7-20150612.180847-61.jar:na]
	at ameba.http.session.SessionFilter.filter(SessionFilter.java:68) ~[ameba-session-0.1.7-20150612.180847-61.jar:na]
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) ~[jersey-server-2.18.jar:na]
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) ~[jersey-server-2.18.jar:na]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) ~[jersey-common-2.18.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:300) ~[jersey-server-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [jersey-server-2.18.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [jersey-server-2.18.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:150) [ameba-container-grizzly-0.1.7-20150528.081010-13.jar:na]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.20.jar:2.3.20]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.20.jar:2.3.20]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.20.jar:2.3.20]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.ClassNotFoundException: ameba.http.session.SessionStorejava.lang.String
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
	at ameba.dev.classloading.ReloadClassLoader.loadClass(ReloadClassLoader.java:158) ~[ameba-dev-0.1.7-20150611.090831-67.jar:0.1.7-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
	at java.lang.Class.forName0(Native Method) ~[na:1.7.0_80]
	at java.lang.Class.forName(Class.java:278) ~[na:1.7.0_80]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154) ~[kryo-3.0.1.jar:na]
	... 29 common frames omitted
```

version : 3.0.1
source code https://github.com/icode/ameba-cache/blob/master/core/src/main/java/ameba/cache/util/KryoSerializer.java

one first error, and second time is ok.

I can't find the law for this error, I'm use for http session serialize

Some time get Object from ehcache thow error
```
try {
    KryoSerializer.asObject(bytes);//throw error
} cache(Exception e) {
    KryoSerializer.asObject(bytes);//is ok
}
```

**Comment by magro** [comment]
Can you explain the special chars in SessionStore�����?
Where was the instance created that got serialized?
Can you please share some details regarding the SessionStore, e.g. its life
cycle, if it's only existing within a single jvm etc?
Am 13.06.2015 19:16 schrieb "icode" <notifications@github.com>:

**Comment by icode** [comment]
this cookie mapping server session filter https://github.com/icode/ameba-session/blob/master/src/main/java/ameba/http/session/SessionFilter.java

a lot and fast switch page happened this error

**Comment by magro** [comment]
I can't find where SessionStore is created in that filter, other questions
remain unanswered. You'll get better help if you share a good problem /
context description.
Am 13.06.2015 22:44 schrieb "icode" <notifications@github.com>:

**Comment by magro** [comment]
Another good way to report an issue is to provide a reproducable/executable test case. Asking for help is better done on the mailing list.

**Comment by icode** [comment]
https://github.com/icode/ameba-session/blob/master/src/main/java/ameba/http/session/CacheSession.java  this save cacheStore to ehcache

https://github.com/icode/ameba-cache/blob/master/core/src/main/java/ameba/cache/Cache.java this cache api

i don't know special chars,  i don't have any operation. Second time `readClassAndObject` is ok, at readClassAndObject error after (catch code block)

**Comment by icode** [comment]
`Another good way to report an issue is to provide`

But i can't find it the law for this error

**Comment by magro** [comment]
Can you attach a debugger and halt when the session gets serialized to inspect the serialized object graph and the SessionStore in particular? This might help you to understand what's going on.

**Comment by icode** [comment]
This random happened, how to debug?And must be fast and most visit web page.

**Comment by magro** [comment]
An issue that only you can reproduce cannot be analyzed by others. You could e.g. try to reproduce this by simulating your setup in a "unit" test (self contained test that anybody can run using e.g. `mvn test`) and generate artificial load (e.g. by spawning threads).

**Comment by NathanSweet** [comment]
I'm afraid we can't fix it without reproducing the problem, which is also needed for testing any proposed fix. I suggest either providing an SSCCE or figuring out the fix and posting that.

**Comment by adilhamid** [comment]
This happens, ever heard of Hisenbug?

**Comment by adilhamid** [comment]
Instead of: com.myproject.starfish.ohgod.cache.TellerThings
Caused by: java.lang.ClassNotFoundException: com.myproject.starfish.o`god.cache.TellerThings 
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192] 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192] 
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_192] 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192] 
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_192] 
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_192] 
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136) ~[kryo-2.24.jar:?]
