### ISSUE TITLE
Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: void

### ISSUE THREAD

**Issue by plmedici** [EsotericSoftware/kryo#334]
Hello,
   I'm trying to serialize a DataTable in Scala (https://github.com/martincooper/scala-datatable) so that I can distribute instances of it over a network using Apache Spark.

   I'm running into an error after registering the DataTable class with the Spark context's Kryo serializer:

       conf.registerKryoClasses(Array(classOf[com.github.martincooper.datatable.DataTable]))

   Here's the serialization trace from the Scala interpreter:

      Serialization trace:
      referent (java.lang.ref.WeakReference)
      scala$reflect$runtime$TwoWayCaches$TwoWayCache$$toJavaMap (scala.reflect.runtime.TwoWayCaches$TwoWayCache)
      classCache (scala.reflect.runtime.JavaMirrors$JavaMirror)
      $outer (scala.reflect.runtime.JavaMirrors$JavaMirror$$anon$1)
      currentOwner (scala.reflect.internal.Trees$TreeTypeSubstituter)
      EmptyTreeTypeSubstituter (scala.reflect.runtime.JavaUniverse)
      $outer (scala.reflect.internal.Types$ClassNoArgsTypeRef)
      columnType (com.github.martincooper.datatable.DataColumn)
      columnIndexMapper (com.github.martincooper.datatable.DataColumnCollection)
      columns (com.github.martincooper.datatable.DataTable)
      value (scala.util.Success)

   It seems that the void type cannot be serialized. Is that correct? I've tried registering the void class with the serializer (so classOf[java.lang.Void]) and that doesn't make a difference.

   Thanks for your help in this matter.

EDIT: 

I've attached a test case (Scala 2.11.6, Apache Spark 1.4, scala-datatable 0.7.0) below that reproduces the error:

      import com.github.martincooper.datatable._
      import org.apache.spark._

      // build fake DataTable
      val numrows = 4
      val newDataTab = DataTable("test",Seq())

      val col1 = new DataColumn[Int]("1",(1 to numrows).map {i => 0})
      val updDataTab = newDataTab.get.columns.add(col1)
      val col2 = new DataColumn[Double]("2",(1 to numrows).map {i => 0.0})
      val finalDataTab = updDataTab.get.columns.add(col2)

      // set up Spark session
      val conf = new SparkConf().setMaster("local[2]").setAppName("serialization test")
      conf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      conf.registerKryoClasses(Array(classOf[com.github.martincooper.datatable.DataTable],classOf[com.github.martincooper.datatable.DataColumnCollection]))
      val sc = new SparkContext(conf)

      val dataTabBroadcast = sc.broadcast(finalDataTab)

**Comment by magro** [comment]
One option would be to write a custom serializers for DataTable and associated classes.

**Comment by plmedici** [comment]
Thanks for the comment.

However, the problem seems to be more fundamental than that. Somewhere in the serialization trace Kryo seems to run up against something of type void (which I thought was serializable).

Put another way, why would I get the error listed in the title when VoidSerializer exists?

Here's more information from the error trace (I used MeatLocker() from the Twitter chill library here, but the issue still applies:

com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: void
Serialization trace:
referent (java.lang.ref.WeakReference)
scala$reflect$runtime$TwoWayCaches$TwoWayCache$$toJavaMap (scala.reflect.runtime.TwoWayCaches$TwoWayCache)
classCache (scala.reflect.runtime.JavaMirrors$JavaMirror)
$outer (scala.reflect.runtime.JavaMirrors$JavaMirror$$anon$1)
currentOwner (scala.reflect.internal.Trees$TreeTypeSubstituter)
EmptyTreeTypeSubstituter (scala.reflect.runtime.JavaUniverse)
$outer (scala.reflect.internal.Types$ClassNoArgsTypeRef)
columnType (com.github.martincooper.datatable.DataColumn)
columnIndexMapper (com.github.martincooper.datatable.DataColumnCollection)
columns (com.github.martincooper.datatable.DataTable)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:585)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
  at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:37)
  at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:33)
  at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
  at com.twitter.chill.TraversableSerializer$$anonfun$write$1.apply(Traversable.scala:29)
  at com.twitter.chill.TraversableSerializer$$anonfun$write$1.apply(Traversable.scala:27)
  at scala.collection.Iterator$class.foreach(Iterator.scala:750)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at com.twitter.chill.TraversableSerializer.write(Traversable.scala:27)
  at com.twitter.chill.TraversableSerializer.write(Traversable.scala:21)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
  at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:37)
  at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:33)
  at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
  at com.twitter.chill.TraversableSerializer$$anonfun$write$1.apply(Traversable.scala:29)
  at com.twitter.chill.TraversableSerializer$$anonfun$write$1.apply(Traversable.scala:27)
  at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
  at com.twitter.chill.TraversableSerializer.write(Traversable.scala:27)
  at com.twitter.chill.TraversableSerializer.write(Traversable.scala:21)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
  at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
  at com.twitter.chill.SerDeState.writeClassAndObject(SerDeState.java:64)
  at com.twitter.chill.KryoPool.toBytesWithClass(KryoPool.java:116)
  at com.twitter.chill.MeatLocker.<init>(MeatLocker.scala:32)
  at com.twitter.chill.MeatLocker$.apply(MeatLocker.scala:21)
  ... 33 elided
Caused by: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: void
  at com.esotericsoftware.kryo.Kryo.newSerializer(Kryo.java:335)
  at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:314)
  at com.twitter.chill.KryoBase.newDefaultSerializer(KryoBase.scala:48)
  at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:307)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:56)
  at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:445)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:79)
  at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:472)
  at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.write(DefaultSerializers.java:219)
  at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.write(DefaultSerializers.java:212)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
  at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
  ... 87 more
Caused by: java.lang.reflect.InvocationTargetException: java.lang.NullPointerException
  at sun.reflect.GeneratedConstructorAccessor2.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at com.esotericsoftware.kryo.Kryo.newSerializer(Kryo.java:322)
  ... 98 more
Caused by: java.lang.NullPointerException
  at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:66)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:50)
  ... 102 more

**Comment by magro** [comment]
Honestly I don't know why you're getting this exception. Can you provide a
self contained test case that allows to reproduce the error?

Cheers,
Martin
Am 08.08.2015 01:07 schrieb "plmedici" <notifications@github.com>:

**Comment by magro** [comment]
@plmedici Any feedback, or shall we close this issue?

**Comment by magro** [comment]
Reopen if still relevant.
