### ISSUE TITLE
Output doesn't synchronously flush to disk on close

### ISSUE THREAD

**Issue by johanhaleby** [EsotericSoftware/kryo#348]
I'm implementing a simplistic durable queue using Kryo and I write queue content to disk like this:

```java
OutputStream outputStream = new DeflaterOutputStream(new FileOutputStream(pathToContent), true);
  kryoPool.run(kryo -> {
            try (Output output = new Output(outputStream)) {
                kryo.writeObject(output, content);
            }
            lock.lock();
            try {
                notEmpty.signal();
            } finally {
                lock.unlock();
            }           
            return null;
        });
```

`lock` is a `ReentrantLock` and `notEmpty` is a `Condition` on this lock:

```java
ReentrantLock lock = new ReentrantLock();
Condition notEmpty = lock.newCondition();
```

The purpose of this code is to signal to another thread that a new object (`content`) has been written to disk and can be read by the other thread. The other thread starts correctly and immediately tries to read the object from the filesystem (if there are consumers waiting): 

```java
try (Input input = new Input(new InflaterInputStream(file))) {
      return kryoPool.run(kryo -> kryo.readObject(input, Content.class));
} 
```

The problem is that under load it's frequent to run into exceptions like this:

```java
com.esotericsoftware.kryo.KryoException: java.io.EOFException: Unexpected end of ZLIB input stream
    at com.esotericsoftware.kryo.io.Input.fill(Input.java:166)
    at com.esotericsoftware.kryo.io.Input.require(Input.java:196)
    at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373)
    at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:823)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:684)
    at ....    
    at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61)
    at .... 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at com.esotericsoftware.kryo.io.Input.fill(Input.java:164)
    at com.esotericsoftware.kryo.io.Input.require(Input.java:196)
    at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373)
    at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:823)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:684)
    at ....
    at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61)
    at .... 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

My workaround is to sleep for a short period of time and then retry the "read" operation and then it usually works. This happens even though `DeflaterOutputStream` is set to do synchronous flushing.

**Comment by magro** [comment]
@johanhaleby Sorry for the late response! This has been changed/fixed with #344, which is available in the current SNAPSHOT.
