### ISSUE TITLE
Kryo Deserialization issue : Invalid ordinal value for enum

### ISSUE THREAD

**Issue by anandpandey** [EsotericSoftware/kryo#374]
Hi Team,

I have been working on Kryo to serialize my data and save it in a database. Later I try to fetch the serialized data again and try to deserialize it. Although most of the data that, I serialize get deserialized correctly, there are some scenarios where I get the following exception Trace for some data:

```java
com.esotericsoftware.kryo.KryoException: Invalid ordinal for enum "test.standards.mt564.Code4Ec335Type": 29
Serialization trace: dataMap (parser.container.TestDataCommon)
at com.esotericsoftware.kryo.serializers.DefaultSerializers$EnumSerializer.read(DefaultSerializers.java:331)
at com.esotericsoftware.kryo.serializers.DefaultSerializers$EnumSerializer.read(DefaultSerializers.java:305)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:139)
at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:17)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:685)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
at helper.KryoHelper.fromByteSerialize(KryoHelper.java:400)
at java.lang.Thread.run(Thread.java:745)
```

This data was serialized and saved in the database as a BLOB a few months back. Now I am finding a need to retrieve this data and deserialize it. The above exception occurs when I try to desiralize the data into the required object.

I know that while deserializing Enum kryo uses ordinal value of Enum. But due to some reason it gets very high value of 30 for ordinal. I am not sure what is actually causing this problem.

Request you to please help me to resolve this isssue.

I am using Kryo-2.23 version and Java 1.8.

**Comment by anandpandey** [comment]
Issue was due to classes registration mechanism. Hence closing this issue.

Refer following link for detail description: http://stackoverflow.com/questions/33829273/kryo-deserialzation-issue-invalid-ordinal-value-for-enum/33891020#33891020
