### ISSUE TITLE
NullPointerException when generic types are used

### ISSUE THREAD

**Issue by doubleloop** [EsotericSoftware/kryo#380]
Code generating NullPointerException:

``` java
public class TestKryo extends TestCase {

    @Test
    public void testKryoGenericExample() {
        abstract class A {
            final int a;
            protected A(int a) {
                this.a = a;
            }
        }

        abstract class B<T> extends A {
            final T b;
            B(int a, T b) {
                super(a);
                this.b = b;
            }
        }

        class C extends B<List<Integer>> {
            C(int a, List<Integer> b) {
                super(a, b);
            }
        }

        class D {
            final Map<String, A> map = new HashMap<>();
            public Map<String, A> getMap() {
                return map;
            }
        }

        Kryo kryo = new Kryo();
        Output out = new Output(new ByteArrayOutputStream());
        Input in = new Input();

        kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
        kryo.register(D.class);

        D d = new D();
        d.getMap().put("C", new C(2, Arrays.asList(1,2,3)));

        kryo.writeObject(out, d);
        in.setBuffer(out.toBytes());
        kryo.readObject(in, D.class);
    }
}
```

```
com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
b (pl.edu.mimuw.cloudatlas.kryo.TestKryo$2C)
map (pl.edu.mimuw.cloudatlas.kryo.TestKryo$2D)

    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)
    at pl.edu.mimuw.cloudatlas.kryo.TestKryo.testKryoGenericExample(TestKryo.java:227)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException
    at java.util.Arrays$ArrayList.size(Arrays.java:3818)
    at java.util.AbstractList.add(AbstractList.java:108)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    ... 31 more
```

**Comment by magro** [comment]
Does this happen with the current snapshot? If you've not yet tested with the latest snapshot, can you please do this?

**Comment by doubleloop** [comment]
Thanks for reply. After some investigation I found:
https://discuss.gradle.org/t/support-for-multiple-application-scripts-in-application-plugin/508/2
The problem here was Arrays.asList type. Still it took me some time to solve this as it is difficult to find based on README and NullPointerExcepion does not give much insight what is wrong. Maybe this could be mentioned in some note..

**Comment by magro** [comment]
Ok, maybe we should have a section "common issues" in the readme mentioning
this.
Am 18.01.2016 00:28 schrieb "Jakub Łuczyński" <notifications@github.com>:

**Comment by NathanSweet** [comment]
Using StdInstantiatorStrategy is asking for trouble. I highly suggest not using it if possible. In that case, Kryo would have shown the error right away:

> Class cannot be created (missing no-arg constructor): java.util.Arrays$ArrayList

If someone wants to improve the README, that would be great.
