### ISSUE TITLE
Each thread should have its own Kryo, Input, and Output instances

### ISSUE THREAD

**Issue by sirolf2009** [EsotericSoftware/kryo#381]
**Each thread should have its own Kryo, Input, and Output instances**

With this in mind I created the following class (I'm building a database backed by kryo):
```java
package com.sirolf2009.database;

import java.util.Arrays;
import java.util.LinkedList;
import java.util.Set;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.function.Function;
import java.util.stream.Stream;

import org.reflections.Reflections;

import com.esotericsoftware.kryo.Kryo;

import lombok.AllArgsConstructor;
import lombok.Data;

public class Connection implements Runnable {

	private static Connection instance;
	private final Kryo kryo;
	@SuppressWarnings("rawtypes")
	private LinkedList<MethodRequest> callbacks;

	private Connection(Database database) {
		kryo = new Kryo();
		getRegisterable(database.getPackagePrefix()).forEach(clazz -> kryo.register(clazz));
		callbacks = new LinkedList<>();
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	@Override
	public void run() {
		while(true) {
			synchronized(this) {
				while(callbacks.isEmpty()) {
					try {
						this.wait();
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}
				for(MethodRequest method : callbacks) {
					try {
						method.result.add(method.function.apply(kryo));
					} catch(Exception e) {
						e.printStackTrace();
					}
				}
				callbacks.clear();
			}
		}
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	public <R> R execute(Function<Kryo, R> function) {
		BlockingQueue<R> queue = new ArrayBlockingQueue<R>(1);
		synchronized(this) {
			callbacks.add(new MethodRequest(queue, function));
			this.notifyAll();
		}
		try {
			return queue.take();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		return null;
	}

	public Stream<Class<?>> getRegisterable(String packagePrefix) {
		Set<Class<?>> entities = new Reflections(packagePrefix).getTypesAnnotatedWith(DBEntity.class);
		return entities.stream().flatMap(entity -> getRegisterable(entity));
	}

	public Stream<Class<?>> getRegisterable(Class<?> clazz) {
		if(Object.class.isAssignableFrom(clazz)) {
			return Arrays.stream(clazz.getDeclaredFields()).flatMap(field -> getRegisterable(field.getType()));
		}
		return Stream.empty();
	}

	public static Connection getInstance(Database database) {
		if(instance == null) {
			instance = new Connection(database);
			new Thread(instance).start();
		}
		return instance;
	}

	@Data
	@AllArgsConstructor
	private static class MethodRequest<R> {

		private BlockingQueue<Object> result;
		private Function<Kryo, R> function;

	}

}
```
Which is called as such:
```java
public void create(Object object) {
		connection.execute(kryo -> {
			Output out = fileAllocation.getOutput(object);
			kryo.writeObject(out, object);
			out.close();
			return true;
		});
	}

	public <T> T read(Object ID, Class<T> type) {
		if(exists(ID, type)) {
			return connection.execute(kryo -> {
				Input input = fileAllocation.getInput(ID, type);
				T object = kryo.readObject(input, type);
				input.close();
				return object;
			});
		}
		return null;
	}
```
yet I get this stacktrace while reading an object
```
com.esotericsoftware.kryo.KryoException: Buffer underflow.
	at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:823)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:684)
	at com.sirolf2009.database.Database.lambda$1(Database.java:53)
	at com.sirolf2009.database.Connection.run(Connection.java:45)
	at java.lang.Thread.run(Thread.java:745)
```

As you can see, the Connection class is a singleton, input and outputs are created when they are needed and closed when no longer needed and the kryo instance is final and inside of a singleton and will therefore only be created once. Yet I still get this exception. What's up?

**Comment by sirolf2009** [comment]
My bad, the kryo instance was created in the constructor, which is called from a different thread than its run method. moving the code from the constructor to the run method fixed it

**Comment by magro** [comment]
@sirolf2009 Great you figured it out! Btw, kryo provides also a [KryoPool](https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/pool/KryoPool.java#L29), which reduces extra time for Kryo setup (which is fairly expensive). Alternatively you can use ThreadLocal to have a Kryo instance per thread.

**Comment by sirolf2009** [comment]
@magro yeah, I thought about that, but I could still be able to create outputs and inputs in a different thread than the thread which would serialize it, which could cause problems.
This way, I'm a little bit slower than normally, because I need to bring messages cross-thread, but the change of me doing wrong is greatly reduced
