### ISSUE TITLE
When encountering StackOverflowError, kryo doesn't show serialization stack

### ISSUE THREAD

**Issue by tribbloid** [EsotericSoftware/kryo#443]
The following stacktrace was printed when serializing an object:

```
java.lang.StackOverflowError
    at com.esotericsoftware.kryo.io.Output.writeLong(Output.java:495)
    at com.esotericsoftware.kryo.serializers.DefaultSerializers$LongSerializer.write(DefaultSerializers.java:109)
    at com.esotericsoftware.kryo.serializers.DefaultSerializers$LongSerializer.write(DefaultSerializers.java:103)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:576)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
.....
```

The error doesn't contain any information regarding the object that triggers this error. Making debugging very difficult.

**Comment by magro** [comment]
Perhaps FieldSerializer.write should catch SOE and throw a KryoException with information about the field? Not sure. Do you want to submit a pull request?

**Comment by magro** [comment]
@NathanSweet @romix what do you think about this?

**Comment by kulkarnianiket** [comment]
I am facing a similar issue. Is there any fix for this via the kryo config? I am having a hard time figuring out what is causing this issue.

I would like to submit a pull request if that would be alright.

**Comment by magro** [comment]
@kulkarnianiket where did the SOE occur, and what was the root cause in your case?

**Comment by kulkarnianiket** [comment]
I am trying to perform a mapPartitions on an RDD and obtain an RDD of the form RDD[((String, String), ArrayBuffer[(String, String)]). I am not sure where the issue stems from as I dont get any logs which point to a line in my code. I just see the recursive calls to the same method. This is my stack trace.


java.lang.StackOverflowError
	at org.xerial.snappy.Snappy.arrayCopy(Snappy.java:90)
	at org.xerial.snappy.SnappyInputStream.rawRead(SnappyInputStream.java:174)
	at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:150)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:140)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:169)
	at com.esotericsoftware.kryo.io.Input.readAscii_slow(Input.java:580)
	at com.esotericsoftware.kryo.io.Input.readAscii(Input.java:558)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:436)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:157)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:146)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:17)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)

**Comment by kulkarnianiket** [comment]
There is a setting on the kryo github page for stack size(-Xss). I used that to set the stack size to 1MB and I don't see the exception anymore.  I have confirmed that it fixes it as once I remove the setting in my run script, the issue occurs again. 

I would still like to volunteer to fix this.

**Comment by ticofab** [comment]
Any news on this? I'm just having this today using the @romix plugin for akka.
