### ISSUE TITLE
Twitter4j serialize and deserialize not working properly 

### ISSUE THREAD

**Issue by surendharjuly1988** [EsotericSoftware/kryo#444]
I'm trying to serialize and deserialize twitter instance and request token. There is problem to load twitter class. I'm getting below exception. Can someone please help me out of this issues.

WARN: [kryo] Unable to load class twitter4j.TwitterImpl with kryo's ClassLoader. Retrying with current..
ERROR | 21:49:39 | [vert.x-worker-thread-41] studio.Studio (Studio.java:17) - Unable to find class: twitter4j.TwitterImpl
`com.esotericsoftware.kryo.KryoException: Unable to find class: twitter4j.TwitterImpl`
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160) ~[kryo-4.0.0.jar:?]
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-4.0.0.jar:?]
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-4.0.0.jar:?]
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804) ~[kryo-4.0.0.jar:?]
    at mx.july.jmx.util.cache.KryoSerializer.deserialize(KryoSerializer.java:86) ~[classes/:?]
    at mx.july.jmx.util.cache.KryoSerializer.deserialize(KryoSerializer.java:78) ~[classes/:?]
    at mx.july.jmx.runtime.RedisSession$SerializedValue.getObject(RedisSession.java:230) ~[classes/:?]
    at com.july.studio.compatibility.HttpSessionBridge.getAttribute(HttpSessionBridge.java:30) ~[?:?]
    at javax.servlet.http.HttpSession$getAttribute.call(Unknown Source) ~[?:?]
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[?:?]
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[?:?]
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[?:?]
    at Cisco.Social_WiFi_Connector.SocialTW_XHTML.render(Cisco.SocialTW.SocialTW_XHTML:238) ~[?:?]
    at com.july.widget.Widget.render(Widget.java:75) ~[?:?]
    at com.july.studio.util.WidgetRunner.lambda$1(WidgetRunner.java:204) ~[?:?]
    at io.vertx.rxjava.core.Vertx$2.handle(Vertx.java:543) ~[vertx-rx-java-3.3.0.jar:?]
    at io.vertx.rxjava.core.Vertx$2.handle(Vertx.java:541) ~[vertx-rx-java-3.3.0.jar:?]
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:303) ~[vertx-core-3.3.0.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: twitter4j.TwitterImpl
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154) ~[kryo-4.0.0.jar:?]
    ... 20 more

**Comment by magro** [comment]
`java.lang.ClassNotFoundException: twitter4j.TwitterImpl` points to a classpath / classloader issue with your app. If you try to serialize this class in a self contained test case it should work.

**Comment by magro** [comment]
Is this still relevant or can we close this issue?

**Comment by heuermh** [comment]
I'm seeing similar stack traces with `JavaSerializer` in the context of the Scala shell.  What do you mean by classpath/classloader issues?  Is there anything else that needs to be in the registrator to use `JavaSerializer`?

```
scala> doSomething()
...
Caused by: java.lang.ClassNotFoundException: org.MyClass
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
  at com.esotericsoftware.kryo.serializers.JavaSerializer.read(JavaSerializer.java:63)
  ... 35 more
```

MyClass is clearly on the classpath
```
scala> import org.MyClass
import org.MyClass
```

Registrator
```java
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.serializers.JavaSerializer;
import org.MyClass;

public class MyClassKryoRegistrator extends SomeOtherKryoRegistrator {
    @Override
    public void registerClasses(final Kryo kryo) {
        super.registerClasses(kryo);
        kryo.register(MyClass.class, new JavaSerializer());
    }
}
```

Please let me know if you would rather me create a new issue.

**Comment by heuermh** [comment]
I found this in the source
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/JavaSerializer.java#L72-L78

If Kryo is using the wrong classloader, how would I provide it with the right one?  Assuming I could determine which one is the right one in the Scala Spark shell.

**Comment by magro** [comment]
Apart from the CNFE the issues/stacktraces look different to me. Anyways, you can set the CL via `Kryo.setClassLoader`.

**Comment by heuermh** [comment]
I tried setting the class loader in the registrator, and that didn't work.

Here is some possible add'l context, from Spark
https://github.com/apache/spark/pull/1972/files

**Comment by magro** [comment]
Can you reduce the issue so that only kryo is involved, without spark? Does it fail with kryo only as well?

**Comment by heuermh** [comment]
I created a new issue #489 and will attempt to reduce the dependencies necessary to reproduce.

**Comment by magro** [comment]
(y)
