### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer

### ISSUE THREAD

**Issue by ToniYang** [EsotericSoftware/kryo#445]
`val instantiator = new ScalaKryoInstantiator

    instantiator.setRegistrationRequired(false)
    val kryo = instantiator.newKryo()

    val b4 = System.currentTimeMillis()
    val baos = new ByteArrayOutputStream
    val output = new Output(baos,4096)
    kryo.writeClassAndObject(output,a)

    output.flush()
    output.close()
    val bytes = output.getBuffer
    print(bytes)

    kryo.setReferences(false)
    kryo.readClassAndObject(new Input(bytes)).asInstanceOf[SingleCrawlRecord]`

`Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to com.crawler.policy.bean.SingleCrawlRecord
	at KryoSerializerTest$.main(KryoSerializerTest.scala:58)
	at KryoSerializerTest.main(KryoSerializerTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

**Comment by magro** [comment]
I'm just reading this on my phone so didn't check in detail. Spotted this `kryo.setReferences(false)`, which you shouldn't do unless references are set to false already anyways. Please check.
