### ISSUE TITLE
Kryo java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by oassuncao** [EsotericSoftware/kryo#456]
I use kryo 3.0.3 to serialize information between my application.

This error occurs when the application B get information of application A. I tried the solution in issue https://github.com/EsotericSoftware/kryo/issues/351 but my problem continues. The code run in Thread Safe

```
com.esotericsoftware.kryo.KryoException:java.lang.IndexOutOfBoundsException: Index: 51, Size: 5 Serialization trace: codes (br.com.me.supplier.message.SupplierEDP) suppliers (br.com.me.supplier.message.SupplierList)
com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
...more...

java.lang.IndexOutOfBoundsException:Index: 51, Size: 5
java.util.ArrayList.rangeCheck(ArrayList.java:653)
java.util.ArrayList.get(ArrayList.java:429)
com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:834)
com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:706)
com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
```

The JSON bellow is the information that application A has.

```
{
  "id": "120442",
  "version": 1,
  "active": true,
  "name": "DEMUTH MÁQUINAS INDUSTRIAIS",
  "tradingName": "DEMUTH MÁQUINAS INDUSTRIAIS",
  "nature": "LegalEntity",
  "additionalInformation": null,
  "country": {
    "name": "Brazil",
    "shortISO": "BR"
  },
  "created": 1463746461558,
  "updated": 1463890676378,
  "statistics": null,
  "documents": [
    {
      "value": "87550505000108",
      "type": {
        "type": "LegalEntity",
        "code": "CNPJ"
      },
      "main": true
    }
  ],
  "addresses": [],
  "contacts": [],
  "codes": [],
  "capitalStock": null,
  "capitalStockCurrency": null
}
```

My kryo instance is configured:

```
        kryo.setDefaultSerializer(new FieldAnnotationAwareSerializer.Factory(
                Arrays.<Class<? extends Annotation>>asList(JsonIgnore.class, JsonBackReference.class), true));

        kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new SerializingInstantiatorStrategy()));
```

I compared the Objects and I saw that application B has a field more named `String clientCode`. If I remove this field this error doesn't occur more.

This field doesn't has in the application A, only in the application B. I think if I doesn't has the field on serialization Kryo will ignore and continue the serialization.

**Comment by oassuncao** [comment]
Debuging kryo with the field `String clientCode` in the application B the kryo read the wrong information, the reader return the object of field `Country country` and not a null object.

**Comment by romix** [comment]
@oassuncao Could you provide a self-contained (JUnit) test that reproduces your issue?

**Comment by oassuncao** [comment]
@romix 

I created repository with tests https://github.com/oassuncao/kryo-bug-example
Step to test:
* Run test of Application A (write a file with serialization)
* Run test of Application B (read the file of application A)
  * The application B have only a field more named "clientCode"

Now I receive the error below. But I think is the same problem

```
com.esotericsoftware.kryo.KryoException: Unable to find class: Country Code
Serialization trace:
country (kryo.application.model.Supplier)

	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:156)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)
	at kryo.example.AppTest.readApplicationA(AppTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: Country Code
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
	... 32 more

```

I'm trying reproduce the same error of IndexOutOfBoundsException

**Comment by oassuncao** [comment]
I created two branchs
- **master** I have the same error above (ClassNotFoundExpcetion)
- **index_exception** I have the error (IndexOutOfBoundsException)

**Comment by oassuncao** [comment]
@romix Did you reproduce the error?

**Comment by magro** [comment]
@oassuncao This is a compatibility issue. You're using the default serializer (FieldSerializer) which does not support any kind of compatibility, according to https://github.com/EsotericSoftware/kryo#compatibility:
> FieldSerializer [..] does not support adding, removing, or changing the type of fields without invalidating previously serialized bytes. This can be acceptable in many situations, such as when sending data over a network, but may not be a good choice for long term data storage because the Java classes cannot evolve.

You should check which alternative serializer suites your needs.
