### ISSUE TITLE
Problem using kryo to custom serialize java object in kafka

### ISSUE THREAD

**Issue by bandops** [EsotericSoftware/kryo#457]
Hi,
     I'm trying to serialize java object using kryo object serializer for writing and reading in kafka queue. For the purpose, I'm not able to extend kryo to serialize a java bean, which is my payload. Here's my  serializer code.

<pre><code>
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.Closeable;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Map;

import org.apache.kafka.common.serialization.Deserializer;
import org.apache.kafka.common.serialization.Serializer;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.ByteBufferInput;
import com.esotericsoftware.kryo.io.ByteBufferOutput;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import com.test.kafka.TextAnalysisRequest;

public class KryoReadingSerializer implements Closeable, AutoCloseable, Serializer, Deserializer {
    private ThreadLocal kryos = new ThreadLocal() {
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            kryo.addDefaultSerializer(TextAnalysisRequest.class, new KryoInternalSerializer());
            return kryo;
        };
    };

    @Override
    public void configure(Map map, boolean b) {
    }

    @Override
    public byte[] serialize(String s, TextAnalysisRequest ta) {
        ByteBufferOutput output = new ByteBufferOutput(100);
        kryos.get().writeObject(output, ta);
        return output.toBytes();
    }

    @Override
    public TextAnalysisRequest deserialize(String s, byte[] bytes) {
        try {
            return kryos.get().readObject(new ByteBufferInput(bytes), TextAnalysisRequest.class);
        }
        catch(Exception e) {
            throw new IllegalArgumentException("Error reading bytes",e);
        }
    }

    /* (non-Javadoc)
     * @see java.io.Closeable#close()
     */
     @Override
     public void close() {
         // TODO Auto-generated method stub

     }

     private static class KryoInternalSerializer extends com.esotericsoftware.kryo.Serializer {
         @Override
         public void write(Kryo kryo, Output output, TextAnalysisRequest ta) {
             System.out.println("Kryo write....");
             kryo.writeClassAndObject(output, ta);
         }

         @Override
         public TextAnalysisRequest read(Kryo kryo, Input input, Class aClass) {
             System.out.println("Kryo read....");
             TextAnalysisRequest ta = null;
             ta = (TextAnalysisRequest)kryo.readClassAndObject(input);
             return ta;
         }
     }
}
</code></pre>

Publishing a java object using write seems to be working, but the serializer fails when it tries to read, used by the kafka consumer. The error originates in  TextAnalysisRequest read(Kryo kryo, Input input, Class aClass) method when being called from  public TextAnalysisRequest deserialize(String s, byte[] bytes). Here's the stacktrace:

<pre><code>
Error -->org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition full-3 at offset 321
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition full-3 at offset 321
Caused by: java.lang.IllegalArgumentException: Error reading bytes
    at com.test.kafka.serialization.KryoReadingSerializer.deserialize(KryoReadingSerializer.java:55)
    at com.test.kafka.serialization.KryoReadingSerializer.deserialize(KryoReadingSerializer.java:1)
    at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:627)
    at org.apache.kafka.clients.consumer.internals.Fetcher.parseFetchedData(Fetcher.java:548)
    at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:354)
    at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1000)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:938)
    at com.test.kafka.consumer.ConsumerGroupSerializerObject1.run(ConsumerGroupSerializerObject1.java:68)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 13994
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
    at com.test.kafka.serialization.KryoReadingSerializer$KryoInternalSerializer.read(KryoReadingSerializer.java:102)
    at com.test.kafka.serialization.KryoReadingSerializer$KryoInternalSerializer.read(KryoReadingSerializer.java:1)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:657)
    at com.test.kafka.serialization.KryoReadingSerializer.deserialize(KryoReadingSerializer.java:52)
    ... 12 more
</code></pre>

My java object.

<pre><code>
public class TextAnalysisRequest implements Serializable {
    public String url;
    public String source; // corresponding to the Source2 assigned in Velocity collection
    public String content;
    public Tag[] tags;
}
</code></pre>

<pre><code>
public class Tag implements Serializable {
    public String name;
    public String value;
    public String weight;
    public Attribute[] attribute;
}
</code></pre>

I'm new to kryo, perhaps not using the right way to read / write an object.

Any pointers will be appreciated.

**Comment by magro** [comment]
Sorry for the late response! Is this still relevant?

**Comment by lvdelu** [comment]
m

**Comment by NathanSweet** [comment]
OP never responded. Also, this is an issue tracker. Please use the mailing list for questions.
