### ISSUE TITLE
StackOverflowError on 2.24.0 and 3.0.3 when serializing tree-like object

### ISSUE THREAD

**Issue by marianoguerra** [EsotericSoftware/kryo#462]
hi, I'm getting a StackOverflowError on kryo 2.24.0 (the one that flink uses), I tried it in 3.0.3 and it also happens, I made a small project that reproduces the problem, it's here:

https://github.com/marianoguerra-atik/kryo-serialize-tree-stack-overflow

the project basically has an interface NodeBase<T> and two classes that implement it:
- `Node<T>`
- `Leaf<T>`

`Leaf<T>` holds a value of T
`Node<T>` holds a `Map<String, NodeBase<T>>`

this builds a tree-like structure, that when serialized fails with the error attached at the end of the issue.

you can reproduce it by running the unit test on the 3 branches:

```
# fails
git checkout kryo-2.24.0
mvn clean test

# fails
git checkout kryo-3.0.3
mvn clean test

# passes
git checkout kryo-4.0.0
mvn clean test
```

The test is simple:

```
Kryo kryo = new Kryo();

Output output = new Output(new FileOutputStream("file.bin"));

Node<Long> node = new Node<Long>();
Node<Long> c1 = new Node<Long>();
node.set("c1", c1);
c1.set("c2", new Leaf<Long>(42L));

kryo.writeObject(output, node);
output.close();

Input input = new Input(new FileInputStream("file.bin"));
Node<Long> result = kryo.readObject(input, Node.class);
input.close();
```

Is it possible to backport whatever fixes the problem from 4.0.0 to 2.24.1 and 3.0.4?

if not, is it something I can do in my code to avoid this problem?

Thanks in advance

The error is:

```
T E S T S
-------------------------------------------------------
Running com.gnandoo.AppTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.125 sec <<< FAILURE! - in com.gnandoo.AppTest
testApp(com.gnandoo.AppTest)  Time elapsed: 0.123 sec  <<< ERROR!
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: com.gnandoo.Leaf
Serialization trace:
childs (com.gnandoo.Node)
childs (com.gnandoo.Node)
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)
    at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)
    at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523)
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:505)
    at com.gnandoo.AppTest.testApp(AppTest.java:47)
Caused by: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: com.gnandoo.Leaf
    at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:48)
    at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:26)
    at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:351)
    at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:344)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:56)
    at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:461)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:79)
    at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:488)
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:593)
    at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)
    at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523)
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61)
    ... 31 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:35)
    ... 43 more
Caused by: java.lang.StackOverflowError
    at java.util.HashMap.hash(HashMap.java:338)
    at java.util.HashMap.get(HashMap.java:556)
    at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:43)
    <last line repeated 100s of times>
```

**Comment by marianoguerra** [comment]
Note: if I remove the <T> and I use a type like long the test passes in 2.24.0 and 3.0.3

**Comment by marianoguerra** [comment]
I added the following line after this one: https://github.com/EsotericSoftware/kryo/blob/kryo-2.24.0/src/com/esotericsoftware/kryo/Generics.java#L49

    if (scope == this) throw new IllegalArgumentException("Can't set parent scope to itself");

and got this stack trace:

	com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Can't set parent scope to itself
	Serialization trace:
	childs (com.gnandoo.Node)
		at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82)
		at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
		at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:505)
		at com.gnandoo.AppTest.testApp(AppTest.java:47)
	Caused by: java.lang.IllegalArgumentException: Can't set parent scope toitself
		at com.esotericsoftware.kryo.Generics.setParentScope(Generics.java:56)
		at com.esotericsoftware.kryo.Kryo.pushGenericsScope(Kryo.java:1132)
		at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:490)
		at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)
		at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)
		at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)
		at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523)
		at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61)
		... 25 more

it seems this line should check that genericsScope != currentScope: https://github.com/EsotericSoftware/kryo/blob/kryo-2.24.0/src/com/esotericsoftware/kryo/Kryo.java#L1132

**Comment by marianoguerra** [comment]
adding the proposed check fixes the problem in my project: 

	if (genericsScope != currentScope) {                                   
		genericsScope.setParentScope(currentScope);                        
	}

let me know if you would like me to provide a PR for 2.24.0 and 3.0.3

**Comment by magro** [comment]
So the issue is fixed in 4.0.0? If you can update the kryo version used by flink, could you change it to 4.0.0?

**Comment by marianoguerra** [comment]
I think they can't see https://issues.apache.org/jira/browse/FLINK-3154

"we cannot bump the Kryo version easily - the serialization format changed (that's why they have a new major version), which would render all Flink savepoints and checkpoints incompatible."

**Comment by magro** [comment]
Just for reference, I just added a [comment to FLINK-3154](https://issues.apache.org/jira/browse/FLINK-3154?focusedCommentId=15785348&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15785348) regarding incompatibility of changes.

**Comment by magro** [comment]
@marianoguerra Can we close this issue here?

**Comment by marianoguerra** [comment]
@magro yes, thanks for your comments.
