### ISSUE TITLE
Lambda serialization problem

### ISSUE THREAD

**Issue by andre-paris** [EsotericSoftware/kryo#469]
I'm using Kryo for serialization inside Hazelcast.
The lambda is sent like this:

``` java
Hazelcast.newHazelcastInstance()
                .getExecutorService("exec")
                .executeOnKeyOwner(() -> {
                    // some code on Runnable.run()
                });
```

Serializer read this way:

``` java
public Object read(ObjectDataInput in) throws IOException {
    Kryo kryo = new Kryo();
    kryo.register(SerializedLambda.class);
    kryo.register(Closure.class, new ClosureSerializer());

    Input input = new Input((InputStream) in);

    return kryo.readClassAndObject(input);
}
```

I got this error:

```
Caused by: java.lang.RuntimeException: Could not serialize lambda
    at com.esotericsoftware.kryo.serializers.ClosureSerializer.write(ClosureSerializer.java:67) ~[kryo-4.0.0.jar:na]
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.0.jar:na]
    at com.paris.sandbox.HazelcastConfig$KryoSerializer.write(HazelcastConfig.java:94) ~[classes/:na]
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:41) ~[hazelcast-3.7.2.jar:3.7.2]
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:199) ~[hazelcast-3.7.2.jar:3.7.2]
    ... 77 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.paris.sandbox.HazelcastRest$$Lambda$17/70747700.writeReplace()
    at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[na:1.8.0_91]
    at com.esotericsoftware.kryo.serializers.ClosureSerializer.write(ClosureSerializer.java:58) ~[kryo-4.0.0.jar:na]
    ... 81 common frames omitted
```

I'm missing something?

Thanks

**Comment by jerrinot** [comment]
Hi @andre-paris,

I believe Kryo requires lambdas to be generated as `Serializable`. Can you try to change it to 
```java
Hazelcast.newHazelcastInstance()
                .getExecutorService("exec")
                .executeOnKeyOwner((Runnable & Serializable) () -> { // <--- instruct lambda factory to create serializable lambdas
                    // some code on Runnable.run()
                }, "key");
```

It won't use the regular Java serialization, but marking it as (Java) serializable is necessary as otherwise generated lambdas won't have all necessary methods.

**Comment by magro** [comment]
@jerrinot thanks for stepping in! I assume this resolved the issue for @andre-paris.
