### ISSUE TITLE
immutable ConfigObject map Problem 

### ISSUE THREAD

**Issue by ailesgrise** [EsotericSoftware/kryo#472]
I was using twitter chill to Serialize my custom class object and got the following error stack

```
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
[error] Serialization trace:
[error] object (com.typesafe.config.impl.SimpleConfig)
[error] config (CpdLogic$CpdLogicCore)
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
Serialization trace:
object (com.typesafe.config.impl.SimpleConfig)
config (CpdLogic$CpdLogicCore)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:107)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:98)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at EnhancedCod$.main(EnhancedCod.scala:97)
    at EnhancedCod.main(EnhancedCod.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
    at com.typesafe.config.impl.AbstractConfigObject.weAreImmutable(AbstractConfigObject.java:193)
    at com.typesafe.config.impl.AbstractConfigObject.put(AbstractConfigObject.java:204)
    at com.typesafe.config.impl.AbstractConfigObject.put(AbstractConfigObject.java:20)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:162)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:107)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:98)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at EnhancedCod$.main(EnhancedCod.scala:97)
    at EnhancedCod.main(EnhancedCod.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
```

My class object does take a typesafe ConfigObject as an input for construction and the configObject is immutable. 

I have no problem writing the object but when I read it again, I get the aforementioned error. 

I am using Scala 2.10.5 using com.twitter chill version 0.8.0.

**Comment by magro** [comment]
Sounds as if you need a custom serializer for the typesafe config class.

**Comment by magro** [comment]
@ailesgrise Is this still an issue for you, or can we close it?
