### ISSUE TITLE
ClassNotFoundException in deserialization

### ISSUE THREAD

**Issue by yonitouitou** [EsotericSoftware/kryo#477]
Hi All,

After reading many posts, i did not find an answer to my issue with kryo.

We are trying to implement Kryo (v4.0.0) in our system that serialize/deserialize a very big quantity of messages between two servers.

Our issue is that the serialization/deserialization can work fine during several minutes (so more than thousand messages) and suddenly stop to work with the following exception : 

```
2016-11-09 13:23:32,968 [AMQP_consumer_blk-ic-p.trade.com_TMSOutWL_TMSOutWL_streaming-1] ERROR Driver handleDelivery -
com.esotericsoftware.kryo.KryoException: Unable to find class: ^AA^]^A^@^A^B^C^_^C ^C!^C^A59927910321794
Serialization trace:
payload (com.trade.common.messagebus.AMQPPacket)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160) ~[kryo-shaded-4.0.0.jar:?]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-shaded-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-shaded-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118) ~[kryo-shaded-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540) ~[kryo-shaded-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-shaded-4.0.0.jar:?]
        at com.tradair.common.serialization.kryo.KryoSerializer.deserialize(KryoSerializer.java:60) ~[common-4.7.3.12.jar:?]
        at com.trade.common.messagebus.AbstractMessageBusConsumer$1.handleDelivery(AbstractMessageBusConsumer.java:106) ~[common-4.7.3.12.jar:?]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144) ~[amqp-client-3.4.3.jar:?]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:95) ~[amqp-client-3.4.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.ClassNotFoundException: ^AA^]^A^@^A^B^C^_^C ^C!^C^A59927910321794
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_40]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_40]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_40]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_40]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_40]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_40]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154) ~[kryo-shaded-4.0.0.jar:?]
        ... 12 more

```

You can see that Kryo does not succeed to read the class name (Unable to find class: ^AA^]^A^@^A^B^C^_^C ^C!^C^A59927910321794).

My serialize class : 

`public class KryoSerializer extends AbstractSerializer {

    private Logger logger = LoggerFactory.getLogger(KryoSerializer.class);
    protected Kryo kryo;
    protected Output output;
    protected Input input;
    protected ByteArrayOutputStream bos;
    protected ByteArrayInputStream bis;

    public KryoSerializer(List<Class> list) {
        kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.setReferences(true);
        for (Class cl : list) {
            kryo.register(cl);
        }
    }

    @Override
    public <T> byte[] serialize(T msg) {
        try {
            bos = new ByteArrayOutputStream();
            output = new Output(bos);
            kryo.writeClassAndObject(output, msg);
            output.flush();
            return bos.toByteArray();
        } finally {
            try {
                if (output != null) {
                    output.close();
                }
                if (bos != null) {
                    bos.close();
                }
            } catch (IOException eio) {
                logger.warn("", eio);
            }
        }
    }

    @Override
    public <T> T deserialize(byte[] bytesArray) {
        try {
            bis = new ByteArrayInputStream(bytesArray);
            input = new Input(bis);
            return (T) kryo.readClassAndObject(input);
        } finally {
            try {
                if (input != null) {
                    input.close();
                }
                if (bis != null) {
                    bis.close();
                }
            } catch (IOException eio) {
                logger.warn("", eio);
            }
        }
    }
}

Please advise 

THanks`

**Comment by magro** [comment]
Not sure if that's related to your issue, but a Kryo instance must be used by a single thread at a time. Is it possible that KryoSerializer is used concurrently from multiple threads?

**Comment by yonitouitou** [comment]
It seems that it was the issue, i am using a KryoPool instance now and it seems to be OK.
An additional small question  : 
Is there a possibility to remove in the serialize and deserialize method the two "new" object (for input/output and inputStream/outputstream ? something like "clean" method in order to work with the same instances all the time ?

Thanks

**Comment by yonitouitou** [comment]
this is my code now with the pool : 
`public class KryoSerializer extends AbstractSerializer {

    private Logger logger = LoggerFactory.getLogger(KryoSerializer.class);
    protected KryoPool kryoPool;
    protected Output output;
    protected Input input;
    protected ByteArrayOutputStream bos;
    protected ByteArrayInputStream bis;

    public KryoSerializer(List<Class> list) {
        kryoPool = new KryoPool.Builder(new KryoFactory() {
            @Override
            public Kryo create() {
                Kryo kryo = new Kryo();
                kryo.setRegistrationRequired(false);
                kryo.setReferences(true);
                for (Class cl : list) {
                    kryo.register(cl);
                }
                return kryo;
            }
        }).build();
    }

    @Override
    public <T> byte[] serialize(T msg) {
        Kryo kryo = kryoPool.borrow();
        try {
            bos = new ByteArrayOutputStream();
            output = new Output(bos);
            kryo.writeClassAndObject(output, msg);
            output.flush();
            return bos.toByteArray();
        } finally {
            kryoPool.release(kryo);
            try {
                if (output != null) {
                    output.close();
                }
                if (bos != null) {
                    bos.close();
                }
            } catch (IOException eio) {
                logger.warn("", eio);
            }
        }
    }

    @Override
    public <T> T deserialize(byte[] bytesArray) {
        Kryo kryo = kryoPool.borrow();
        try {
            bis = new ByteArrayInputStream(bytesArray);
            input = new Input(bis);
            return (T) kryo.readClassAndObject(input);
        } finally {
            kryoPool.release(kryo);
            try {
                if (input != null) {
                    input.close();
                }
                if (bis != null) {
                    bis.close();
                }
            } catch (IOException eio) {
                logger.warn("", eio);
            }
        }
    }
}
`

**Comment by magro** [comment]
Can you create a reproducable example for this?

**Comment by yonitouitou** [comment]
Unfortunately i cannot give a reproducible example. It occur in the complex scenario between three servers (same kryo serialize/deserialize code for the three servers) that streamed a very big quantity of messages.

Do you have some reasons of this issue and directions to give me to solve it?
Can you confirm me that the multi-threading issue is solved with my KryoPool implementation ?

**Comment by magro** [comment]
Yes, `KryoPool` solves multithreading issues regarding `Kryo`.
Your `KryoSerializer` has Output, Input and BAOS/BAIS as fields, therefore it must not be used concurrently by different threads - you'd have to synchronize this. Probably you want to create these resources within serialize/deserialize.

**Comment by yonitouitou** [comment]
Hi Magro,

I added synchronized in the methods serialize/deserialize.
During several days, i did not receive any exception but yesterday with the following code i receive the following exception : 

`public class KryoSerializer extends AbstractSerializer {

    private Logger logger = LoggerFactory.getLogger(KryoSerializer.class);
    protected KryoPool kryoPool;
    protected Output output;
    protected Input input;
    protected ByteArrayOutputStream bos;
    protected ByteArrayInputStream bis;

    public KryoSerializer() {
        kryoPool = new KryoPool.Builder(new KryoFactory() {
            @Override
            public Kryo create() {
                Kryo kryo = new Kryo();
                kryo.setRegistrationRequired(false);
                kryo.setReferences(true);
                kryo.register(AMQPPacketProperties.class);
                kryo.register(AMQPPacket.class);
                return kryo;
            }
        }).build();
    }

    @Override
    public synchronized <T> byte[] serialize(T msg) {
        Kryo kryo = kryoPool.borrow();
        try {
            bos = new ByteArrayOutputStream();
            output = new Output(bos);
            kryo.writeClassAndObject(output, msg);
            output.flush();
            return bos.toByteArray();
        } finally {
            kryoPool.release(kryo);
            try {
                if (output != null) {
                    output.close();
                }
                if (bos != null) {
                    bos.close();
                }
            } catch (IOException eio) {
                logger.warn("", eio);
            }
        }
    }

    @Override
    public synchronized <T> T deserialize(byte[] bytesArray) {
        Kryo kryo = kryoPool.borrow();
        try {
            bis = new ByteArrayInputStream(bytesArray);
            input = new Input(bis);
            return (T) kryo.readClassAndObject(input);
        } finally {
            kryoPool.release(kryo);
            try {
                if (input != null) {
                    input.close();
                }
                if (bis != null) {
                    bis.close();
                }
            } catch (IOException eio) {
                logger.warn("", eio);
            }
        }
    }`



EXCEPTION : 

`>>> TMS : [FixPlatform [streamingDriver=Driver [platformName=TMSInCS_streaming, isOnline=false, wideSpreadOn=false, propertyFilePath=C:\tradair/config/drivers/, uniqueInstanceIdentifier=1399732907], tradingDriver=Driver [platformName=TMSInCS_trading, isOnline=false, wideSpreadOn=false, propertyFilePath=C:\tradair/config/drivers/, uniqueInstanceIdentifier=1904259679], rfqDriver=null, parentToString()=Platform [id=1016, name=TMSInCS, online=false, enabled=false, role=TAKER, metaData=PlatformMetaData [senderId=TradairMakerClientCS1-STREAMING, targetId=TradairMakerSeverCS1-STREAMING, url=proxy-p.tradair.com:5533, protocol=, platformMarketTypeEnum=book, platformOrderTypeData=PlatformOrderTypeData [orderData={market=[ioc], limit=[ioc, fok], previouslyQuoted=[ioc]}], supportRestingOrder=false, supportRFS=true, supportNDF=true, supportNDS=true, platformType=TradairMakerServerClient, isManualRFS=false, isPriceImprovmentRfs=true, supportSecondCurrency=true, supportsVwap=false]]], FixPlatform [streamingDriver=Driver [platformName=TMSOutCSWL_streaming, isOnline=false, wideSpreadOn=false, propertyFilePath=C:\tradair/config/drivers/, uniqueInstanceIdentifier=825089105], tradingDriver=Driver [platformName=TMSOutCSWL_trading, isOnline=false, wideSpreadOn=false, propertyFilePath=C:\tradair/config/drivers/, uniqueInstanceIdentifier=1187402783], rfqDriver=null, parentToString()=Platform [id=841, name=TMSOutCSWL, online=false, enabled=false, role=MAKER, metaData=PlatformMetaData [senderId=, targetId=, url=proxy-p.tradair.com:, protocol=FIX.4.2, platformMarketTypeEnum=book, platformOrderTypeData=PlatformOrderTypeData [orderData={market=[ioc], limit=[ioc, fok], previouslyQuoted=[ioc]}], supportRestingOrder=false, supportRFS=true, supportNDF=true, supportNDS=true, platformType=TradairMakerServer, isManualRFS=false, isPriceImprovmentRfs=true, supportSecondCurrency=true, supportsVwap=false]]]]
2016-11-21 20:31:23,685 [AMQP_consumer_it's me :)_Platforms_Platforms-1] ERROR TnetApi publish - 
com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
beanClassLoader (org.springframework.beans.factory.support.DefaultListableBeanFactory)
beanFactory (org.springframework.dao.support.PersistenceExceptionTranslationInterceptor)
advice (org.springframework.dao.annotation.PersistenceExceptionTranslationAdvisor)
advisorArray (org.springframework.aop.framework.ProxyFactory)
advised (org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor)
CGLIB$CALLBACK_0 (com.tradair.ic.services.ccpairs.CcPairRepository$$EnhancerBySpringCGLIB$$2f9f66b1)
ccPairRepository (com.tradair.ic.services.ccpairs.CcPairService)
ccPairService (com.tradair.ic.services.platform.ccpairsubscriptions.PlatformCcPairSubscriptionsService)
platformCcPairSubscriptionsService (com.tradair.ic.services.platform.PlatformService)
platformService (com.tradair.tnet.services.DriverLoaderService)
driverLoaderService (com.tradair.tnet.services.DriverManager)
driverManager (com.tradair.ic.services.platform.PlatformManager)
platformManager (com.tradair.ic.controllers.AccountsController)
accountsController (com.tradair.ic.network.IcApi)
icApi (com.tradair.tnet.services.DriverAccountService)
driverAccountService (com.tradair.tnet.driver.fix.client.server.TradairServerMakerClientClient)
dedicatedConnector (com.tradair.tnet.driver.fix.server.TradairServerMakerClientDriver)
streamingDriver (com.tradair.ic.services.platform.datamodel.FixPlatform)
platformList (com.tradair.common.integrationcenter.tos.PlatformListMessage)
payload (com.tradair.common.messagebus.AMQPPacket)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:362) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:303) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:505) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-shaded-4.0.0.jar:?]
	at com.tradair.common.serialization.kryo.KryoSerializer.serialize(KryoSerializer.java:48) ~[classes/:?]
	at com.tradair.common.messagebus.AbstractMessageBusProducer.sendMessage(AbstractMessageBusProducer.java:114) ~[classes/:?]
	at com.tradair.common.messagebus.AbstractMessageBusProducer.publish(AbstractMessageBusProducer.java:83) ~[classes/:?]
	at com.tradair.ic.api.TnetApi.sendAvailablePlatforms(TnetApi.java:101) ~[classes/:?]
	at com.tradair.ic.api.TnetApi.handleMessage(TnetApi.java:59) ~[classes/:?]
	at com.tradair.common.messagebus.AbstractMessageBusConsumer$1.handleDelivery(AbstractMessageBusConsumer.java:111) ~[classes/:?]
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144) ~[amqp-client-3.4.3.jar:?]
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:95) ~[amqp-client-3.4.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1184) ~[?:1.8.0_60]
	at java.util.Vector$Itr.next(Vector.java:1137) ~[?:1.8.0_60]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:99) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-shaded-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-shaded-4.0.0.jar:?]
	... 79 more
2016-11-21 20:31:45,992 [Broadway_trading] INFO  FixClient toAdmin - Broadway_trading - sending logon message...
2016-11-21 20:31:45,992 [Broadway_streaming] INFO  FixClient toAdmin - Broadway_streaming - sending logon message...
2016-11-21 20:31:47,578 [NioProcessor-24] INFO  FixClient onLogout - After logout to platform: Broadway_trading
2016-11-21 20:31:47,578 [NioProcessor-21] INFO  FixClient onLogout - After logout to platform: Broadway_streaming
2016-11-21 20:32:15,497 [pool-4-thread-1] INFO  PlatformsWatchdogService  - Sending empty book for instruments : Instrument [[-1-EURUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]Instrument [[-1-GBPUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]
2016-11-21 20:32:15,497 [pool-4-thread-1] INFO  PlatformsWatchdogService  - Sending empty book for instruments : Instrument [[-1-EURUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]Instrument [[-1-GBPUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]
2016-11-21 20:32:27,630 [Broadway_trading] INFO  FixClient toAdmin - Broadway_trading - sending logon message...
2016-11-21 20:32:27,632 [Broadway_streaming] INFO  FixClient toAdmin - Broadway_streaming - sending logon message...
2016-11-21 20:32:32,816 [NioProcessor-23] INFO  FixClient onLogout - After logout to platform: Broadway_trading
2016-11-21 20:32:32,816 [NioProcessor-20] INFO  FixClient onLogout - After logout to platform: Broadway_streaming
2016-11-21 20:32:45,497 [pool-4-thread-1] INFO  PlatformsWatchdogService handlePlatformFilterMessage - Sending empty book for instruments : Instrument [[-1-EURUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]Instrument [[-1-GBPUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]
2016-11-21 20:32:45,497 [pool-4-thread-1] INFO  PlatformsWatchdogService handlePlatformFilterMessage - Sending empty book for instruments : Instrument [[-1-EURUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]Instrument [[-1-GBPUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]
2016-11-21 20:33:09,310 [Broadway_trading] INFO  FixClient toAdmin - Broadway_trading - sending logon message...
2016-11-21 20:33:09,310 [Broadway_streaming] INFO  FixClient toAdmin - Broadway_streaming - sending logon message...
2016-11-21 20:33:10,814 [NioProcessor-22] INFO  FixClient onLogout - After logout to platform: Broadway_trading
2016-11-21 20:33:10,814 [NioProcessor-19] INFO  FixClient onLogout - After logout to platform: Broadway_streaming
2016-11-21 20:33:15,493 [pool-4-thread-1] INFO  PlatformsWatchdogService handlePlatformFilterMessage - Sending empty book for instruments : Instrument [[-1-EURUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]Instrument [[-1-GBPUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]
2016-11-21 20:33:15,493 [pool-4-thread-1] INFO  PlatformsWatchdogService handlePlatformFilterMessage - Sending empty book for instruments : Instrument [[-1-EURUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]Instrument [[-1-GBPUSD, isNdf: false, isSpot: false, term: Term [id=-1, name=Spot, shortName=SP, length=-1], isMetal: false, isSupportLots: false, eod: 12:00, isCFD: false, contractSize: 0.0, displayName: ],[1-SPOT]]
`

**Comment by magro** [comment]
Not related to the exception, but I'd prefer to create these resources (Output, Input and BAOS/BAIS) within serialize/deserialize, instead of synchronizing serialize/deserialize (with synchronization different threads affect each other).

Regarding the exception: if you look at the stack trace you'll see that the beanFactory and its classloader (basically your whole application state) gets serialized - most probably you don't want this to happen. You should think about what *should* be serialized and then see how to achieve this - this depends on your application and state.

**Comment by magro** [comment]
@yonitouitou Is this still an issue, or can we close it?
