### ISSUE TITLE
Kryo IndexOutOfBoundsException Index: 221805, Size: 5 in MapReferenceResolver

### ISSUE THREAD

**Issue by fatalcubez** [EsotericSoftware/kryo#482]
Here is the console output

`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 221805, Size: 5
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:707)
	at com.fullspectrum.level.NavMesh$NavMeshSerializer.read(NavMesh.java:689)
	at com.fullspectrum.level.NavMesh$NavMeshSerializer.read(NavMesh.java:1)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at com.fullspectrum.level.NavMesh.createNavMesh(NavMesh.java:110)
	at com.fullspectrum.game.GameScreen.<init>(GameScreen.java:238)
	at com.fullspectrum.game.GdxGame.create(GdxGame.java:74)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:275)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:242)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
	at com.fullspectrum.game.desktop.DesktopLauncher.main(DesktopLauncher.java:14)
`
In my code I register my classes like this:
``` java
Kryo kryo = new Kryo();
Log.TRACE();
kryo.register(NavMesh.class, getSerializer(), 10);
kryo.register(Node.class, Node.getSerializer(), 11);
kryo.register(NavLink.class, NavLink.getSerializer(), 12);
kryo.register(TrajectoryData.class, TrajectoryData.getSerializer(), 13);
kryo.register(JumpOverData.class, JumpOverData.getSerializer(), 14);
```

This is consistent when serializing and deserializing. I've been digging around through all the various other issues people are having, but none of the solutions are working for me. I also looked through Kryo.java a bit to try and understand how it works, but it's too complicated for me. I guess I don't fully understand how Kryo works to understand why something like this is happening.

Btw, all writing/reading is in exactly the same order. Here is how I write/read

``` java
              @Override
		public void write(Kryo kryo, Output output, NavMesh object) {
			output.writeShort((short)object.nodes.size);
			for(Node n : object.nodes){
				kryo.writeObject(output, n);
				output.writeByte((byte)n.getLinks().size);
				for(NavLink link : n.getLinks()){
					kryo.writeObject(output, link);
				}
			}
		}

		@Override
		public NavMesh read(Kryo kryo, Input input, Class<NavMesh> type) {
			NavMesh mesh = new NavMesh();
			int size = input.readShort();
			for(int i = 0; i < size; i++){
				Node node = kryo.readObject(input, Node.class);
				mesh.nodes.add(node);
				mesh.nodeMap.put(new Point(node.row, node.col), node);
				if(node.type == NodeType.LEFT_EDGE || node.type == NodeType.SOLO || node.type == NodeType.RIGHT_EDGE) {
					mesh.edgeNodes.add(node);
				}
				byte numLinks = input.readByte();
				for(int j = 0; j < numLinks; j++){
					NavLink link = kryo.readObject(input, NavLink.class);
					node.addLink(link);
					link.fromNode = node;
				}
			}
			for(Node n : mesh.nodes){
				for(NavLink link : n.getLinks()){
					link.toNode = mesh.nodeMap.get(new Point(link.toRow, link.toCol));
					if(link.data instanceof TrajectoryData){
						TrajectoryData data = (TrajectoryData) link.data;
						data.toNode = mesh.nodeMap.get(new Point(data.toRow, data.toCol));
					}
				}
			}
			return mesh;
		}
```
The program is able to read the first `Node` and the first two `NavLink` s but consistently fails when reading in the second `Node`.

All help is appreciated! Thanks!

**Comment by magro** [comment]
Is this still an issue for you? If so, can you reduce it to have a reproducable test case that you can share?

**Comment by fatalcubez** [comment]
No its no longer an issue. Thanks to Eclipse's auto-complete feature, my read/write methods didn't all match and my serialization was a few bytes off causing the index to be a giant integer. *sigh*. That's about 6 hours of my life I'll never get back.

Anyways, the issue can be closed.

**Comment by magro** [comment]
Great that you solved it!
