### ISSUE TITLE
ClassNotFoundException from JavaSerializer in Apache Spark shell

### ISSUE THREAD

**Issue by heuermh** [EsotericSoftware/kryo#489]
Copied from comment at https://github.com/EsotericSoftware/kryo/issues/444#issuecomment-272472529

...I'm seeing similar stack traces with `JavaSerializer` in the context of the Apache Spark Scala shell
```
scala> doSomething()
...
Caused by: java.lang.ClassNotFoundException: org.MyClass
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
  at com.esotericsoftware.kryo.serializers.JavaSerializer.read(JavaSerializer.java:63)
  ... 35 more
```

MyClass is clearly on the classpath
```
scala> import org.MyClass
import org.MyClass
```

Registrator
```java
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.serializers.JavaSerializer;
import org.MyClass;

public class MyClassKryoRegistrator extends SomeOtherKryoRegistrator {
    @Override
    public void registerClasses(final Kryo kryo) {
        super.registerClasses(kryo);
        kryo.register(MyClass.class, new JavaSerializer());
    }
}
```

The runtime classpath for this is quite complex, and in fact there are multiple versions of kryo present
```
$ mvn dependency:tree
...
[INFO] +- org.apache.spark:spark-core_2.11:jar:2.1.0:provided
[INFO] |  +- org.apache.avro:avro-mapred:jar:hadoop2:1.7.7:provided
[INFO] |  |  +- org.apache.avro:avro-ipc:jar:1.7.7:provided
[INFO] |  |  +- org.apache.avro:avro-ipc:jar:tests:1.7.7:provided
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  +- com.twitter:chill_2.11:jar:0.8.0:provided
[INFO] |  |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:provided
...
[INFO] +- org.bdgenomics.adam:adam-core-spark2_2.11:jar:0.21.0:compile
[INFO] |  +- org.bdgenomics.utils:utils-metrics-spark2_2.11:jar:0.2.11:compile
[INFO] |  |  \- org.bdgenomics.utils:utils-misc-spark2_2.11:jar:0.2.11:compile
[INFO] |  +- org.bdgenomics.utils:utils-io-spark2_2.11:jar:0.2.11:compile
[INFO] |  +- org.bdgenomics.utils:utils-cli-spark2_2.11:jar:0.2.11:compile
[INFO] |  |  \- args4j:args4j:jar:2.0.23:compile
[INFO] |  +- org.bdgenomics.utils:utils-intervalrdd-spark2_2.11:jar:0.2.11:compile
[INFO] |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:compile
```

I will attempt to reduce the dependencies necessary to reproduce the issue.

**Comment by heuermh** [comment]
The class loader provided to the Kryo registrator is not the one used by the Spark shell
```
scala> doSomething()
[TRACE] MyClassKryoRegistrator.registerClasses,
current classLoader: org.apache.spark.repl.ExecutorClassLoader@6070abbc

scala> Thread.currentThread.getContextClassLoader
res1: ClassLoader = scala.tools.nsc.interpreter.IMain$TranslatingClassLoader@323bfedf
```

Will continue to investigate.

**Comment by idlefella** [comment]
I experience the same error. Did you find a solution for this problem?

**Comment by magro** [comment]
Can you debug who's setting/overriding the classloader on kryo? Perhaps discuss this with the Spark shell guys?

**Comment by heuermh** [comment]
@idlefella I ran into this issue in a project with a complicated dependency tree ([1](https://github.com/heuermh/dishevelled-bio/tree/master/adam), [2](https://github.com/heuermh/dishevelled-bio/tree/master/convert), [3](https://github.com/bigdatagenomics/bdg-convert), [4](https://github.com/bigdatagenomics/adam), [5](https://github.com/bigdatagenomics/utils), then Spark); I need to find time to create a limited test case that still demonstrates the issue.

@magro I'll test if this issue also occurs in `spark-submit`.

**Comment by idlefella** [comment]
I ran into this issue while porting the dbpedia spotlight project (https://github.com/dbpedia-spotlight/dbpedia-spotlight) to spark. The problem appears when you try to load the trained models from a folder. Then it needs to deserialize the data. I solved the problem in my case. It turned out that if you implement your own JavaSerializer class (e.g. just copy the JavaSerializer.java source to a new file in your project) and use it in the project, it works. Don't ask me why, I'm not an expert in how the classes are loaded in java. The commit which solved the problem is this one: https://github.com/trivo-ch/dbpedia-spotlight/commit/78ee74f93b6a2cafab85e1bde36c365ad8d139b3 (and of course the commit message should be "make it work with scala and spark", I think I was tired :D )

**Comment by magro** [comment]
Btw, in `JavaSerializer` there was recently an improvement regarding the CL: https://github.com/EsotericSoftware/kryo/commit/19a6b5e

You could try to update the kryo version to 4.0.1-SNAPSHOT (see also https://github.com/EsotericSoftware/kryo#integration-with-maven) and see if this resolves the issue.

**Comment by idlefella** [comment]
@magro Yes I've seen this. The problem is that we're using a precompiled version of spark on our cluster from a "bigdata distributor". It comes with version 3.0.3 and I can't replace the dependency. If I have time I will try to make a local test with version 4.

**Comment by magro** [comment]
@idlefella ok

**Comment by shaofengshi** [comment]
I also got the same issue when use Kryo with spark; Hope the fix can be released as earlier as possible.

**Comment by rvvincelli** [comment]
Hi, not sure if this comment is relevant but on Kryo 4.0.1, Chill 0.8.0 and Spark 2.1.0 the executor still can't handle meatlocking with `Externalizer` when deploying in local mode with `spark-submit` - I get this class lookup failure on the wrapped domain class. Thanks,

**Comment by magro** [comment]
Also related:
https://github.com/twitter/chill/issues/246
https://github.com/twitter/chill/issues/194
