### ISSUE TITLE
An ArrayIndexOutOfBoundsException be thrown when serialize some java basic type in IdentityObjectIntMap.java:243

### ISSUE THREAD

**Issue by lazyjack001** [EsotericSoftware/kryo#496]
Version:kryo-3.0.0.jar
Exception:
Caused by: java.lang.ArrayIndexOutOfBoundsException: 53
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.get(IdentityObjectIntMap.java:243)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getWrittenId(MapReferenceResolver.java:28)
	at com.esotericsoftware.kryo.Kryo.writeReferenceOrNull(Kryo.java:644)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:619)
	at com.utraffic.cbb.common.data.MessageDataSerializer.write(MessageDataSerializer.java:79)
	at com.utraffic.cbb.common.data.MessageDataSerializer.write(MessageDataSerializer.java:19)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:530)

**Comment by lazyjack001** [comment]
How to fix it, thanks.

**Comment by magro** [comment]
How to reproduce it, thanks. ;-)

**Comment by lazyjack001** [comment]
I guess that It could reproduce when kryo run in multi threads.  After I find kryo is not thread safe, but  I would know  why kryo don't keep thread safe instead of kryo object pool to improve performance. Thanks.
------------------------------------
"Kryo is not thread safe. Each thread should have its own Kryo, Input, and Output instances. Also, the byte[] Input uses may be modified and then returned to its original state during deserialization, so the same byte[] "should not be used concurrently in separate threads."

**Comment by magro** [comment]
Kryo is behaving correct according to the specification in this regard, it's just designed this way. Therfore I'm closing this.
