### ISSUE TITLE
Add workaround for serializing very large object trees to documentation.

### ISSUE THREAD

**Issue by AlbertWeichselbraun** [EsotericSoftware/kryo#497]
This issue is related to #382  and #258.

We are serializing large profiles for named entity linking:
- entity objects: > 2.8 Mio
- relation objects: > 511 Mio
- primitives: int (> 1E9); primitives long (> 500 mio)

which leads to the following error message
```
Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.lang.NegativeArraySizeException
Serialization trace:
relations (com.weblyzard.backend.recognize.data.Lexicon)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:624)
        at com.weblyzard.lib.serialize.KryoSerializer.serialize(KryoSerializer.java:26)
        at com.weblyzard.lib.serialize.Serializers.serialize(Serializers.java:100)
        at com.weblyzard.lib.serialize.Serializers.serialize(Serializers.java:54)
        at com.weblyzard.backend.recognize.console.Composer.convertProfile(Composer.java:134)
        at com.weblyzard.backend.recognize.console.Composer.main(Composer.java:49)
Caused by: java.lang.NegativeArraySizeException
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.resize(IdentityObjectIntMap.java:427)
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putStash(IdentityObjectIntMap.java:227)
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.push(IdentityObjectIntMap.java:221)
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.put(IdentityObjectIntMap.java:117)
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putStash(IdentityObjectIntMap.java:228)
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.push(IdentityObjectIntMap.java:221)
        at com.esotericsoftware.kryo.util.IdentityObjectIntMap.put(IdentityObjectIntMap.java:117)
        at com.esotericsoftware.kryo.util.MapReferenceResolver.addWrittenObject(MapReferenceResolver.java:23)
        at com.esotericsoftware.kryo.Kryo.writeReferenceOrNull(Kryo.java:654)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:619)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:82)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:22)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:624)
        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)
        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:548)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61)
        ... 7 more
```
As outlined in #382 this problem is caused by an integer overflow in `IdentityObjectIntMap`.

A workaround for this issue is to set kryo's setReferences feature to `false` since this disables identity comparisons that rely on `IdentityObjectIntMap`:

```java
 Kryo kryo = new Kryo();
 kryo.setReferences(false);
```
May I suggest to add this information regarding large object serialization to the documentation.

Another option to handle this would be to change `IdentityObjectIntMap` so that it is able to more than`Integer.MAX_VALUE` objects.

**Comment by magro** [comment]
Thanks for the suggestion, do you want to submit a pull request?

**Comment by AlbertWeichselbraun** [comment]
done.
cheers, albert :)
