### ISSUE TITLE
How  to serialize/deserialize a Exception?

### ISSUE THREAD

**Issue by liukefeng2008** [EsotericSoftware/kryo#510]
I have a trouble with deserialize a exception:
```
public class KryoSerializerTest {
    private ISerializer serializer = new KryoSerializer();
    @Test
    public  void testSerializeAndDeSerialize() {
        LocalDateTime now = LocalDateTime.now();
        byte[] buffer = serializer.serialize(now);
        LocalDateTime serializeNow = serializer.deserialize(buffer);
        System.out.println(serializeNow);
        Throwable throwable = new Throwable();
        buffer = serializer.serialize(throwable);
        throwable = serializer.deserialize(buffer);
        throwable.printStackTrace();
        IllegalStateException illegalStateException = new IllegalStateException(throwable);
        IllegalArgumentException illegalArgumentException = new IllegalArgumentException(illegalStateException);
        buffer = serializer.serialize(illegalArgumentException);
        IllegalArgumentException newException = serializer.deserialize(buffer);
        newException.printStackTrace();
    }
}

```
Kryo will throw exception:
```
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.Collections$UnmodifiableRandomAccessList
Serialization trace:
suppressedExceptions (java.lang.IllegalStateException)
cause (java.lang.IllegalArgumentException)

	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1310)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136)

        balabala
```
What should I do?

**Comment by liukefeng2008** [comment]
I have two solutions:
first one: use cutome exception protocol
second:regist common exception(e.g.RemoteException)
