### ISSUE TITLE
After deserializing collection type object, Kryo fails to reset collectionSerializer

### ISSUE THREAD

**Issue by Barala** [EsotericSoftware/kryo#512]
[kryoBug.zip](https://github.com/EsotericSoftware/kryo/files/978671/kryoBug.zip)

We read byteBuffer from a file and try to deserialize and returns a correct object (List PeculiarClass).

But just after deserializing, We try to serialize another collection type(List SampleCustomizeClass) then Kryo throws below error:-

`java.lang.ClassCastException: serializer.arraylistprob.SampleCustomizeClass cannot be cast to java.lang.Integer
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$IntSerializer.write(DefaultSerializers.java:127)
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:603)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:93)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:531)`

**The structure of PeculiarClass::
------------------------------------------**
``` 
public class PeculiarClass {
    private List<Integer> costCategories;
    public PeculiarClass() {
        // TODO Auto-generated constructor stub
    }

    public List<Integer> getCostCategories() {
        return costCategories;
    }

    public void setCostCategories(List<Integer> costCategories) {
        this.costCategories = costCategories;
    }
 }
```

**SampleCustomizeClass can be any custom type**

**Note:** 
* We are using **CompatibleFieldSerializer.**
* If we create new kryo instance then the problem does not happen.

It seems Kryo instance is not able to clear the references after deserializing the data.

Please do let us know If you need more info on this.
Could anyone please tell us why is it happening.

**Comment by magro** [comment]
I assume this happens with kryo 4? If not, can you please try 4.0.0?

Can you try calling Kryo.reset explicitly (although by default Kryo.autoReset is enabled)? 

Does this happen as well if you use FieldSerializer?

**Comment by Barala** [comment]
Thanks a lot for your response!!

* We are using **3.0.1**
* I tried resetting explicitly but didn't work
* Since data is written using compatibleFieldSerializer so not able to use FieldSerializer.
* It happens for particular data so I have that data, not able to generate data by on my own.

* tried with 4.0.0 as well but It seems 3.0.1 data is not compatible with 4.0.0
`Exception in thread "main" com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
costCategories (kryo.problem.CustomizeType)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:470)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:150)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)`

**Comment by magro** [comment]
Can you try to create/provide a reproducable test case?

**Comment by magro** [comment]
I'm closing this for now, please reopen if still relevant.
