### ISSUE TITLE
Kryo cannot serialize Java exceptions

### ISSUE THREAD

**Issue by danielyli** [EsotericSoftware/kryo#532]
When attempting to unserialize a throwable, Kryo gives the following exception:

```
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.time.zone.ZoneRulesException
  at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1310)
  at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127)
  at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:559)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:535)
  at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
  ... 42 elided
```

Throwables are a pretty integral part of the Java library.  Any way to add support?

**Comment by magro** [comment]
You could set the `JavaSerializer` as default serializer for `Throwable`: `kryo.addDefaultSerializer(java.lang.Throwable.class, new JavaSerializer());`

Alternatively write a dedicated serializer and maybe submit a pull request :-)

**Comment by danielyli** [comment]
I’d be happy to write something, but I’m having difficulty understanding the the error message.  Most (if not all) standard `Throwable`s have a zero-argument constructor already.  Why is Kryo not detecting it?

**Comment by isaki-x** [comment]
Because there isn't one.

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/zone/ZoneRulesException.java

**Comment by magro** [comment]
I'm closing this for now, please reopen if still relevant.
