### ISSUE TITLE
Switching version, keeping serialized files.

### ISSUE THREAD

**Issue by PatrikSchulze** [EsotericSoftware/kryo#536]
In short I am reviving an old project which used Kryo 2.20 at the time and had already many files serialized.
Now when I switch to latest (4.0.1) and load then it crashes.

`com.esotericsoftware.kryo.KryoException: java.lang.ArrayStoreException: java.lang.Long
Serialization trace:
mapData (game.SerializableGameMapData)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	...
Caused by: java.lang.ArrayStoreException: java.lang.Long
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:391)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:302)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	... 6 more`

Question is: Is this a bug and it _ought_ to work, or is this pretty much expected and if so, is there a strategy to fix this, like saving or loading the files with different options or something?

**Comment by isaki-x** [comment]
Moving from 2.20 to 4.0.1 crosses multiple changes that break binary compatibility. I'll defer to the Kryo authors regarding if there is some magic way to convert your files, but I strongly suspect their isn't; it is likely brute force is in order.

**Comment by magro** [comment]
Right, for serialization libraries it's more required to read the changelog carefully than for (nearly) every other library ;-)

From 2.x to 3.x the Unsafe base IO format was changed according to the [changelog entry](https://github.com/EsotericSoftware/kryo/blob/master/CHANGES.md#2240---300-2014-10-04), i.e. if this IO strategy is/was used a custom migration has to be done.
With 4.x the generics serialization format was changed, the related [changelog](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-4.0.0) contains advices how to restore the former behaviour.

Does this help?

**Comment by NathanSweet** [comment]
Please use the mailing list for questions. This is an issue tracker.
