### ISSUE TITLE
CompatibleFieldSerializer forward compatibility - ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by tonyyuzhao** [EsotericSoftware/kryo#554]
We are using Kryo in production software and noticed a forward compatibility issue.
The issue arises when we read bytes serialized by a newer class that has multiple new fields (i.e. from the serialize perspective, when multiple fields are removed).

We initially noticed this issue in version `3.0.3` but the issue persists with latest `4.0.2-SNAPSHOT`. In both cases an `ArrayIndexOutOfBoundsException` is thrown.

Your unit tests do not cover the case where more than one field is added or removed.
**We wrote a unit test in** `CompatibleFieldSerializerTest.java` (using origin/master)  **that illustrates this issue:**
```
public void testRemovedMultipleFieldsFromClassWithManyFields() throws FileNotFoundException {
	// class must have more than CompatibleFieldSerializer#THRESHOLD_BINARY_SEARCH number of fields
	ClassWithManyFields object1 = new ClassWithManyFields();
	object1.aa = "aa";
	object1.bb = "bb";
	object1.cc = "cc";
	object1.dd = "dd";
	object1.ee = "ee";
	object1.ff = "ff";
	object1.gg = "gg";
	object1.hh = "hh";
	object1.ii = "ii";
	object1.jj = "jj";
	object1.kk = "kk";
	object1.ll = "ll";
	object1.mm = "mm";
	object1.nn = "nn";
	object1.oo = "oo";
	object1.pp = "pp";
	object1.qq = "qq";
	object1.rr = "rr";
	object1.ss = "ss";
	object1.tt = "tt";
	object1.uu = "uu";
	object1.vv = "vv";
	object1.ww = "ww";
	object1.xx = "xx";
	object1.yy = "yy";
	object1.zz = "zz";

	kryo.register(ClassWithManyFields.class, new CompatibleFieldSerializer(kryo, ClassWithManyFields.class));
	roundTrip(220, 220, object1);

	CompatibleFieldSerializer serializer = new CompatibleFieldSerializer(kryo, ClassWithManyFields.class);
	serializer.removeField("bb");
	serializer.removeField("cc");
	serializer.removeField("dd");

	kryo.register(ClassWithManyFields.class, serializer);

	//pre-junit 4 as this class extends TestCase
	try {
		kryo.readClassAndObject(input);
		fail();
	} catch (ArrayIndexOutOfBoundsException e) {
		e.printStackTrace();
	}
}
```

**The logged stack trace is as follows:**
```
java.lang.ArrayIndexOutOfBoundsException: 35
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:111)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:816)
	at com.esotericsoftware.kryo.CompatibleFieldSerializerTest.testRemovedMultipleFieldsFromClassWithManyFields(CompatibleFieldSerializerTest.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by marcusbb** [comment]
I've also encountered the same issue.  Running this test removing 1 or 2 fields achieves correct behaviour.  However, the threshold for removal of fields is 2.  Removing any more than that results in an index out of bounds exception.
