### ISSUE TITLE
Pls, I need some help. When I deSerialize a nested object, I got a 

### ISSUE THREAD

**Issue by xuxingyude** [EsotericSoftware/kryo#557]
my serialize and deSerilize func are this 
```
    public static byte[] serialize(final Kryo kryo, final Object obj)
    {
        if (obj == null)
        {
            throw new IllegalArgumentException("serialize Object is null");
        }

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Output output = new Output(outputStream);
        kryo.writeObject(output, obj);
        output.close();
        return CompressUtil.snappyCompress(outputStream.toByteArray());
    }

    public static <T> T deSerialize(final Kryo kryo, final byte[] bytes, final Class<T> clazz)
    {
        if (bytes == null || bytes.length == 0)
        {
            throw new IllegalArgumentException("deSerialize Class<T>  bytes is null or empty");
        }

        final byte[] uncompressed = CompressUtil.snappyUncompress(bytes);
        return kryo.readObject(new Input(uncompressed), clazz);
    }
```
my deSerilize object is this 
```
public class ConnLinkListWrapper extends ListWrapper<ConnLink>
{
    public ConnLinkListWrapper()
    {

    }

    public ConnLinkListWrapper(List<ConnLink> linkList)
    {
        super(linkList);
    }
}
public class ListWrapper<T>
{
    protected List<T> list;

    public ListWrapper()
    {
    }

    public ListWrapper(List<T> list)
    {
        this.list = list;
    }

    public List<T> getList()
    {
        return list;
    }

    public void setList(List<T> list)
    {
        this.list = list;
    }
}
public class ConnLink
{
    @JsonProperty("connectionId")
    private String connectionId;
    public String getConnectionId()
    {
        return connectionId;
    }
    public void setConnectionId(String connectionId)
    {
        this.connectionId = connectionId;
    }
}
```
when I test it in Junit, it works ok. but when i deploy it in linix env, i got an error
```
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: com.*.common.model.ConnLink
Serialization trace:
list (com.*.common.model.wrapper.ConnLinkListWrapper)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709
        ... 40 more
Caused by: java.lang.ClassNotFoundException: com.*.common.model.ConnLink
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
        ... 58 more
```
who can help me , i'm crazy.
env info:   kryo 4.0.1
THX

**Comment by isaki-x** [comment]
`Caused by: java.lang.ClassNotFoundException: com.huawei.cloudsop.cloudvpnappraisalmgrservice.common.model.ConnLink`

Are you sure this class (or the jar that contains it) is on your class path?

**Comment by xuxingyude** [comment]
@isaki-x sure, this class is my project code, the class can work normally until kryo deSerilise it.

**Comment by isaki-x** [comment]
Can you try something for me? I've replaced your (write|read)Object calls with (write|read)ClassAndObject calls.

```java
    public static byte[] serialize(final Kryo kryo, final Object obj)
    {
        if (obj == null)
        {
            throw new IllegalArgumentException("serialize Object is null");
        }

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Output output = new Output(outputStream);
        kryo.writeClassAndObject(output, obj);
        output.close();
        return CompressUtil.snappyCompress(outputStream.toByteArray());
    }

    public static <T> T deSerialize(final Kryo kryo, final byte[] bytes, final Class<T> clazz)
    {
        if (bytes == null || bytes.length == 0)
        {
            throw new IllegalArgumentException("deSerialize Class<T>  bytes is null or empty");
        }

        final byte[] uncompressed = CompressUtil.snappyUncompress(bytes);
        return kryo.readClassAndObject(new Input(uncompressed), clazz);
    }
```

If that doesn't work, I'll try to setup what you have in a test project and actually debug it, though I might not be able to get to it for a few days.

**Comment by xuxingyude** [comment]
@isaki-x actually i did it and this problem doesnt solve. in my computer i use Junit it works well, but when i pack  and deploy it in tomcat, the wrong is happen. if i just deserilize ConnLink in tomcat env. it is ok, but if i deserilize like List<ConnLink>, the exception is happen. i test more, i find some interesting phenomenon, if i deserilize model in jar, no matter it someClass or List<someClass>, it works well. but if the class in file, i just deserilize the class, and the excption will happen in deserilize   List<someClass>.

**Comment by isaki-x** [comment]
I'm wondering if there isn't an issue somewhere in your compression code. I just setup a standalone application using slightly modified versions of your code.

Here is the main class for sandbox:

```Java
public abstract class JSandboxApplication {

    public static void main(final String[] args) throws Exception {
        final Kryo557Application x = new Kryo557Application();
        x.run(args);
    }

    protected JSandboxApplication() {
        super();
    }

    protected abstract void run(final String[] args) throws Exception;
}
```

Here is my test app for your code:

```Java
package io.isaki.jsandbox;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;

import io.isaki.jsandbox.kryo557.CompressUtil;
import io.isaki.jsandbox.kryo557.ConnLink;
import io.isaki.jsandbox.kryo557.ConnLinkListWrapper;

public final class Kryo557Application extends JSandboxApplication {

    @Override
    protected void run(final String[] args) throws Exception {
        final String[] data = new String[] {
            "this is a string",
            "this is also a string",
            "yet some other string",
            "i'm a little teacup",
            "short and stout",
            "here is my handle",
            "here is my spout"
        };
        
        final List<ConnLink> clinks = Arrays.stream(data)
            .map(ConnLink::new)
            .collect(Collectors.toCollection(ArrayList::new));
        final ConnLinkListWrapper wrapper = new ConnLinkListWrapper(clinks);
        
        final Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);
        kryo.getFieldSerializerConfig().setUseAsm(true);
        
        final byte[] payload = serialize(kryo, wrapper);
        final ConnLinkListWrapper copy = deSerialize(kryo, payload);
        
        final List<ConnLink> copyList = copy.getList();
        
        System.out.println(copyList.toString());

        final List<String> idList = copyList.stream()
            .map((x) -> x.toString())
            .collect(Collectors.toCollection(ArrayList::new));
        
        final String[] copyArray = idList.toArray(new String[0]);
        
        if (!Arrays.equals(copyArray, data)) {
            throw new IOException("Serialization data corruption");
        }
        
        System.out.println("Everything checks out; have a nice day!");
    }

    public static byte[] serialize(final Kryo kryo, final Object obj)
    {
        if (obj == null)
        {
            throw new IllegalArgumentException("serialize Object is null");
        }

        final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        final Output output = new Output(outputStream);
        kryo.writeClassAndObject(output, obj);
        output.close();
        return CompressUtil.snappyCompress(outputStream.toByteArray());
    }

    public static <T> T deSerialize(final Kryo kryo, final byte[] bytes)
    {
        if (bytes == null || bytes.length == 0)
        {
            throw new IllegalArgumentException("deSerialize Class<T>  bytes is null or empty");
        }

        final byte[] uncompressed = CompressUtil.snappyUncompress(bytes);
        @SuppressWarnings("unchecked") 
        final T ret = (T) kryo.readClassAndObject(new Input(uncompressed));
        return ret;
    }
}
```

Finally, here is your code, but modified a bit so I could be lazy in implementing the test:

```Java
package io.isaki.jsandbox.kryo557;

import java.util.List;

public class ListWrapper<T> {

    private List<T> list;
    
    public ListWrapper() {
        this(null);
    }
    
    public ListWrapper(final List<T> list) {
        super();
        this.list = list;
    }

    public List<T> getList() {
        return list;
    }

    public void setList(final List<T> list) {
        this.list = list;
    }   
}
```

```Java
package io.isaki.jsandbox.kryo557;

import java.util.List;

public class ConnLinkListWrapper extends ListWrapper<ConnLink> {

    public ConnLinkListWrapper() {
        super();
    }
    
    public ConnLinkListWrapper(final List<ConnLink> list) {
        super(list);
    }
}
```

```Java
package io.isaki.jsandbox.kryo557;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ConnLink {

    @JsonProperty("connectionId")
    private String connectionId;
    
    public ConnLink() {
        this(null);
    }
    
    public ConnLink(final String connectionId) {
        super();
        this.connectionId = connectionId;
    }
    
    public String getConnectionId() {
        return this.connectionId;
    }
    
    public void setConnectionId(final String connectionId) {
        this.connectionId = connectionId;
    }
    
    @Override
    public String toString() {
        return this.connectionId;
    }
}
```

And because I wanted to mess with the bytes a bit I wrote a fake compression class that just reversed the bytes:

```Java
package io.isaki.jsandbox.kryo557;

/**
 * Dummy class that just messes with the byte order
 * 
 * @author isaki
 */
public final class CompressUtil {

    private CompressUtil() {
        // STATIC
    }
    
    public static byte[] snappyCompress(final byte[] data) {
        return reverse(data);
    }
    
    public static byte[] snappyUncompress(final byte[] data) {
        return reverse(data);
    }
    
    private static byte[] reverse(final byte[] in) {
        final byte[] ret = new byte[in.length];
        
        for (int i = 0, j = in.length; i < in.length; ++i) {
            ret[--j] = in[i];
        }
        
        return ret;
    }
}
```

When I run this I get:

```
[this is a string, this is also a string, yet some other string, i'm a little teacup, short and stout, here is my handle, here is my spout]
Everything checks out; have a nice day!
```

**Comment by NathanSweet** [comment]
Please use the mailing list for questions. This is an issue tracker.
