### ISSUE TITLE
NPE problem

### ISSUE THREAD

**Issue by lvdelu** [EsotericSoftware/kryo#559]
![image](https://user-images.githubusercontent.com/16470271/34102126-f19f694c-e422-11e7-816c-0334148b501f.png)

the problem is below,and how to fix it

Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
metricClazz (com.bi.storm.stat.PersistCounter)
at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:626) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:109) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:18) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:629) ~[kryo-2.21.jar:na]
at backtype.storm.serialization.KryoValuesDeserializer.deserializeFrom(KryoValuesDeserializer.java:38) ~[jstorm-core-2.1.1.jar:na]
at backtype.storm.serialization.KryoTupleDeserializer.deserialize(KryoTupleDeserializer.java:85) ~[jstorm-core-2.1.1.jar:na]
... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:223) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:212) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:706) ~[kryo-2.21.jar:na]
at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:611) ~[kryo-2.21.jar:na]
... 18 common frames omitted

**Comment by magro** [comment]
@lvdelu Can you provide a reproducer, following the ideas of http://www.sscce.org/?

**Comment by NathanSweet** [comment]
Can reopen when reproducible.
