### ISSUE TITLE
Input with specific byte value cause Java OOM problem

### ISSUE THREAD

**Issue by eMorphling** [EsotericSoftware/kryo#566]
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:482)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:195)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:184)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:759)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)`

Here is the OOM problem, with specific byte value in signed value `-61`,
Which will cause readUtf8Length method return a big size for allocation which cause OOM.
Is there any problem for this fucntion?

Here is the link https://github.com/EsotericSoftware/kryo/blob/77935c696ee4976963aa5c6ac53d53d9b40b8bdd/src/com/esotericsoftware/kryo/io/Input.java#L487
You can think about the `b` is -61.
And after the function the result is `2086550275`, I think whether `readByteUnsigned` should be used in this function?

**Comment by magro** [comment]
@eMorphling did you close this because of new insights?

**Comment by ivan-murray** [comment]
@eMorphling - What was the resolution here, seeing the same issue

**Comment by dipankar08** [comment]
same here
