### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by opllkd** [EsotericSoftware/kryo#571]
i dont know this problem is by my code or kryo.
this code reproduce it at loop=20. loop=10 is okay.

java.lang.IndexOutOfBoundsException: Index: 18, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:707)
	at junk.XodusExample.test2(XodusExample.java:70)

	@Test
	public void test2() {
		Kryo kryo = new Kryo();
		Output output = new Output(new ByteArrayOutputStream());
		ConcurrentHashMap o = new ConcurrentHashMap();
		byte[] val = new byte[333];
		Random rnd = new Random();
		int loop = 20;
		for (int i = 0; i < loop; i++) {
			rnd.nextBytes(val);
			o.put(i, val.clone());
		}
		kryo.writeObject(output, o);
		byte[] b = output.toBytes();
		output.close();

		Input input = new Input(new ByteArrayInputStream(b));
		ConcurrentHashMap someObject = kryo.readObject(input,
				ConcurrentHashMap.class);
		input.close();

		System.out.println(someObject);
	}

**Comment by isaki-x** [comment]
I can reproduce, with a bit more of a targeted test to help narrow down the issue.

```Java
    @Test
    public void test2() {
        final Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);
        
        final Kryo kryo2 = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);

        kryo.getFieldSerializerConfig().setUseAsm(true);
        kryo2.getFieldSerializerConfig().setUseAsm(true);
        
        Output output = new Output(new ByteArrayOutputStream());
        HashMap<Integer, byte[]> o = new HashMap<>();
        byte[] val = new byte[333];
        Random rnd = new Random();
        int loop = 20;
        for (int i = 0; i < loop; i++) {
            rnd.nextBytes(val);
            o.put(i, val.clone());
        }
        kryo.writeObject(output, o);
        byte[] b = output.toBytes();
        output.close();

        Input input = new Input(new ByteArrayInputStream(b));
        HashMap<?, ?> someObject = kryo2.readObject(input,
                HashMap.class);
        input.close();

        System.out.println(someObject);
    }
```

This is the line throwing the exception in my version:

```Java
HashMap<?, ?> someObject = kryo2.readObject(input,
                HashMap.class);
```

Interesting.

**Comment by isaki-x** [comment]
I noticed Output wasn't being flushed; doing so really breaks things (buffer underflow), so I changed the test to use flush and pull the byte array from the backing stream. Still have the issue.

```Java
    @Test
    public void test2() throws IOException {
        final Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);

        final Kryo kryo2 = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);

        kryo.getFieldSerializerConfig().setUseAsm(true);
        kryo2.getFieldSerializerConfig().setUseAsm(true);

        final Random rnd = new Random();

        final byte[] b;
        try (final ByteArrayOutputStream bs = new ByteArrayOutputStream();
            final Output output = new Output(bs)) {
            final HashMap<Integer, byte[]> o = new HashMap<>();
            final byte[] val = new byte[333];

            for (int i = 0; i < 20; i++) {
                rnd.nextBytes(val);
                o.put(i, val.clone());
            }
            kryo.writeClassAndObject(output, o);
            output.flush();
            b = bs.toByteArray();
        }

        final Map<?, ?> someObject;
        try (final ByteArrayInputStream bis = new ByteArrayInputStream(b);
            final Input input = new Input(bis)) {
            someObject = (HashMap<?, ?>) kryo2.readClassAndObject(input);
        }

        System.out.println(someObject);
    }
```

**Comment by isaki-x** [comment]
Alright, one last experiment. I decorated the byte array with a wrapper object that safely allocated a new array for each item to be stored.

```Java
    @Test
    public void test2() throws IOException {
        final Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);

        final Kryo kryo2 = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);

        kryo.getFieldSerializerConfig().setUseAsm(true);
        kryo2.getFieldSerializerConfig().setUseAsm(true);

        final Random rnd = new Random();

        final byte[] b;
        final byte[] val = new byte[333];
        try (final ByteArrayOutputStream bs = new ByteArrayOutputStream();
            final Output output = new Output(bs)) {
            final Map<Integer, ByteArray> o = new HashMap<>();

            for (int i = 0; i < 20; i++) {
                rnd.nextBytes(val);
                final ByteArray wrapped = new ByteArray(val);
                o.put(i, wrapped);
            }
            kryo.writeClassAndObject(output, o);
            output.flush();
            b = bs.toByteArray();
        }

        final Map<?, ?> someObject;
        try (final ByteArrayInputStream bis = new ByteArrayInputStream(b);
            final Input input = new Input(bis)) {
            someObject = (HashMap<?, ?>) kryo2.readClassAndObject(input);
        }

        System.out.println(someObject);
    }
    
    static final class ByteArray {
        private final byte[] x;
        
        ByteArray(final byte[] x) {
            super();
            final byte[] tmp = new byte[x.length];
            System.arraycopy(x, 0, tmp, 0, x.length);
            this.x = tmp;
        }
        
        public byte[] get() {
            return this.x;
        }
    }
```

Still:

```
java.lang.IndexOutOfBoundsException: Index: 18, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:811)
	at io.isaki.jsandbox.KryoTest.test2(KryoTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by isaki-x** [comment]
I set up a bunch of tests to really understand the problem (if you want to see my tests with different kryo set ups, I can share). I narrowed it down to a buffer issue. I've changed your code to do the right thing below:

```Java
    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Test
    public void testOriginal() {
        Kryo kryo = new Kryo();
        
        ByteArrayOutputStream base = new ByteArrayOutputStream();
        Output output = new Output(base);
        ConcurrentHashMap o = new ConcurrentHashMap();
        byte[] val = new byte[333];
        Random rnd = new Random();
        int loop = 20;
        for (int i = 0; i < loop; i++) {
            rnd.nextBytes(val);
            o.put(i, Arrays.copyOf(val, val.length));
        }
        kryo.writeObject(output, o);
        output.flush();
        byte[] b = base.toByteArray();
        output.close();

        Input input = new Input(new ByteArrayInputStream(b));
        ConcurrentHashMap someObject = kryo.readObject(input,
                ConcurrentHashMap.class);
        input.close();

        System.out.println(someObject);
    }
```

The same thing, but using try-with-resource and fixing the missing generics:

```Java
    @Test
    public void testOriginal() throws IOException {
        final Kryo kryo = new Kryo();
        
        final byte[] b;
        try (final ByteArrayOutputStream base = new ByteArrayOutputStream();
            final Output output = new Output(base)) {
            final Map<Integer, byte[]> o = new ConcurrentHashMap<>();
            final byte[] val = new byte[333];
            final Random rnd = new Random();
            final int loop = 20;
            for (int i = 0; i < loop; i++) {
                rnd.nextBytes(val);
                o.put(i, Arrays.copyOf(val, val.length));
            }
            kryo.writeObject(output, o);
            output.flush();
            b = base.toByteArray();
        }

        final Map<?, ?> someObject;
        try (final Input input = new Input(new ByteArrayInputStream(b))) {
            someObject = kryo.readObject(input, ConcurrentHashMap.class);
        }

        System.out.println(someObject);
    }
```

**Comment by opllkd** [comment]
I fixed it by flush() and direct access to ByteArrayOutputStream. thanks.

**Comment by isaki-x** [comment]
Please close the issue at your earliest convenience. Thanks!
