### ISSUE TITLE
en/decode List,java.lang.NullPointerException

### ISSUE THREAD

**Issue by cutieagain** [EsotericSoftware/kryo#572]
I use this code to en/decode List,but it not working.
` public class KryoCodec extends AbstractMessageCodec {
    private static volatile KryoCodec kryoCodec;

    public static final KryoCodec getInstance() {
        if (kryoCodec == null) {
            synchronized (KryoCodec.class) {
                if (kryoCodec == null) {
                    kryoCodec = new KryoCodec();
                    kryoCodec.pool = new KryoPool.Builder(new KryoFactory() {
                        public Kryo create() {
                            Kryo kryo = new Kryo();
                            kryo.setReferences(false);
                            kryo.register(NettyMessage.class);
                            kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
                            return kryo;
                        }
                    }).build();
                }
            }
        }
        return kryoCodec;
    }

    private KryoPool pool;

    @Override
    public void encode(final OutputStream output,final Object object) {
        pool.run(new KryoCallback() {
            public Object execute(Kryo kryo) {
                Output out = new Output(output);
                kryo.writeClassAndObject(out, object);
                out.close();
                return null;
            }
        });
    }

    @Override
    public Object decode(byte[] body) throws IOException {
        ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(body);
        final Input in = new Input(byteArrayInputStream);
        return pool.run(new KryoCallback() {
            public Object execute(Kryo kryo) {
                Object result = kryo.readClassAndObject(in);
                in.close();
                return result;
            }
        });
    }
}  `

Here is the error
> Serialization trace:
result (com.dnkx.cashier.netty.models.response.RpcResponse)
body (com.dnkx.cashier.netty.models.NettyMessage)
io.netty.handler.codec.DecoderException: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
result (com.dnkx.cashier.netty.models.response.RpcResponse)
body (com.dnkx.cashier.netty.models.NettyMessage)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:418) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
result (com.dnkx.cashier.netty.models.response.RpcResponse)
body (com.dnkx.cashier.netty.models.NettyMessage)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:734) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:816) ~[kryo-4.0.1.jar:na]
	at com.dnkx.cashier.netty.codec.kryo.KryoCodec$3.execute(KryoCodec.java:64) ~[douni-cashier-netty-1.1.14-SNAPSHOT.jar:na]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:58) ~[kryo-4.0.1.jar:na]
	at com.dnkx.cashier.netty.codec.kryo.KryoCodec.decode(KryoCodec.java:62) ~[douni-cashier-netty-1.1.14-SNAPSHOT.jar:na]
	at com.dnkx.cashier.netty.codec.kryo.KryoDecoder.decode(KryoDecoder.java:13) ~[douni-cashier-netty-1.1.14-SNAPSHOT.jar:na]
	at com.dnkx.cashier.netty.codec.MessageDecoder.decode(MessageDecoder.java:43) ~[douni-cashier-netty-1.1.14-SNAPSHOT.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	... 12 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:234) ~[na:1.8.0_92]
	at java.util.ArrayList.ensureCapacity(ArrayList.java:218) ~[na:1.8.0_92]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:114) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:734) ~[kryo-4.0.1.jar:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-4.0.1.jar:na]
	... 23 common frames omitted

**Comment by cutieagain** [comment]
i can use the code to en/decode java object without List.

**Comment by cutieagain** [comment]
solved.. use kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
and use kryo-shaded instead of kryo is ok
