### ISSUE TITLE
Program type already present: com.esotericsoftware.reflectasm.AccessClassLoader

### ISSUE THREAD

**Issue by w1570187062** [EsotericSoftware/kryo#579]
When i used on android studio 3.1 occured this issue:
Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: com.esotericsoftware.reflectasm.AccessClassLoader
	at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
	at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
	at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:121)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:122)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:36)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:95)
	at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)
	... 52 more

**Comment by magro** [comment]
Sounds like you have multiple dependencies on reflectasm.

**Comment by magro** [comment]
Btw, google returns many results for "Program type already present", maybe some of it helps.

**Comment by w1570187062** [comment]
this problem can be solved by use:
`    api('kryonet:kryonet:2.21') {
        exclude module: 'reflectasm'
        exclude group: 'com.esotericsoftware.reflectasm'
    }`
