### ISSUE TITLE
java.lang.ClassValue can not be serialized

### ISSUE THREAD

**Issue by levyfan** [EsotericSoftware/kryo#608]
```
@Test
public void testClassValueSerializer() {
	kryo.setRegistrationRequired(false);

	ClassValue<Boolean> cv = new ClassValue<Boolean>() {
		@Override
		protected Boolean computeValue(Class type) {
			return true;
		}
	};

	roundTrip(Integer.MIN_VALUE, cv);
}
```

```
com.esotericsoftware.kryo.KryoException: 
java.lang.ArrayIndexOutOfBoundsException: 0
Serialization trace:
classValue (java.lang.ClassValue$Version)
version (com.esotericsoftware.kryo.serializers.DefaultSerializersTest$2)
        at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
        at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
        at com.esotericsoftware.kryo.KryoTestCase.roundTripWithBufferFactory(KryoTestCase.java:179)
        at com.esotericsoftware.kryo.KryoTestCase.roundTrip(KryoTestCase.java:77)
        at com.esotericsoftware.kryo.serializers.DefaultSerializersTest.testClassValueSerializer(DefaultSerializersTest.java:416)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:134)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:135)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:102)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
        at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
        ... 33 more
```

**Comment by levyfan** [comment]
ClassValue is used here 

https://github.com/google/guava/blob/v25.1/guava/src/com/google/common/util/concurrent/FuturesGetChecked.java#L127

https://github.com/apache/lucene-solr/blob/releases/lucene-solr/7.4.0/lucene/core/src/java/org/apache/lucene/util/AttributeFactory.java#L63

**Comment by NathanSweet** [comment]
ClassValue is too complex internally to easily see why it fails the way it does when references are not enabled, but that was the main problem with your test. You also need StdInstantiatorStrategy to use an anonymous class and to create the objects inside ClassValue. StdInstantiatorStrategy is [not recommended](https://github.com/EsotericSoftware/kryo/#instantiatorstrategy). Instead consider writing a serializer that gets the keys and values from ClassValue and serializes those, if that is possible. Pointing Kryo/FieldSerializer at a class when you do not know the implementation is not a good idea.

**Comment by NathanSweet** [comment]
Had to remove the tests added above as it failed on OpenJDK 7 because it isn't safe to make assumptions about the private implementation.

**Comment by levyfan** [comment]
It is better to provide and register a default ClassValueSerializer in Kryo. My code
```
class MyClass {
  private org.apache.lucene.util.AttributeFactory factory;
  ...
}
```
would fail in serializing.

**Comment by NathanSweet** [comment]
It doesn't look like ClassValue exposes enough to write a serializer. Eg, it doesn't allow access to the keys.
