### ISSUE TITLE
Generics Serializer bug

### ISSUE THREAD

**Issue by a62611323** [EsotericSoftware/kryo#610]
We found a sequential bug when using kryo 5.0.0-RC2 and a test case could be found as follows.
    Class D<K> fileID TestA<K>  
    Class E extends D<TestC>
    Class TestB extends TestA<TestC>

    write E
Serialization trace:
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:134)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:163)
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.write(CompatibleFieldSerializer.java:61)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:82)
	... 28 more

	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:108)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy0.getPermissions(proxy0.java)
	
	
Through stack tracking and debugging, we found the issue occured since that the result returned by Generics#nextGenericTypes is Array[1] dismatched with Array[0] returned by this.genericsHierarchy.counts.

**Comment by NathanSweet** [comment]
Can you please show executable code that shows the problem? Will reopen then.

**Comment by flisky** [comment]
It also occurs to me. The same traceback on `5.0.0-RC4`:

```
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:137)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:135)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:114)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:799)
        at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:235)
        at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:42)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:799)
```

`this.kryo.getGenerics().nextGenericTypes()` returns a type, however, `this.genericsHierarchy#counts` is empty.

I have no clue howto reproduce this bug. @NathanSweet, could you gives me some hints?

**Comment by theigl** [comment]
This is most likely the same as issue #654 to which I attached a test case.
