### ISSUE TITLE
Nested structures using generics easily exceed hardcoded `Generics` limit of 16, even when well under max depth.

### ISSUE THREAD

**Issue by joshhansen** [EsotericSoftware/kryo#618]
Kryo 5.0.0-RC1 and the current 5.0.0-RC2-SNAPSHOT seem to have a regression versus 4.0.2 when serializing deep object graphs involving generics. I'm trying to serialize a trie (prefix tree) data structure. This is a recursive structure that in my case gets down to depths as deep as the longest word in the English language, meaning well over 16 ("[supercalifragilisticexpialidocious](https://en.wikipedia.org/wiki/Supercalifragilisticexpialidocious#Word_meaning_and_origin)" and all that).

It seems that as part of the Kryo serialization the size 16 array at `Generics.depths` is being maxed out. This surprised me as the maximum recursion depth is supposedly Integer.MAX_VALUE by default (according to `Kryo.setMaxDepth`'s docs), but I seem to be hitting a limit at depth 17.

The serialization code:
```
Kryo kryo = new Kryo();
kryo.register(ApproximatePrefixMap.class);
kryo.register(TreeMap.class);
kryo.register(LinkedList.class);

final ApproximatePrefixMap<String> pronunciationToWord = loadPronunciationToWord();

try(OutputStream out = new FileOutputStream(OUTPUT_DIR + "/cmu+infochimps_kryo.gz")) {
	Output output = new Output(out);
	kryo.writeObject(output,
			pronunciationToWord
	);
	output.close();
}
```

The fields of ApproximatePrefixMap:

```
public class ApproximatePrefixMap<T> {
	final SortedMap<Character,ApproximatePrefixMap<T>> children = new TreeMap<>();
	List<T> values = null;
}
```

The error:
```
Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 16
Serialization trace:
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
children (com.example.ApproximatePrefixMap)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:543)
	at com.example.MergePronouncingDictionaries.main(MergePronouncingDictionaries.java:97)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
	at com.esotericsoftware.kryo.util.Generics.pushGenericType(Generics.java:65)
	at com.esotericsoftware.kryo.util.Generics.nextGenericTypes(Generics.java:93)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:133)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	... 93 more
```

If I recurse down the structure just a few steps and serialize that instead of the whole thing, then everything is okay. That makes it seem it really is the depth of the structure that's at issue.

This works in 4.0.2.

**Comment by NathanSweet** [comment]
It's not hardcoded, it's just a default size. It's intended to grow. Can you post an executable example so I can see the crash?

**Comment by joshhansen** [comment]
Here you go:
```
package jhn.test;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;

public class KryoBug {
	
	static class Node<T> {
		Node<T> child;
	}
	
	public static void main(String[] args) throws FileNotFoundException, IOException {
		
		Node<String> cur = new Node<>();
		final Node<String> start = cur;
		
		for(int i = 0; i < 17; i++) {
			cur.child = new Node<>();
			cur = cur.child;
		}
		
		Kryo kryo = new Kryo();
		kryo.register(Node.class);
		
		try(Output out = new Output(new FileOutputStream("/tmp/out.kryo"))) {
			kryo.writeObject(out, start);
		}
	}
}
```

**Comment by NathanSweet** [comment]
Cheers!
