### ISSUE TITLE
KryoException: Unable to resolve type variable: C

### ISSUE THREAD

**Issue by sdecoppet** [EsotericSoftware/kryo#622]
Hi,

I just updated the version from 4.0.2 to 5.0.0-RC1 and got the following exception while copying an object having a Guava Range (com.google.common.collect.Range) as instance variable:

KryoException: Unable to resolve type variable: C

Serialization trace:
myVar (com.test.MyTestClass)
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveTypeVariable(GenericsUtil.java:114)
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveType(GenericsUtil.java:41)
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:263)
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:228)
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:242)
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:228)
	at com.esotericsoftware.kryo.serializers.CachedFields.addField(CachedFields.java:139)
	at com.esotericsoftware.kryo.serializers.CachedFields.rebuild(CachedFields.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:82)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:124)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:108)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:392)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:377)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:85)
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:497)
	at com.esotericsoftware.kryo.Kryo.getSerializer(Kryo.java:517)
	at com.esotericsoftware.kryo.Kryo.copy(Kryo.java:895)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.copy(CollectionSerializer.java:255)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.copy(CollectionSerializer.java:43)
	at com.esotericsoftware.kryo.Kryo.copy(Kryo.java:895)
	at com.esotericsoftware.kryo.serializers.MapSerializer.copy(MapSerializer.java:244)
	at com.esotericsoftware.kryo.serializers.MapSerializer.copy(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.copy(Kryo.java:895)
	at com.esotericsoftware.kryo.serializers.UnsafeField.copy(UnsafeField.java:50)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.copy(FieldSerializer.java:215)
	at com.esotericsoftware.kryo.Kryo.copy(Kryo.java:895)

Guava version: 26.0-jre

**Comment by lukasz-golebiewski** [comment]
Similar problem here without guava

**Comment by sdecoppet** [comment]
Here it is
[test.zip](https://github.com/EsotericSoftware/kryo/files/2500429/test.zip)

**Comment by ab91963931372** [comment]
The same problem occurred during Apache dubbo's DecodeableRpcResult serialization process.
```
com.esotericsoftware.kryo.KryoException: Unable to resolve type variable: T
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
contextClassLoader (java.lang.Thread)
threads (java.lang.ThreadGroup)
parent (java.lang.ThreadGroup)
mGroup (com.alibaba.dubbo.common.utils.NamedThreadFactory)
threadFactory (java.util.concurrent.ThreadPoolExecutor)
bossExecutor (org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory)
factory (org.jboss.netty.channel.socket.nio.NioClientSocketChannel)
channel (com.alibaba.dubbo.remoting.transport.netty.NettyChannel)
channel (com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult)
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveTypeVariable(GenericsUtil.java:114) ~[kryo-5.0.0-RC2.jar:na]
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveType(GenericsUtil.java:41) ~[kryo-5.0.0-RC2.jar:na]
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:295) ~[kryo-5.0.0-RC2.jar:na]
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:260) ~[kryo-5.0.0-RC2.jar:na]
```

Nothing special, just call the writeClassAndObject method to serialize DecodeableRpcResult

```
public static String serializeObject(Object object) {
        try (
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            Output output = new Output(bos)
        ) {
            defaultKryo.writeClassAndObject(output, object);
            output.flush();
            return bos.toString(CODE);
        } catch (IOException e) {
            LOGGER.error("Write object stream with kryo error", e);
            throw new TTMException("Write object stream with kryo error");
        }
    }
```

**Comment by NathanSweet** [comment]
@sdecoppet Sorry for the delay getting to this!

**Comment by sdecoppet** [comment]
No worries, thanks for your help
