### ISSUE TITLE
What is wrong here

### ISSUE THREAD

**Issue by adilhamid** [EsotericSoftware/kryo#634]
Instead of: com.myproject.starfish.ohgod.cache.TellerThings
Caused by: java.lang.ClassNotFoundException: com.myproject.starfish.o`god.cache.TellerThings 
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192] 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192] 
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_192] 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192] 
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_192] 
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_192] 
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136) ~[kryo-2.24.jar:?]

**Comment by adilhamid** [comment]
Last Issue: https://github.com/EsotericSoftware/kryo/issues/319

**Comment by NathanSweet** [comment]
I can't know what is wrong from a stacktrace, besides saying the `` ` `` should probably be an `h`. If you are using Kryo < 5, maybe you are modifying the buffer during deserialization from multiple threads. Otherwise, my guessing at your issue which you did not provide sufficient information about is futile. Read this:
https://github.com/libgdx/libgdx/wiki/More-Info
It's for a different project, but a similar thing applies here. Update this issue with sufficient information and it can be reopened.

**Comment by adilhamid** [comment]
Sure, sometimes we can't provide the whole trace log. Seems like we are using Kryo Kryo = 2.24.
