### ISSUE TITLE
SetFromMap cannot be deserialized , gives null pointer exception

### ISSUE THREAD

**Issue by jayachathu** [EsotericSoftware/kryo#646]
Exception in thread "main" javax.websocket.DecodeException: Could not decode object
at org.ziptie.bridge.events.serializers.KryoEventDecoder.decode(KryoEventDecoder.java:61)
at org.ziptie.bridge.events.serializers.EventDecoder.main(EventDecoder.java:53)
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
traits (dancer.net.discovery.DiscoveryRecord)
payload (org.ziptie.bridge.events.Event)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
at org.ziptie.bridge.events.serializers.KryoEventDecoder.decode(KryoEventDecoder.java:57)
... 1 more
Caused by: java.lang.NullPointerException
at java.util.Collections$SetFromMap.add(Collections.java:5461)
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
... 7 more

**Comment by NathanSweet** [comment]
Kryo does not support `Collections.newSetFromMap`, which uses a private implementation. You could write your own serializer, eg using reflection/unsafe, but it would only work with the specific JRE implementation you target. You must evaluate every concrete type you will serialize and ensure it can be serialized.
