### ISSUE TITLE
Cannot serialize a class with field of type Map<K, Set<String>> 

### ISSUE THREAD

**Issue by vivekmalhotragithub** [EsotericSoftware/kryo#648]
using 5.0.0-RC2 with hazelcast 3.11.1

have a class 
```
public class Foo {
 private final Map<Bar, Set<String>> keysByBar = new HashMap<>();
}

public class Bar {
    private String field1;
    private String field2;
}
```

when trying to serialize Foo instance i get an exception 

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:138)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:135)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:102)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:154)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	... 31 more
```

**Comment by NathanSweet** [comment]
Repro:
```
static public void main (String[] args) throws Exception {
	Foo foo = new Foo();
	Bar bar = new Bar();
	bar.field1 = "foo";
	bar.field2 = "bar";
	HashSet set = new HashSet();
	set.add("one");
	set.add("two");
	foo.keysByBar.put(bar, set);

	Output output = new Output(1024);
	Kryo kryo = new Kryo();
	kryo.register(Foo.class);
	kryo.register(Bar.class);
	kryo.register(HashMap.class);
	kryo.register(HashSet.class);
	kryo.writeClassAndObject(output, foo);
	Input input = new Input(output.getBuffer(), 0, output.position());
	Foo foo2 = (Foo)kryo.readClassAndObject(input);
	System.out.println(foo.keysByBar);
	System.out.println(foo2.keysByBar);
}
```
