### ISSUE TITLE
Unable to resolve type variable

### ISSUE THREAD

**Issue by theigl** [EsotericSoftware/kryo#655]
Using Kryo 5.0.0-RC3-SNAPSHOT, I get the following Stacktrace when running the test:

```
om.esotericsoftware.kryo.KryoException: Unable to resolve type variable: T

	at com.esotericsoftware.kryo.util.GenericsUtil.resolveTypeVariable(GenericsUtil.java:112)
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveType(GenericsUtil.java:41)
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:294)
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:259)
	at com.esotericsoftware.kryo.serializers.CachedFields.addField(CachedFields.java:139)
	at com.esotericsoftware.kryo.serializers.CachedFields.rebuild(CachedFields.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:82)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:124)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:108)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:395)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:380)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:87)
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:500)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:110)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:532)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
```

```
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import org.junit.jupiter.api.Test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

import static org.assertj.core.api.Assertions.assertThat;

public class SerializeTest {

	@Test
	void serializeClassList() {
		final Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(false);

		final Output output = new Output(1024);
		kryo.writeClassAndObject(output, new LoadableClassList(new ArrayList<>()));
		final byte[] result = output.toBytes();

		assertThat(result).isNotNull();
	}

	static class LoadableClassList extends Loadable<Class<?>[]> {

		private final List<Class<?>> groups;

		LoadableClassList(List<Class<?>> groups) {
			this.groups = groups;
		}

		@Override
		protected Class<?>[] load() {
			return groups.toArray(new Class<?>[]{});
		}
	}

	abstract static class Loadable<T> implements Supplier<T>, Serializable {

		private transient T t;

		@Override
		public T get() {
			if (t == null) {
				t = load();
			}
			return t;
		}

		protected abstract T load();
	}
}
```

Related to #622

**Comment by magro** [comment]
Should be fixed with RC6 - can we close this issue now?

**Comment by theigl** [comment]
@magro: I have to reopen this ticket. I discovered two more corner cases in my application and created an additional PR: #720
