### ISSUE TITLE
Unable to find class: com.sun.jna.Pointer

### ISSUE THREAD

**Issue by ericxsun** [EsotericSoftware/kryo#680]
I implemented a class with a [third-party lib Chimera4j](https://github.com/SocialIntelligence/Chimera4j) (a high-perf regex lib calling c/c++ functions with JNA, not implemented with Serializable) like the following 
```java

public class JHyperScan implements Serializable {
  private ChimeraDatabase db;  // third-party lib
  private Scanner scanner = new Scanner();  // third-party lib
  private LinkedList<ChimeraExpression> expressions = new LinkedList<>();  // third-party lib

  public void add(List<Pair<String, EnumSet<ChimeraExpressionFlag>>> exps, Boolean clear) {
    if (clear) { expressions.clear(); }
    for (Pair<String, EnumSet<ChimeraExpressionFlag>> exp: exps) {
      expressions.add(new ChimeraExpression(exp.getLeft(), exp.getRight()));
    }
  }

  public void build() throws HyperscanException {
    db = ChimeraDatabase.compile(expressions);
    scanner.allocScratch(db);
  }

  public List<Match> parse(String doc) throws HyperscanException {
    return scanner.scan(db, doc);
  }

  public void release() throws HyperscanException {
    expressions.clear();
    scanner.close();
    db.close();
  }

  private void writeObject(ObjectOutputStream oos) throws IOException {
    Kryo kryo = new Kryo();
    kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

    kryo.register(ChimeraDatabase.class);
    kryo.register(Scanner.class);
    kryo.register(expressions.getClass());

    Output output = new Output(oos);
    kryo.writeObject(output, db);
    kryo.writeObject(output, scanner);
    kryo.writeObject(output, expressions);
    output.close();
  }


  @SuppressWarnings("unchecked")
  private void readObject(ObjectInputStream ois) throws IOException, ClassNotFoundException {
    Kryo kryo = new Kryo();
    kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

    Input input = new Input(ois);
    db = kryo.readObject(input, ChimeraDatabase.class);
    scanner = kryo.readObject(input, Scanner.class);
    expressions = (LinkedList<ChimeraExpression>) kryo.readObject(input, expressions.getClass());
    input.close();
  }
}

```

However, I met the following exception.

```shell
com.esotericsoftware.kryo.KryoException: Unable to find class: com.sun.jna.Pointer
Serialization trace:
database (io.carpe.hyperscan.db.ChimeraDatabase)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:599)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:626)
	at com.zhihu.walle.utils.JHyperScan.readObject(JHyperScan.java:96)

......

Caused by: java.lang.ClassNotFoundException: com.sun.jna.Pointer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136)
```

Is there anyway to solve the problem(serialize the struct jna or other way to do so)? 

Thanks very much for any clues and help.

**Comment by theigl** [comment]
Does it help if you manually register `com.sun.jna.Pointer`?

Could you create a minimal test-case that doesn't require external dependencies?

**Comment by magro** [comment]
Closed for now, please reopen if still relevant.

**Comment by ericxsun** [comment]
To serialize ChimeraDB was really difficult. I finally figure out another way without serialize ChimeraDB but rebuild it:

- serialize: save the expressions used to build db(ChimeraDB) and scanner(Scanner)
- deserialize: read the expressions and rebuild db and scanner

see https://github.com/SocialIntelligence/Chimera4j/issues/1

Hope it'll be help for others.

**Comment by magro** [comment]
Cool, thanks for sharing!
