### ISSUE TITLE
KryoException: Unable to find class - className not correct

### ISSUE THREAD

**Issue by fericit-bostan** [EsotericSoftware/kryo#695]
I'm using Kryo 4.0.2 and some classes, when deserializing are raising and exception:

> java.lang.RuntimeException: com.esotericsoftware.kryo.KryoException: Unable to find class:

This appears to be caused by the className being corrupted for some reason. This is easily reproducible and I have attached a maven project that demonstrates the issue. The object is created and serialized to file without issue. Reading the file and deserializing causes the exception but the className within the file is corrupted at the time of writing. 

Our project is currently encountering this with multiple classes but I am unable to identify any common reason for this issue.

Stepping though the code it appear that the buffer, which contains only the name, is getting corrupted in the Output class at line 353:
`		if (ascii) {
			if (capacity - position < charCount)
				writeAscii_slow(value, charCount);
			else {
				value.getBytes(0, charCount, buffer, position);
				position += charCount;
			}
			buffer[position - 1] |= 0x80 // this is overwriting the last character of the className
`

Thanks for the assistance.
Chris

**Comment by fericit-bostan** [comment]
It seems that the issue was the way I was writing out the bytes to file that was causing the issue. I've made some modifications to the project and everything seems to be working correctly now in my test project.  But we are still seeing errors in our production environment pertaining to Kryo.  The class is in the class path so I know that this is not an issue, and we are not supplying a different class loader to Kryo so the class should be able to be located. The one items that seems odd to me are the characters at the end of the DistributedLockRows class name. 
[kryo-test.zip](https://github.com/EsotericSoftware/kryo/files/3654162/kryo-test.zip)


> vv.common.domain.exception.VVRuntimeException: com.esotericsoftware.kryo.KryoException: Unable to find class: vv.common.infrastructure.util.VVDistributedLockRows^A^Av
Serialization trace:
cachedObject (vv.common.infrastructure.util.cache.impl.ObjectCacheEntry)
        at vv.common.infrastructure.util.cache.impl.KryoSerializationService.deserialize(KryoSerializationService.java:102)
        at vv.common.infrastructure.util.cache.impl.CacheKryoTranscoder.lambda$0(CacheKryoTranscoder.java:25)
        at vv.common.infrastructure.util.cache.impl.CacheSerializingTranscoder.execute(CacheSerializingTranscoder.java:51)
        at vv.common.infrastructure.util.cache.impl.CacheKryoTranscoder.deserialize(CacheKryoTranscoder.java:22)
        at net.spy.memcached.transcoders.SerializingTranscoder.decode(SerializingTranscoder.java:88)
        at net.spy.memcached.transcoders.TranscodeService$1.call(TranscodeService.java:63)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.spy.memcached.transcoders.TranscodeService$Task.run(TranscodeService.java:110)
        at net.spy.memcached.transcoders.TranscodeService$Task.get(TranscodeService.java:96)
        at net.spy.memcached.internal.GetFuture.get(GetFuture.java:70)
        at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1229)
        at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1256)

**Comment by fericit-bostan** [comment]
This issue is persisting in our production environment. We are using Kryo for serializing our contract objects to memcached and our cache.log is constantly filling up with exceptions from kryo but I am unable to determine why. 

Exceptions stating: Invalid Ordinal for enum.

> vv.common.domain.exception.VVRuntimeException: com.esotericsoftware.kryo.KryoException: Invalid ordinal for enum "vv.common.filesystem.BucketInfo$BucketStatus": 117
Serialization trace:
bucketStatus (vv.common.filesystem.BucketInfo)
contentTypeToBucket (vv.common.filesystem.RemoteConfiguration)
instanceConfigurationObjects (vv.common.infrastructure.config.cache.InstanceConfigurationCacheItem)
cachedObject (vv.common.infrastructure.util.cache.impl.ObjectCacheEntry)
        at vv.common.infrastructure.util.cache.impl.KryoSerializationService.deserialize(KryoSerializationService.java:102)
        at vv.common.infrastructure.util.cache.impl.VVCacheKryoTranscoder.lambda$0(VVCacheKryoTranscoder.java:25)
        at vv.common.infrastructure.util.cache.impl.VVCacheSerializingTranscoder.execute(VVCacheSerializingTranscoder.java:51)
        at vv.common.infrastructure.util.cache.impl.VVCacheKryoTranscoder.deserialize(VVCacheKryoTranscoder.java:22)
        at net.spy.memcached.transcoders.SerializingTranscoder.decode(SerializingTranscoder.java:88)
        at net.spy.memcached.transcoders.TranscodeService$1.call(TranscodeService.java:63)


The class BucketInfo$BucketStatus enum is extremely simple and I don't understand why Kryo is reporting an invalid ordinal.

```
public class BucketInfo implements Cacheable{
    private static final long serialVersionUID = 5642159444686974197L;
    private BucketLocator bucketLocator;
    private BucketStatus bucketStatus;

    public enum BucketStatus{
        active,
        inactive
    }
}
```



In addition to those exceptions, the log file is filling up with exceptions stating: Encountered unregistered class ID:

> vv.common.domain.exception.VVRuntimeException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 68
Serialization trace:
cachedObject (vv.common.infrastructure.util.cache.impl.ObjectCacheEntry)
cachedObject (vv.common.infrastructure.util.cache.impl.ObjectCacheEntry)
fields (vv.mdlclient.infrastructure.contract.VcfComponentImmutable)
subComponents (vv.mdlclient.infrastructure.contract.VcfComponentImmutable)
vcfComponent (vv.vcfclient.cache.VcfComponentSingleCacheItem)
cachedObject (vv.common.infrastructure.util.cache.impl.ObjectCacheEntry)
        at vv.common.infrastructure.util.cache.impl.KryoSerializationService.deserialize(KryoSerializationService.java:102)
        at vv.common.infrastructure.util.cache.impl.VVCacheKryoTranscoder.lambda$0(VVCacheKryoTranscoder.java:25)
        at vv.common.infrastructure.util.cache.impl.VVCacheSerializingTranscoder.execute(VVCacheSerializingTranscoder.java:51)
        at vv.common.infrastructure.util.cache.impl.VVCacheKryoTranscoder.deserialize(VVCacheKryoTranscoder.java:22)
        at net.spy.memcached.transcoders.SerializingTranscoder.decode(SerializingTranscoder.java:88)
        at net.spy.memcached.transcoders.TranscodeService$1.call(TranscodeService.java:63)


I am also still seeing Exceptions stating "Unable to find class". This seems to be caused by unexpected characters being appended or getting corrupted in the class name:
> vv.common.domain.exception.VVRuntimeException: com.esotericsoftware.kryo.KryoException: Unable to find class: vv.common.infrastructure.util.VVDistributedLockRows^A^AV
Serialization trace:
cachedObject (vv.common.infrastructure.util.cache.impl.ObjectCacheEntry)
        at vv.common.infrastructure.util.cache.impl.KryoSerializationService.deserialize(KryoSerializationService.java:102)
        at vv.common.infrastructure.util.cache.impl.VVCacheKryoTranscoder.lambda$0(VVCacheKryoTranscoder.java:25)
        at vv.common.infrastructure.util.cache.impl.VVCacheSerializingTranscoder.execute(VVCacheSerializingTranscoder.java:51)
        at vv.common.infrastructure.util.cache.impl.VVCacheKryoTranscoder.deserialize(VVCacheKryoTranscoder.java:22)
        at net.spy.memcached.transcoders.SerializingTranscoder.decode(SerializingTranscoder.java:88)
        at net.spy.memcached.transcoders.TranscodeService$1.call(TranscodeService.java:63)


Our serialize and deserialize methods are listed below:
```
    public Object deserialize(byte[] in) {
        Object rv = null;
        Kryo kryo = null;
        try(Input input = new Input(in)) {
            kryo = borrow();
            rv = kryo.readClassAndObject(input);
        } catch(Exception e) {
            invalidate(kryo);
            kryo = null; // set kryo to null to prevent release from returning it to the pool
            throw new VVRuntimeException(e);
        } finally {
            release(kryo);
        }
        return rv;
   }     

   public byte[] serialize(Object o) {
        byte[] rv = null;
        Kryo kryo = null;
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (Output output = new Output(bos)) {
            kryo = borrow();
            kryo.writeClassAndObject(output, o);
            output.flush();
            rv = bos.toByteArray();
        } catch(Exception e) {
            invalidate(kryo);
            kryo = null; // set kryo to null to prevent release from returning it to the pool
            throw new VVRuntimeException(e);
        } finally {
            release(kryo);
        }
        return rv;
    }
```
 
The Kryo instance is retrieved from an ObjectPool, which we are using the apache commons-pool2 implementation. So there should never be a situation where an instance of Kryo is shared between threads.

These issues are constantly filling our log files daily. Disabling Kryo serialization and using Java Serialization instead solves the issue, which is disappointing as Kryo seems to be much more performant. I'm desperate to find a solution to these issues. Any help would be greatly appreciated.

**Comment by fericit-bostan** [comment]
Due to the lack of assistance that I received for this issue I have disabled Kryo in all of our environments. Since we are continuing to experience issues associated with Kryo serialization and support appears to be non-existent at this point, there is little point in pursuing the use of Kryo for any of our needs. We invested a significant amount of time and effort into its usage only to experience constant issues with our production environments causing us to disable Kryo release after release.

**Comment by krishna81m** [comment]
@fericit-bostan , can you share your Kryo configs to confirm you used a backward/forward compatible serializer/deserializer something like this one? 

We did notice something similar but that happened because serializer changed the configs _a tad bit_, as long as both were using exact same configs, we were fine.

```
    kryo.setReferences(false);
    kryo.setRegistrationRequired(false);
    CompatibleFieldSerializer.CompatibleFieldSerializerConfig config =
            new CompatibleFieldSerializer.CompatibleFieldSerializerConfig();
    config.setChunkedEncoding(true);
    config.setReadUnknownFieldData(true);
    kryo.setDefaultSerializer(new SerializerFactory.CompatibleFieldSerializerFactory(config));
```
