### ISSUE TITLE
Illegal reflective access with java.nio.DirectByteBuffer

### ISSUE THREAD

**Issue by esalsbury** [EsotericSoftware/kryo#698]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.unsafe.UnsafeUtil (file:/C:/Users/*****/.m2/repository/com/esotericsoftware/kryo/5.0.0-RC4/kryo-5.0.0-RC4.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.unsafe.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by zakgof** [comment]
I get this exception when trying to serialize DirectByteBuffer with kryo-5.0.0-RC4:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private jdk.internal.ref.Cleaner jdk.internal.ref.Cleaner.next accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @5b19ffd1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at com.esotericsoftware.kryo.serializers.CachedFields.addField(CachedFields.java:123)
	at com.esotericsoftware.kryo.serializers.CachedFields.rebuild(CachedFields.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:82)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:124)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:108)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:395)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:380)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:87)
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:500)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:110)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:532)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:67)
	... 9 more
```

**Comment by NathanSweet** [comment]
@esalsbury Kryo uses unsafe operations. This is normal.

@zakgof Serialize how? You can't just throw any class at FieldSerializer, you need to consider the internal structure of the class. Likely you need to write a serializer for DirectByteBuffer.
