### ISSUE TITLE
KryoException: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mrniko** [EsotericSoftware/kryo#704]
Unable to encode follow data structure:

```java
    public static class Test4 implements Test3<String, Integer, Integer> {

    }

    public interface Test3<K, V, R> extends Serializable {

    }

    public static class Test1 implements Serializable {

        private Test3<String, Integer, Integer> collator = new Test4();

    }

   Kryo kryo = new Kryo();
   kryo.setRegistrationRequired(false);
   Output output = new Output(8192, -1);

   kryo.writeClassAndObject(output, new Test1());
```

Getting follow exception:

```java
com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 0
Serialization trace:
collator (org.redisson.RedissonCodecTest$Test1)

	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at org.redisson.RedissonCodecTest.kryoCodec(RedissonCodecTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:137)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:135)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:102)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	... 28 more
```

Used JDK 1.8, Kryo 5.0.0-RC4

**Comment by theigl** [comment]
This is most likely a duplicate of #654

**Comment by theigl** [comment]
@mrniko: Could you please close this issue? I just verified that this is the same as #654 and will add a PR with a simplified testcase.

**Comment by theigl** [comment]
Should be fixed in RC6. Please verify.

**Comment by mrniko** [comment]
Unable to reproduce the issue with RC6. Thank you!
