### ISSUE TITLE
Kryo serialization goes to StackOverflowError using Lucene Query and wildcard '*'

### ISSUE THREAD

**Issue by psycojack** [EsotericSoftware/kryo#706]
When I try to serialialize Lucene 4.7.2 BooleanQuery using WildcardQuery '*' as sub-query, Kryo goes to StackOverflowError.
We encountered the issue in the version 5.0.0-RC4 , RC3 is affected as well.
The code works fine until version 5.0.0-RC2

Java Version: 1.8.0_172

How to reproduce.

The Kryo pool:

      private final Pool<Kryo> kryoPool = new Pool<Kryo>(true, false, 10) {
         protected Kryo create() {
			Kryo kryo = new Kryo();
			kryo.setRegistrationRequired(false);
			kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
			return kryo;
		}
	};

The Unit Test:

     import org.apache.lucene.index.Term;
     import org.apache.lucene.search.Query;
     import org.apache.lucene.search.BooleanClause;
     import org.apache.lucene.search.BooleanQuery;
     import org.apache.lucene.search.WildcardQuery
    
     @Test
     public void testKryo()  {
      Kryo kryo = kryoPool.obtain();
		try {

                    Term term = new Term("title","test*");
			Query subQuery = new WildcardQuery(term);
			BooleanQuery booleanQuery = new BooleanQuery();
			booleanQuery.add(subQuery, BooleanClause.Occur.MUST);
			ByteArrayOutputStream queryOutputStream = new ByteArrayOutputStream();
			Output output = new Output(queryOutputStream);
			kryo.writeObject(output, booleanQuery);
			output.close();
			byte[] response = queryOutputStream.toByteArray();
			assertTrue(response.length == 689);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			kryoPool.free(kryo);
		}
	}

The stacktrace:

	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
Caused by: java.lang.StackOverflowError
	at java.lang.Class.getName0(Native Method)
	at java.lang.Class.getName(Class.java:642)
	at java.lang.Throwable.toString(Throwable.java:479)
	at java.lang.Throwable.<init>(Throwable.java:311)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at com.esotericsoftware.kryo.KryoException.<init>(KryoException.java:40)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:561)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:66)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:334)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:299)

**Comment by fcarsten** [comment]
I'm seeing similar behavior with a non-Lucene example. Seems something was broken after RC2. My example is hard to bundle up so I won't add it here (unless explicitly requested). Just commenting to point out it's not a Lucene specific issue and it's affecting multiple users (at least 2).

**Comment by MarcMil** [comment]
You can try to increase the stack size of the JVM.
Also, you may want to enable kryo.setReferences(true) in case you have circular references in any form.

**Comment by theigl** [comment]
References have been disable by default since RC3. See #617. 

You have to enable them as MarcMil suggested.

**Comment by magro** [comment]
Closed for now, please reopen if this is still an issue.
