### ISSUE TITLE
Issue:  out of range Exception

### ISSUE THREAD

**Issue by bmistry13** [EsotericSoftware/kryo#716]
I am getting below exception when I start up Spring Boot and try to read from the cache.  Is this issue fixed or let me know how to fix it ?

```
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.StringIndexOutOfBoundsException: offset 0, count -1931017144, length 32
Serialization trace:
implClass (java.lang.invoke.SerializedLambda)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:165)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at com.esotericsoftware.kryo.serializers.ClosureSerializer.read(ClosureSerializer.java:75)
	... 140 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: offset 0, count -1931017144, length 32
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.rangeCheck(String.java:280)
	at java.base/java.lang.String.<init>(String.java:276)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:484)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:199)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:188)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:153)
	... 143 common frames omitted

```

**Comment by theigl** [comment]
@bmistry13: Can you try to reproduce this in a test-case?

**Comment by magro** [comment]
Closed for now, please reopen if this is still relevant.

**Comment by saurabhk687** [comment]
I am finding the same issue, but don't know if its reproduceable and if yes then how
