### ISSUE TITLE
nullpointer when serialize protobuf builder (kryo:5.0.0-RC7)

### ISSUE THREAD

**Issue by choxsword** [EsotericSoftware/kryo#749]
```
Caused by: java.lang.NullPointerException: null
        at com.google.protobuf.RepeatedFieldBuilderV3$MessageExternalList.size(RepeatedFieldBuilderV3.java:587)
        at java.util.AbstractList.add(AbstractList.java:108)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.copy(CollectionSerializer.java:264)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.copy(CollectionSerializer.java:43)
        at com.esotericsoftware.kryo.Kryo.copy(Kryo.java:910)
        at com.esotericsoftware.kryo.serializers.UnsafeField.copy(UnsafeField.java:54)
```

**Comment by theigl** [comment]
@choxsword: Kryo does its best to serialize/copy arbitrary classes, but there are always cases where the built-in serializers are not enough. Your best choice is to write your own custom serializer.

If you believe this is a bug in the collection serializer itself, please create a minimal test-case that demonstrates the issue. Ideally, without referencing protobuf.

**Comment by choxsword** [comment]
> @choxsword: Kryo does its best to serialize/copy arbitrary classes, but there are always cases where the built-in serializers are not enough. Your best choice is to write your own custom serializer.
> 
> If you believe this is a bug in the collection serializer itself, please create a minimal test-case that demonstrates the issue. Ideally, without referencing protobuf.

But protobuf is a common used tool, not that arbitrary. Maybe kryo should provide a more stable support for protobuf?

**Comment by theigl** [comment]
Kryo only supports JDK classes. 

Take a look at https://github.com/magro/kryo-serializers. There seems to be some support for protobuf there.

**Comment by magro** [comment]
A custom serializer could be added to kryo-serializers.
