### ISSUE TITLE
Can't deserialize class java.utils.Date

### ISSUE THREAD

**Issue by zza1998** [EsotericSoftware/kryo#783]
The version is very old 
`      <dependency>
			<groupId>com.esotericsoftware.kryo</groupId>
			<artifactId>kryo</artifactId>
			<version>2.24.0</version>
		</dependency>
`
`
		<dependency>
			<groupId>de.javakaffee</groupId>
			<artifactId>kryo-serializers</artifactId>
			<version>0.27</version>
		</dependency>
`

when deserialize  type of Date params, a error happen 

`com.esotericsoftware.kryo.KryoException: Unable to find class:   java.util.Date
Serialization trace:
createTime (com.xx.xx.api.user.dto.SelectUserInfoRes
at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764))`

but i have no idea how to solve it

**Comment by zza1998** [comment]
I guess it is because of serialization and deserialization problems that Date class can't be recognized

**Comment by Mr14huashao** [comment]
@zza1998  The version is outdated. Are test cases provided?

**Comment by zza1998** [comment]
Thanks, I had ignore this problem ,it only happened on local test ,our project should be update 👍
