### ISSUE TITLE
NullPointerException occured when read HashSet, in 4.0.2

### ISSUE THREAD

**Issue by fennuzhichui** [EsotericSoftware/kryo#791]
the Exception like this
Caused by: java.lang.NullPointerException
	at java.util.HashSet.add(HashSet.java:219)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125

when debug the code,i found the result of  kryo.newInstance(type) (CollectionSerializer#111 )is null，so why this happen? 
the HashSet doesn`t support kryo sede?

**Comment by fennuzhichui** [comment]
@puneetlakhina @timotta @matthoffman

**Comment by theigl** [comment]
@fennuzhichui: Please create a minimal test-case that reproduces the problem.

**Comment by theigl** [comment]
@fennuzhichui: Please provide a test-case or additional input. Otherwise, I'll close this ticket.
