### ISSUE TITLE
java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/Kryo

### ISSUE THREAD

**Issue by crystaldevelopment** [EsotericSoftware/kryo#797]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/Kryo
        at net.minemix.crystalcloud.Master.start(Master.java:39)
        at net.minemix.crystalcloud.Launcher.main(Launcher.java:25)
Caused by: java.lang.ClassNotFoundException: com.esotericsoftware.kryo.Kryo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more
```

**I dont know how i can fix that.**

Im using IntelliJ Idea Ultimate and `Kryo 5.0.0-RC3` and `KryoNet 2.22.0-RC1`

**Comment by theigl** [comment]
@crystaldevelopment: This is hard to diagnose without additional context. Are you using a Maven or Gradle build or do you simply have the libraries on the classpath? Can you provide a minimal project that reproduces the issue?

KryoNet was built for Kryo 2.x, so it might simply be incompatible with Kryo 5. Your error message looks more like build problem though.

**Comment by mikereiche** [comment]
I run into this error in Intellij - on this import statement.  

Class com.esotericsoftware.kryo.KryoSerializable not found - continuing with a stub.
import org.apache.spark.unsafe.types.UTF8String
