### ISSUE TITLE
Serializing reference to outer class: works in v4, broken in v5?

### ISSUE THREAD

**Issue by armanbilge** [EsotericSoftware/kryo#801]
I recently upgraded to Kryo v5 but am experiencing issues with object graphs that I was previously able to (de)serialize with v4. Specifically, in v5 the reference to an outer class does not get populated and causes null pointer exceptions.

I've provided a demo of this problem below. Is this a configuration problem I'm experiencing or something else? Thanks in advance for your help.

#### Kryo v4.0.2:
```java
package sandbox;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.Serializer;
import com.esotericsoftware.kryo.factories.SerializerFactory;
import com.esotericsoftware.kryo.serializers.FieldSerializer;
import org.objenesis.strategy.StdInstantiatorStrategy;

public class Sandbox {

    static abstract class Inner {
        public abstract void accessOuter();
    }

    static class Outer {

        private String message;

        public Outer(String message) {
            this.message = message;
        }

        public Inner newInner() {
            return new Inner() {
                public void accessOuter() {
                    System.out.println(message);
                }
            };
        }
    }

    public static void main(String[] args) {

        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
        kryo.setDefaultSerializer(new SerializerFactory() {
            public Serializer makeSerializer(Kryo kryo, Class<?> type) {
                FieldSerializer fs = new FieldSerializer(kryo, type);
                fs.setIgnoreSyntheticFields(false);
                return fs;
            }
        });

        Outer outer = new Outer("Hello world");
        Inner inner = outer.newInner();
        Inner copy = kryo.copy(inner);
        copy.accessOuter();
        // Prints "Hello world"
    }

}

```

#### Kryo v5.0.3
```java
package sandbox;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.Serializer;
import com.esotericsoftware.kryo.SerializerFactory;
import com.esotericsoftware.kryo.serializers.FieldSerializer;
import org.objenesis.strategy.StdInstantiatorStrategy;

public class Sandbox {

    static abstract class Inner {
        public abstract void accessOuter();
    }

    static class Outer {

        private String message;

        public Outer(String message) {
            this.message = message;
        }

        public Inner newInner() {
            return new Inner() {
                public void accessOuter() {
                    System.out.println(message);
                }
            };
        }
    }

    public static void main(String[] args) {

        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
        kryo.setDefaultSerializer(new SerializerFactory() {
            public Serializer newSerializer(Kryo kryo, Class type) {
                FieldSerializer fs = new FieldSerializer(kryo, type);
                fs.getFieldSerializerConfig().setIgnoreSyntheticFields(false);
                return fs;
            }
            public boolean isSupported(Class type) {
                return true;
            }
        });

        Outer outer = new Outer("Hello world");
        Inner inner = outer.newInner();
        Inner copy = kryo.copy(inner);
        copy.accessOuter();
        // Throws:
        // Exception in thread "main" java.lang.NullPointerException
        //	at sandbox.Sandbox$Outer$1.accessOuter(Sandbox.java:26)
        //	at sandbox.Sandbox.main(Sandbox.java:51)
    }

}
```

**Comment by armanbilge** [comment]
Aha, this was my fault for not reading the docs for `getFieldSerializerConfig()`:
> If the returned config settings are modified, `updateFields()` must be called.

**Comment by theigl** [comment]
@armanbilge:

You can also configure the serializer like this:

```java
FieldSerializerFactory factory = new FieldSerializerFactory();
factory.getConfig().setIgnoreSyntheticFields(false);
kryo.setDefaultSerializer(factory); 
```
