### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Unable to find class: hone

### ISSUE THREAD

**Issue by behruz-b** [EsotericSoftware/kryo#812]
While upgrading play2, akka to versions play2 - 2.7.7, akka - 2.6.12. Following exception happens:
```
com.esotericsoftware.kryo.KryoException: Unable to find class: hone
Serialization trace:
underlying (play.api.libs.json.JsObject)
value (scala.Some)
CASE_CLASS_FIELD1 (CASE_CLASS_FIELD1_PATH)
CASE_CLASS_FIELD2 (CASE_CLASS_FIELD2_PATH)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:190)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802)
	at io.altoo.akka.serialization.kryo.serializer.scala.ScalaMutableMapSerializer.read(ScalaMapSerializers.scala:46)
	at io.altoo.akka.serialization.kryo.serializer.scala.ScalaMutableMapSerializer.read(ScalaMapSerializers.scala:38)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:729)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:124)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:729)
Caused by: java.lang.ClassNotFoundException: hone
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:184)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802)
	at io.altoo.akka.serialization.kryo.serializer.scala.ScalaMutableMapSerializer.read(ScalaMapSerializers.scala:46)
```

Please help to solve,
Thanks

**Comment by theigl** [comment]
@behruz-b: I don't know enough about Play/Akka to help you with this issue. It might be better to report this to https://github.com/altoo-ag/akka-kryo-serialization

**Comment by behruz-b** [comment]
> It might be better to report this to https://github.com/altoo-ag/akka-kryo-serialization

Ok, thanks
