### ISSUE TITLE
DEBUG: [kryo] No direct ByteBuffer constructor is available.

### ISSUE THREAD

**Issue by t3link** [EsotericSoftware/kryo#843]
**Describe the bug**
```log
java.lang.reflect.InaccessibleObjectException: Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module @58ceff1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at com.esotericsoftware.kryo.unsafe.UnsafeUtil.<clinit>(UnsafeUtil.java:100)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at com.esotericsoftware.kryo.util.Util.<clinit>(Util.java:47)
	at com.esotericsoftware.kryo.serializers.OptionalSerializers.addDefaultSerializers(OptionalSerializers.java:38)
	at com.esotericsoftware.kryo.Kryo.<init>(Kryo.java:230)
	at com.esotericsoftware.kryo.Kryo.<init>(Kryo.java:168)
	at link.tothetracker.infra.restful.component.redis.KryoUtil.lambda$static$0(KryoUtil.java:25)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at link.tothetracker.infra.restful.component.redis.KryoUtil.serialize(KryoUtil.java:42)
```

**Environment:**
 - OS: Windows10
 - JDK Version: openjdk version "16" 2021-03-16
 - Kryo Version: 5.1.1

**Additional context**
```java
private static Constructor<? extends ByteBuffer> directByteBufferConstructor;
static {
	ByteBuffer buffer = ByteBuffer.allocateDirect(1);
	try {
		directByteBufferConstructor = buffer.getClass().getDeclaredConstructor(long.class, int.class);
		directByteBufferConstructor.setAccessible(true);
	} catch (Exception ex) {
		if (DEBUG) debug("kryo", "No direct ByteBuffer constructor is available.", ex);
		directByteBufferConstructor = null;
	}
}
```

**Comment by theigl** [comment]
@t3link: This is expected when running under JDK 16. See https://blogs.oracle.com/javamagazine/java-runtime-encapsulation-internals for why this is happening.

You can add the following JVM argument if you intend to use Kryo's `UnsafeByteBuffers`:

    --add-opens=java.base/java.nio=ALL-UNNAMED

Depending on what kind of serializers you are using, you will need a bunch of additional `add-opens`. This is the current configuration used for running Kryo tests under JDK 16: https://github.com/EsotericSoftware/kryo/blob/57d11f2dc9e25f4e7bdd0413eaddf4d729649710/pom.xml#L397-L408

**Comment by theigl** [comment]
We will revisit this topic as the release of JDK 17 gets closer and try to get rid of warnings for parts of the system that don't get used.
