### ISSUE TITLE
`java.lang.ArrayIndexOutOfBoundsException: 1`

### ISSUE THREAD

**Issue by catap** [EsotericSoftware/kryo#860]
**Describe the bug**

Kryo can't serialize fastutils' structures with error: `java.lang.ArrayIndexOutOfBoundsException: 1`. 

**To Reproduce**
```java
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;

import it.unimi.dsi.fastutil.ints.Int2ObjectArrayMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;

import java.io.ByteArrayOutputStream;

public class Bug {
    private static class Node {
        public Int2ObjectMap<Object> kids;
    }

    public static void main(String[] args) {
        Node node1 = new Node();
        Node node2 = new Node();

        node1.kids = new Int2ObjectArrayMap<>();
        node1.kids.put(1, node2);

        Kryo kryo = new Kryo();

        kryo.setRegistrationRequired(false);

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (Output output = new Output(bos)) {
            kryo.writeClassAndObject(output, node1);
        }
    }
}
```

fails as:
```
Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 1
Serialization trace:
kids (Bug$Node)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:101)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
	at Bug.main(Bug.java:27)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:140)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	... 3 more
```

**Environment:**
 - OS: [e.g. Ubuntu]
 - JDK Version: 1.8.0_312
 - Kryo Version: 5.2.0
 - fastutil Version: 8.5.6

**Comment by theigl** [comment]
@catap: Kryo has buit-in support for most JDK data structures, but needs help (i.e. a custom serializer) when serializing complex third-party data structures.

Please take a look at https://github.com/magro/kryo-serializers/issues/76. The linked serializer might help, or you can always fall back to plain Java serialization.

**Comment by catap** [comment]
@theigl or use `FieldSerializer` which works very well :)

**Comment by theigl** [comment]
@catap: I would suggest you do some performance tests. If fastutil has optimized custom serialization logic it might be faster and/or smaller than `FieldSerializer`. But good to know that this works for you!
