### ISSUE TITLE
PriorityQueueSerializer fails to load empty empty queue 

### ISSUE THREAD

**Issue by holgerbrandl** [EsotericSoftware/kryo#865]
**Describe the bug**
Consider the following example:
```
PriorityQueue<String> foo  = new PriorityQueue<>();

Kryo kryo = KryoKoinKt.buildKryoKoin();

File saveFile = new File("dat.bin");
Output o = new Output(new FileOutputStream(saveFile));
kryo.writeObject(o, foo);
o.close();

Input i = new Input(new FileInputStream(saveFile));

PriorityQueue<String> restored = kryo.readObject(i, PriorityQueue.class);

System.out.println(restored);
```

Expected: it should read the empty queue.

Observed:
```
Exception in thread "main" java.lang.IllegalArgumentException
	at java.base/java.util.PriorityQueue.<init>(PriorityQueue.java:171)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$PriorityQueueSerializer.createPriorityQueue(DefaultSerializers.java:746)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$PriorityQueueSerializer.create(DefaultSerializers.java:738)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$PriorityQueueSerializer.create(DefaultSerializers.java:732)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:216)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:44)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:774)
	at KryoPrioMap.main(KryoPrioMap.java:25)
```

**Environment:**
 - OS: Windows
 - JDK Version: 11
 - Kryo Version: 5.2

**Comment by theigl** [comment]
Good catch. I think we need to use a minimum capacity of 1.

**Comment by theigl** [comment]
Fixed. Please test against the lastest snapshot.

**Comment by holgerbrandl** [comment]
Works for me. Thanks for the quick update.
