### ISSUE TITLE
After upgrade java 11 to 11.0.6 (and upper), RMI connection failed. 

### ISSUE THREAD

**Issue by tigeleo** [EsotericSoftware/kryo#880]
I get error:
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

I all version from 1.8 until 11.0.5 working fine.

**Comment by theigl** [comment]
@tigeleo: What does that have to do with Kryo? If Kryo is involved somehow, please post the full stacktrace.

**Comment by tigeleo** [comment]
Hi. No , not use Kryo. 
But I think that found something, Failed not simple RMI, but lucene RMI .
And it is cause that fail this one. 
But still not understood why Lucene cannot to work. 

2022-02-01 15:41:19,545 ERROR [t-Thread-49] [c-Searcher] - failed to update schema: false,slicestrue 
java.rmi.RemoteException: Method is not Remote: interface org.apache.lucene.search.Searchable::public abstract int org.apache.lucene.search.Searchable.maxDoc() throws java.io.IOException
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:214)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
	at com.sun.proxy.$Proxy125.maxDoc(Unknown Source)
	at org.apache.lucene.search.MultiSearcher.<init>(MultiSearcher.java:146)
	at org.apache.lucene.search.ParallelMultiSearcher.<init>(ParallelMultiSearcher.java:64)
	at org.apache.lucene.search.ParallelMultiSearcher.<init>(ParallelMultiSearcher.java:57)
	at com.exlibris.jaguar.search.lucene.impl.JaguarParallelMSearcher.<init>(JaguarParallelMSearcher.java:82)
	at com.exlibris.jaguar.mng.search.Searcher.reset(Searcher.java:471)
	at com.exlibris.jaguar.mng.search.Searcher.update(Searcher.java:356)
	at java.base/java.util.Observable.notifyObservers(Observable.java:173)
	at com.exlibris.jaguar.mng.manager.Manager.resetAll(Manager.java:44)
	at com.exlibris.jaguar.mng.agent.AgentMananger.deployAgentInner(AgentMananger.java:382)
	at com.exlibris.jaguar.mng.agent.AgentMananger.deployAgent(AgentMananger.java:362)
	at com.exlibris.jaguar.mng.agent.AgentMananger.registerAgent(AgentMananger.java:177)
	at com.exlibris.jaguar.mdb.AgentQueueMDB.registerAgent(AgentQueueMDB.java:66)
	at com.exlibris.jaguar.mdb.AgentQueueMDB.access$0(AgentQueueMDB.java:63)
	at com.exlibris.jaguar.mdb.AgentQueueMDB$RegisterThread.run(AgentQueueMDB.java:86)
2022-02-01 15:41:19,609 INFO  [t-Thread-49] [c-AgentQueueMDB] - Agent has successfully registered itself with the server, port 1097, host il-Davidbd-vm 

I was try to update Lucene version, but it not help. Still same problem... 
in 11.0.5 and lower - working
in 11.0.6 - and up not working. 

In debug I see that failed in constructor: 
org.apache.lucene.search.MultiSearcher

  /** Creates a searcher which searches <i>searchers</i>. */
  public MultiSearcher(Searchable... searchables) throws IOException {
    this.searchables = searchables;

    starts = new int[searchables.length + 1];	  // build starts array
    for (int i = 0; i < searchables.length; i++) {
      starts[i] = maxDoc;
      maxDoc += searchables[i].maxDoc();          // compute maxDocs
    }
    starts[searchables.length] = maxDoc;
  }
  
searchables[0] - have 
[0]	$Proxy123  (id=348)	
	h	RemoteObjectInvocationHandler  (id=391)	
		ref	UnicastRef2  (id=401)	
			ref	LiveRef  (id=408)	
				ch	TCPChannel  (id=412)	
				ep	TCPEndpoint  (id=415)	
				id	ObjID  (id=418)	
				isLocal	false	
That not contain the method...
