### ISSUE TITLE
Scala 3 lazy vals break FieldSerializer

### ISSUE THREAD

**Issue by nvollmar** [EsotericSoftware/kryo#882]
Scala 3 changed the implementation of lazy vals. Classes containing a lazy val end up with a field called `0bitmap$1`:

```
Compiled from "Test.scala"
public class Test implements scala.Product,java.io.Serializable {
  public static final long OFFSET$0;
  public long 0bitmap$1;
  private final byte a;
  ...
```

Trying to serialize an instance of such a class fails with

```
Cause: java.lang.ClassFormatError: Illegal field name "0bitmap$1" in class io/altoo/akka/serialization/kryo/TestFieldAccess
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at com.esotericsoftware.reflectasm.AccessClassLoader.defineClass(AccessClassLoader.java:78)
	at com.esotericsoftware.reflectasm.AccessClassLoader.defineAccessClass(AccessClassLoader.java:57)
	at com.esotericsoftware.reflectasm.FieldAccess.get(FieldAccess.java:173)
	at com.esotericsoftware.kryo.serializers.CachedFields.addField(CachedFields.java:147)
	at com.esotericsoftware.kryo.serializers.CachedFields.rebuild(CachedFields.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:82)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:68)
	at jdk.internal.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
```

**Comment by theigl** [comment]
@nvollmar: Could you try it against this branch: https://github.com/EsotericSoftware/kryo/tree/scala-lazy-val

With the added catch clause, `FieldSerializer` should fall back to standard reflection.

**Comment by nvollmar** [comment]
Quickly ran my test case against a build of that branch and I can confirm this fixes the issue 👍

**Comment by theigl** [comment]
Great! I'll apply this fix and will release a new Kryo version in the coming days.

Please report the issue to [@reflect](https://github.com/EsotericSoftware/reflectasm). It is unlikely that it will be fixed since the project is not actively maintained, but it makes sense to document it.
