### ISSUE TITLE
java.lang.IncompatibleClassChangeError exception

### ISSUE THREAD

**Issue by mrniko** [EsotericSoftware/kryo#898]
**Describe the bug**
I'm getting error below:

```java
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:107)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:434)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IncompatibleClassChangeError: org.redisson.executor.RedissonExecutorServiceTest and org.redisson.executor.RedissonExecutorServiceTest$TaskStaticCallableClass disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/java.lang.Class.getEnclosingClass(Class.java:1613)
	at com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy.newInstantiatorOf(DefaultInstantiatorStrategy.java:54)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1190)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1199)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:163)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:122)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:98)
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:312)
	at org.redisson.executor.TasksRunnerService.executeCallable(TasksRunnerService.java:211)
```

**To Reproduce**
Please note TaskStaticCallableClass is a part of RedissonExecutorServiceTest. The same test pass with MarshallingCodec.

```java
public class RedissonExecutorServiceTest extends BaseTest {

    public static class TaskStaticCallableClass implements Callable<String>, Serializable {

        @Override
        public String call() throws Exception {
            return "123";
        }
        
    }

    @Test
    public void testInnerClassCallable() throws InterruptedException, ExecutionException, IOException {
        String res = redisson.getExecutorService("test").submit(new TaskStaticCallableClass()).get();
        assertThat(res).isEqualTo("123");
    }

}
```

**Environment:**
Windows, JDK 11, Kryo 5.3.0, Redisson 3.17.1

**Comment by theigl** [comment]
@mrniko: Please provide a reproducer that only uses Kryo without any external dependencies.

**Comment by mrniko** [comment]
My test works if `com.esotericsoftware.kryo.util.Util#isAndroid = true`

The problem is in `com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy#newInstantiatorOf` for isAndroid = false it uses ReflectASM which shouldn't be used for static inner class.

**Comment by theigl** [comment]
Kryo uses static inner classes *extensively* for tests. This test passes without problems:

```java
class StaticInnerTest extends KryoTestCase {
	
	public static class TaskStaticCallableClass implements Callable<String>, Serializable {
		@Override
		public String call() throws Exception {
			return "123";
		}

		public boolean equals(Object obj) {
			return obj instanceof TaskStaticCallableClass;
		}
	}

	@Test
	void testCallable () {
		kryo.setRegistrationRequired(false);
		
		roundTrip(67, new TaskStaticCallableClass());
	}
}
```

Please take this test as a base and add config options from Redisson until you can reproduce this issue with a plain Kryo test.

**Comment by mrniko** [comment]
I'm unable to reproduce it with plane Kryo test too.

**Comment by theigl** [comment]
Closing this issue for now. Please re-open if you can reproduce it.

**Comment by mrniko** [comment]
`kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());` setting fixed the issue
