### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.List

### ISSUE THREAD

**Issue by veiframework** [EsotericSoftware/kryo#899]
**Describe the bug**
java base type serialization failed, such as java.util.List

**Environment:**
 - OS: windows 10
 - JDK Version: 1.8
 - Kryo Version: 4.0.2
 - Dubbo Version: 2.7.15

**stacktrace**
 `java.io.IOException: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.List
	at org.apache.dubbo.common.serialize.kryo.optimized.KryoObjectInput2.readObject(KryoObjectInput2.java:163)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:155)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:83)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by theigl** [comment]
@doge618: There is not enough information for me to diagnose this issue. If you want me to look into this, please try to break down the issue into the simplest, dependency-free test-case you can.

**Comment by theigl** [comment]
Closing this for now. If you can provide a simpler test-case, please re-open.
