### ISSUE TITLE
After KryoSerialisation read object (i.e Deserialised Object) results in a new Initialised Object instead of Original

### ISSUE THREAD

**Issue by akshay-hazari** [EsotericSoftware/kryo#902]
I have done Custom Kryo Serialization like this

SO link to this - https://stackoverflow.com/questions/72708652/after-kryoserialisation-read-object-i-e-deserialised-object-results-in-a-new-i

```
class NumericalRangeHistogramCalculator(
  var histogramSketch: UpdateDoublesSketch = DoublesSketch.builder().build(),
) : KryoSerializable {

  var sum: Double = 0.0

  operator fun plus(fieldValue: Any?) {
    if (fieldValue is Number) {
      histogramSketch.update(fieldValue.toDouble())
      this.sum += fieldValue.toDouble()
    }
  }

  override fun toString(): String {
    return histogramSketch.toString()
  }

  operator fun plus(other: NumericalRangeHistogramCalculator) = NumericalRangeHistogramCalculator(
    histogramSketch = run {
      val doublesUnion = DoublesUnion.builder().build()
      doublesUnion.update(histogramSketch)
      doublesUnion.update(other.histogramSketch)
      this.sum += other.sum
      doublesUnion.result
    },
  )

  fun getFrequencies(): List<NumericalRangeBinData>? {
    if (histogramSketch.isEmpty) {
      return null
    }
    return try {
      val separators = getSeparators()
      val histogram = histogramSketch.getPMF(separators)
      val scaledHistogram = histogram.map { it * histogramSketch.n }
      scaledHistogram.withIndex().map {
        val lower = if (it.index == 0) null else separators[it.index - 1]
        val upper = if (it.index == separators.size) null else separators[it.index]
        NumericalRangeBinData(lower, upper, it.value)
      }
    } catch (e: Exception) {
      log.error("Failed to generate frequencies for numerical data", e)
      null
    }
  }

  fun getDecimalDataDistribution(): DoubleDistributionForCollections? {
    return if (!histogramSketch.isEmpty) {
      DoubleDistributionForCollections(
        histogramSketch.minValue, histogramSketch.maxValue,
        this.sum / histogramSketch.n, getStdDev(),
        this.sum
      )
    } else {
      null
    }
  }

  private fun getStdDev(): Double {
    var sum = 0.0
    getFrequencies()?.map {
      val value = (it.upper_bound_exclusive?.let { it1 -> it.lower_bound_inclusive?.plus(it1) })?.div(2)
      if (value != null) (it.frequency * ((this.sum / histogramSketch.n) - value).pow(2))
    }?.forEach {
      if (isNumeric(it.toString()))
        sum += it.toString().toDouble()
    }
    return sqrt(sum / histogramSketch.n)
  }

  internal fun getSeparators(): DoubleArray {
    val (min, max) = histogramSketch.getQuantiles(MIN_MAX_VALUE)
    return if (min == max) {
      doubleArrayOf(min)
    } else {
      val increase = (max - min) / NUMBER_OF_BINS
      (0..NUMBER_OF_BINS - 2).map { min + (increase * (it + 1)) }.toDoubleArray()
    }
  }

  override fun write(kryo: Kryo, output: Output) {

//    val serializedSketchBytes = histogramSketch.compact().toByteArray()

    try {
      kryo.writeObject(output, this)
//      output.writeInt(serializedSketchBytes.size)
//      output.write(serializedSketchBytes)
    } catch (e: Exception) {
      log.error("Failed to serialise histogram sketch", e)
      throw e
    }
  }

  override fun read(kryo: Kryo, input: Input) {
//    val length = input.readInt()
//    if (length == 0) return
//    val serializedSketchBytes = ByteArray(length)
    try {
      val numericalRangeHistogramCalculator=
        kryo.readObject(input, NumericalRangeHistogramCalculator::class.java)
//      input.read(serializedSketchBytes)
      histogramSketch = numericalRangeHistogramCalculator.histogramSketch
      sum = numericalRangeHistogramCalculator.sum
    } catch (e: Exception) {
      log.error("Failed to deserialise histogram sketch", e)
      throw e
    }
  }

  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (other?.javaClass != javaClass) return false
    other as NumericalRangeHistogramCalculator
    return histogramSketch.toByteArray().contentEquals(other.histogramSketch.toByteArray())
  }

  override fun hashCode(): Int {
    return histogramSketch.hashCode()
  }

  companion object {
    const val NUMBER_OF_BINS = 20
    const val MIN_MAX_VALUE = 2

    private val log = LoggerFactory.getLogger(NumericalRangeHistogramCalculator::class.java)
  }
}
```

Have this unit test for above class gives me a completely new NumericalRangeHistogramCalculator object with no values after KryoRead. 

```
  @Test
  fun test_numerical_calculator_kryo_serialisation() {
    val kryo = Kryo()
    val output = Output(FileOutputStream("src/test/resources/file.dat"))
    val input = Input(FileInputStream("src/test/resources/file.dat"))

    val calculator = NumericalRangeHistogramCalculator()
    val data = listOf(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)
    data.forEach { calculator.plus(it) }
    val distribution = calculator.getDecimalDataDistribution()!!
    val min = 1.0
    val max = 6.0
    val (actualMin, actualMax) = calculator.histogramSketch.getQuantiles(MIN_MAX_VALUE)
    assertEquals(min, actualMin)
    assertEquals(max, actualMax)
    assertEquals(distribution.sum, data.sum())
    assertEquals(distribution.mean, data.sum() / data.size)
    val frequencies = calculator.getFrequencies()
    println(calculator.histogramSketch)
    kryo.writeObject(output, calculator)
    output.close()

    val deserialisedCalculator = kryo.readObject(input, NumericalRangeHistogramCalculator::class.java)
    input.close()
    println("deserialisedCalculator $deserialisedCalculator")
    println("MIN_MAX_VALUE " + MIN_MAX_VALUE)
    val (desMin, desMax) = deserialisedCalculator.histogramSketch.getQuantiles(MIN_MAX_VALUE)
    assertEquals(min, desMin)
    assertEquals(max, desMax)

    val desFrequencies = deserialisedCalculator.getFrequencies()
    assertEquals(frequencies, desFrequencies)
  }
```

Here it gives me the output for above code and error at line `val (desMin, desMax) = deserialisedCalculator.histogramSketch.getQuantiles(MIN_MAX_VALUE)` where histogramSketch is Null while it should be the same as the written object in kryoWrite

```
### Quantiles HeapUpdateDoublesSketch SUMMARY: 
   Empty                        : false
   Direct, Capacity bytes       : false, 
   Estimation Mode              : false
   K                            : 128
   N                            : 6
   Levels (Needed, Total, Valid): 0, 0, 0
   Level Bit Pattern            : 0
   BaseBufferCount              : 6
   Combined Buffer Capacity     : 8
   Retained Items               : 6
   Compact Storage Bytes        : 80
   Updatable Storage Bytes      : 96
   Normalized Rank Error        : 1.406%
   Normalized Rank Error (PMF)  : 1.711%
   Min Value                    : 1.000000e+00
   Max Value                    : 6.000000e+00
### END SKETCH SUMMARY

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.reflectasm.AccessClassLoader (file:/Users/aashokhazari/.m2/repository/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.reflectasm.AccessClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
deserialisedCalculator 
### Quantiles HeapUpdateDoublesSketch SUMMARY: 
   Empty                        : true
   Direct, Capacity bytes       : false, 
   Estimation Mode              : false
   K                            : 128
   N                            : 0
   Levels (Needed, Total, Valid): 0, 0, 0
   Level Bit Pattern            : 0
   BaseBufferCount              : 0
   Combined Buffer Capacity     : 4
   Retained Items               : 0
   Compact Storage Bytes        : 8
   Updatable Storage Bytes      : 8
   Normalized Rank Error        : 1.406%
   Normalized Rank Error (PMF)  : 1.711%
   Min Value                    :          NaN
   Max Value                    :          NaN
### END SKETCH SUMMARY

MIN_MAX_VALUE 2


java.lang.NullPointerException
	at com.expediagroup.dataquality.profile.NumericalRangeHistogramCalculatorTest.test_numerical_calculator_kryo_serialisation(NumericalRangeHistogramCalculatorTest.kt:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code 255
```

**Comment by theigl** [comment]
@akshay-hazari: The code you provided is too complex for me to quickly see what's going on. If you want me to look into this, please break the issue down in the simplest, dependency-free test case you can create.

**Comment by theigl** [comment]
Closing this for now. If you can provide a simpler test-case, please re-open.
