### ISSUE TITLE
frequent instantiation cause out of mermory error

### ISSUE THREAD

**Issue by coder4lin** [EsotericSoftware/kryo#916]
**Describe the bug**
In my application use threadlocal storage new kryo and create a lot of kryo object. It will use Class.forName search higher jdk version provide new classes like “java.util.ImmutableCollections” eg. in every instantiation time.
Now i am using kryo pool try to fix this problem and suggest check jdk version before looking for those new classes provided by higher jdk version 

**Environment:**
 - OS: centos
 - JDK Version: openjdk 8
 - Kryo Version: 5.3.0

** full stack trace **
java.lang.OutOfMemoryError: null
　　at java.util.zip.ZipFile.open(ZipFile.java:-2) ~[?:1.8.0_332]
　　at java.util.zip.ZipFile.(ZipFile.java:228) ~[?:1.8.0_332]
　　at java.util.zip.ZipFile.(ZipFile.java:157) ~[?:1.8.0_332]
　　at java.util.jar.JarFile.(JarFile.java:171) ~[?:1.8.0_332]
　　at java.util.jar.JarFile.(JarFile.java:135) ~[?:1.8.0_332]
　　at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:209) ~[tomcat-util.jar:8.5.79]
　　at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:194) ~[tomcat-util.jar:8.5.79]
　　at org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:96) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:257) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.webresources.Cache.getResource(Cache.java:62) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2376) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:881) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1384) ~[catalina.jar:8.5.79]
　　at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1228) ~[catalina.jar:8.5.79]
　　at java.lang.Class.forNameImpl(Class.java:-2) ~[?:1.8.0_332]
　　at java.lang.Class.forName(Class.java:339) ~[?:1.8.0_332]
　　at com.esotericsoftware.kryo.util.Util.isClassAvailable(Util.java:73) ~[kryo-5.3.0.jar:?]
　　at com.esotericsoftware.kryo.serializers.ImmutableCollectionsSerializers.addDefaultSerializers(ImmutableCollectionsSerializers.java:37) ~[kryo-5.3.0.jar:?]
　　at com.esotericsoftware.kryo.Kryo.(Kryo.java:232) ~[kryo-5.3.0.jar:?]
　　at com.esotericsoftware.kryo.Kryo.(Kryo.java:168) ~[kryo-5.3.0.jar:?]

**Comment by theigl** [comment]
@coder4lin: You would have to instantiate Kryo many thousands of times for this to be a problem. Your memory leak most likely comes from somewhere else and Kryo just triggered the final allocation that exhausted your memory.

Can you share your code for how you re-use Kryo with ThreadLocals or pooling?

**Comment by coder4lin** [comment]
Thank you for answer ,It seems  can not be re-use when use ThreadLocals and you are right kryo not all but may be one of the main reasons.

This is my code:

private static final Pool<Kryo> kryoPool = new Pool<Kryo>(true, false, 30) {
        protected Kryo create() {
            Kryo kryo = new Kryo();
            kryo.setReferences(true);
            kryo.setRegistrationRequired(false);
            return kryo;
        }
    };
    
    public static Kryo getInstance() {
        return kryoPool.obtain();
    }

    public static void free(Kryo kryo) {
        kryoPool.free(kryo);
    }

    
    private static final ThreadLocal<Kryo> kryoLocal = new ThreadLocal<Kryo>() {
        @Override
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            kryo.setReferences(true);
            kryo.setRegistrationRequired(false);
            return kryo;
        }
    };
    public static Kryo getThreadLocalInstance() {
        return kryoLocal.get();
    }

**Comment by coder4lin** [comment]
> @coder4lin: You would have to instantiate Kryo many thousands of times for this to be a problem. Your memory leak most likely comes from somewhere else and Kryo just triggered the final allocation that exhausted your memory.
> 
> Can you share your code for how you re-use Kryo with ThreadLocals or pooling?

Thank you for answer ,It seems can not be re-use when use ThreadLocals and you are right kryo not all but may be one of the main reasons.

This is my code:
```
private static final Pool<Kryo> kryoPool = new Pool<Kryo>(true, false, 30) {
        protected Kryo create() {
            Kryo kryo = new Kryo();
            kryo.setReferences(true);
            kryo.setRegistrationRequired(false);
            return kryo;
        }
    };
    
    public static Kryo getInstance() {
        return kryoPool.obtain();
    }

    public static void free(Kryo kryo) {
        kryoPool.free(kryo);
    }

    
    private static final ThreadLocal<Kryo> kryoLocal = new ThreadLocal<Kryo>() {
        @Override
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            kryo.setReferences(true);
            kryo.setRegistrationRequired(false);
            return kryo;
        }
    };
    public static Kryo getThreadLocalInstance() {
        return kryoLocal.get();
    }
```

**Comment by simonzhong1985** [comment]
@theigl one more qeustion, Why didn't Kryo consider calling the `remove` method for the ThreadLocal scheme? Wouldn't this prevent memory leaks? thanks

**Comment by simonzhong1985** [comment]
@theigl here is understanding. if there is something wrong, please correct me.
For using ThreadLocal with Kryo without calling `remove`, the reasons are as follows:
1. we use ThreadLocal to create a Kryo object for each thread because Kryo is not thread-safe.
2. Even without calling `remove`, when threads are reused, we do not expect to create a new Kryo object, so there is no issue of data pollution as we typically encounter.
3. In general, we need to call `remove` to ensure that the value object (Kryo object) is not held indefinitely in the thread's ThreadLocalMap, which would prevent the Kryo object from being garbage collected. However, in our scenario, we do not expect the Kryo object to be garbage collected during the thread's lifetime.

**Comment by theigl** [comment]
That is correct.

**Comment by simonzhong1985** [comment]
@theigl  thanks a lot for your quick reply.
