### ISSUE TITLE
Serialization of objects from "java.lang.reflect" package

### ISSUE THREAD

**Issue by mrniko** [EsotericSoftware/kryo#934]
**Describe the bug**
Kryo5 is unable to serialize `java.lang.reflect.Field`, `java.lang.reflect.Member` and `java.lang.reflect.Method` objects. `Method` object extends `java.lang.reflect.Executable`

```
javax.persistence.PersistenceException: org.hibernate.cache.CacheException: com.esotericsoftware.kryo.KryoException: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient volatile boolean java.lang.reflect.Executable.hasRealParameterData accessible: module java.base does not "opens java.lang.reflect" to unnamed module @2c13da15
Serialization trace:
getterMethod (org.hibernate.property.access.spi.GetterFieldImpl)
getters (org.hibernate.tuple.component.PojoComponentTuplizer)
componentTuplizer (org.hibernate.type.EmbeddedComponentType)
type (org.hibernate.cache.internal.CacheKeyImplementation)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1394)
        at org.redisson.hibernate.CollectionTest.testQuery(CollectionTest.java:96)
        at org.hibernate.testing.junit4.ExtendedFrameworkMethod.invokeExplosively(ExtendedFrameworkMethod.java:45)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.cache.CacheException: com.esotericsoftware.kryo.KryoException: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient volatile boolean java.lang.reflect.Executable.hasRealParameterData accessible: module java.base does not "opens java.lang.reflect" to unnamed module @2c13da15
Serialization trace:
getterMethod (org.hibernate.property.access.spi.GetterFieldImpl)
getters (org.hibernate.tuple.component.PojoComponentTuplizer)
componentTuplizer (org.hibernate.type.EmbeddedComponentType)
type (org.hibernate.cache.internal.CacheKeyImplementation)
        at org.redisson.hibernate.RedissonStorage.evictData(RedissonStorage.java:183)
        at org.hibernate.cache.spi.support.StorageAccess.removeFromCache(StorageAccess.java:35)
        at org.hibernate.cache.spi.support.AbstractCachedDomainDataAccess.remove(AbstractCachedDomainDataAccess.java:91)        at org.hibernate.action.internal.CollectionAction.evict(CollectionAction.java:140)
        at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:52)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
        ... 4 more
```

**To Reproduce**
Try to run Redisson hibernate tests for redisson-hibernate-53 module

**Environment:**
 - OS: Windows
 - JDK Version: 11]
 - Kryo Version: 5.4.0

**Comment by theigl** [comment]
@mrniko: This could only be fixed if Kryo provided serializers for classes in `java.lang.reflect`. That's not a use-case that many people have.

I think it makes more sense to report this to Hibernate. Why would a cache key need to have a reference to a `Field`? In [Hibernate 6](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/cache/internal/CacheKeyImplementation.java), they seem to have fixed it already.

If you really think this is a legitimate use-case, you can register `JavaSerializer` for `Field`, `Member`,  `Method` etc.

**Comment by mrniko** [comment]
Field, Member and Method aren't implement Serializable interface and can't be serialized with JavaSerializer

**Comment by theigl** [comment]
Then you should definitely report this to Hibernate. `CacheKeyImplementation` implements `Serializable` so referencing objects that are not serializable is clearly a bug.

Even if Kryo was able to serialize these types, the resulting binary representation of the key would likely be very large. This is something that has to be fixed on Hibernate's side.

If you need a solution now, you could probably replace the default `CacheKeyImplementation` with the implementation from Hibernate 6.

**Comment by theigl** [comment]
I reported this to Hibernate as [HHH-16001](https://hibernate.atlassian.net/browse/HHH-16001)
