### ISSUE TITLE
kryo.copy not support java.util.Collections$SingletonList

### ISSUE THREAD

**Issue by wellhowtosay** [EsotericSoftware/kryo#939]
**Describe the bug**
fail to copy java.util.Collections$SingletonList object

> Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Class is not registered: java.util.Collections$SingletonList
Note: To register this class use: kryo.register(java.util.Collections.SingletonList.class);
	at com.nextev.ais.niolu.engine.cn.impl.model.MultiTaskLocalModelHandler.handle(MultiTaskLocalModelHandler.java:186)
	at com.nextev.ais.niolu.engine.cn.impl.model.MultiTaskLocalModelHandler.handle(MultiTaskLocalModelHandler.java:36)
	... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class is not registered: java.util.Collections$SingletonList
Note: To register this class use: kryo.register(java.util.Collections.SingletonList.class);
	at com.esotericsoftware.kryo.kryo5.Kryo.getRegistration(Kryo.java:579)
	at com.esotericsoftware.kryo.kryo5.Kryo.getSerializer(Kryo.java:601)
	at com.esotericsoftware.kryo.kryo5.Kryo.copy(Kryo.java:983)
	at com.nextev.ais.niolu.engine.cn.impl.model.MultiTaskLocalModelHandler.handle(MultiTaskLocalModelHandler.java:176)
	... 6 common frames omitted

**To Reproduce**
`List<NluInfo> modelNluInfos =Collections.singletonList(result);`
`kryo.copy(modelNluInfos);`
**Environment:**
 - OS: macOs
 - JDK Version: 1.8
 - Kryo Version: 5.4.0

**Comment by theigl** [comment]
The error message says it quite clearly:

    Note: To register this class use: kryo.register(java.util.Collections.SingletonList.class);

You have to either `kryo.setRegistrationRequired(false)` or register the classes you want to copy.

**Comment by wellhowtosay** [comment]
> Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Class is not registered: java.util.Collections$SingletonList
I add following code
kryo.register(Collections.singletonList("").getClass());
and it finally works
BTW, why not support Collections.singletonList and many other Array Class  by default

**Comment by theigl** [comment]
It is supported by default if you `setRegistrationRequired(false)`. If manual registration is required, only primitives and wrappers are registered by default. Everything else has to be manually registered by the user. The main reason is that serialization is fastest if only the minimum necessary number of types is registered.
