### ISSUE TITLE
Serialization of a generic array of enum

### ISSUE THREAD

**Issue by pierrecoquentin-datadome** [EsotericSoftware/kryo#940]
**Describe the bug**
Fails to serialize a generic array of enum values when it's defined as a parameterized field of a class.

**To Reproduce**

```java
package test.kryo;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.minlog.Log;

import java.io.ByteArrayOutputStream;

public class KryoTest {

    public static void main(String[] args) {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);

        Log.set(Log.LEVEL_TRACE);

        ArrayEnum<TestEnum> array = new ArrayEnum<>(new TestEnum[]{TestEnum.A});
        Container container = new Container(array);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        try (Output output = new Output(outputStream)) {
            kryo.writeClassAndObject(output, container);
        }
    }

    enum TestEnum {
        A, B, C;
    }

    public static class ArrayEnum<V extends Enum<V>> {

        private V[] values;

        public ArrayEnum(V[] array) {
            this.values = array;
        }
    }

    public static class Container {

        private ArrayEnum<TestEnum> field;

        public Container(ArrayEnum<TestEnum> array) {
            this.field = array;
        }
    }
}
```

When running this example, Kryo will throw an exception because it will directly try to use an `EnumSerializer` on the array instead of an `ObjectArraySerializer` before.

```
Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.lang.ClassCastException: [Ltest.kryo.KryoTest$TestEnum; cannot be cast to java.lang.Enum
Serialization trace:
values (test.kryo.KryoTest$ArrayEnum)
field (test.kryo.KryoTest$Container)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:101)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
	at test.kryo.KryoTest.main(KryoTest.java:21)
Caused by: java.lang.ClassCastException: [Ltest.kryo.KryoTest$TestEnum; cannot be cast to java.lang.Enum
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$EnumSerializer.write(DefaultSerializers.java:349)
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:692)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:79)
	... 6 more
```

**Environment:**
 - OS: Ubuntu
 - JDK Version: 8
 - Kryo Version: 5.2.0 and 5.4.0

**Comment by pierrecoquentin-datadome** [comment]
I've just noticed that it doesn't work for any generic array with a pre-defined serializer. It will produce the same error for `Number`.
```java
package test.kryo;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.minlog.Log;

import java.io.ByteArrayOutputStream;

public class KryoTest {

    public static void main(String[] args) {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);

        Log.set(Log.LEVEL_TRACE);

        ArrayNumber<Integer> array = new ArrayNumber<>(new Integer[]{1});
        Container container = new Container(array);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        try (Output output = new Output(outputStream)) {
            kryo.writeClassAndObject(output, container);
        }
    }

    public static class ArrayNumber<V extends Number> {

        private V[] values;

        public ArrayNumber(V[] array) {
            this.values = array;
        }
    }

    public static class Container {

        private ArrayNumber<Integer> field;

        public Container(ArrayNumber<Integer> array) {
            this.field = array;
        }
    }
}
```
When running, it will produce the same error:
```
Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.lang.ClassCastException: [Ljava.lang.Integer; cannot be cast to java.lang.Integer
Serialization trace:
values (test.kryo.KryoTest$ArrayNumber)
field (test.kryo.KryoTest$Container)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:101)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
	at test.kryo.KryoTest.main(KryoTest.java:21)
Caused by: java.lang.ClassCastException: [Ljava.lang.Integer; cannot be cast to java.lang.Integer
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$IntSerializer.write(DefaultSerializers.java:115)
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:692)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:79)
	... 6 more

**Comment by theigl** [comment]
@pierrecoquentin-datadome: Thanks a lot for the detailed bug report!

This seems to be caused by incorrect generics optimization. You can work around it for now by setting `kryo.setOptimizedGenerics(false);`.
