### ISSUE TITLE
High CPU Usage after switching to CompatibleFieldSerializer

### ISSUE THREAD

**Issue by ankit-harness** [EsotericSoftware/kryo#976]
**Describe the bug**

We recently switched to CompatibleFieldSerializer in our codebase. After that we have had few instances where a thread ends up consuming very high CPU in our service. We have to restart our service instance to fix that. Here's the stacktrace for the thread - 

```
main-app-pool-97571" #4516363 prio=5 os_prio=0 cpu=1058305.52ms elapsed=1212.28s tid=0x00007f6620d90400 nid=0x57dd8 runnable  [0x00007f6611c19000]
   java.lang.Thread.State: RUNNABLE
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:64)
at com.esotericsoftware.kryo.io.Output.flush(Output.java:186)
   Locked ownable synchronizers:
<0x000000043f002148> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

I think this issue is same as https://github.com/EsotericSoftware/kryo/issues/838. We wanted to try out the fix done for this issue. But, it's not available in 4.0.2 which is the version we are using. Upgrading to 5.x.x is going to be a huge effort as it has breaking changes.

Can we release 4.0.3 with this fix?

**Comment by ankit-harness** [comment]
Thanks a lot @theigl . I have created the PR - https://github.com/EsotericSoftware/kryo/pull/978

**Comment by theigl** [comment]
Thank you @ankit-harness! I will try to release a new Kryo 4 version next week. First I have to look through all improvements that were made to Kryo 5 that could potentially be backported.

 I have not done a release of 4.x since I took over as maintainer of this project. I hope the release process still works after 4 years ;)

**Comment by ankit-harness** [comment]
Eagerly waiting for the release with extra goodness. 😀

**Comment by ankit-harness** [comment]
Hi @theigl , any update on this?

**Comment by theigl** [comment]
Not yet. I need a couple of hours of spare time to get the 4.x branch into a releasable state again. I'll let you know when I cut the release.

**Comment by theigl** [comment]
@ankit-harness: I have just [released](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-4.0.3) 4.0.3.

I cherry picked and applied two additional fixes concerning `InputChunked` and `OutputChunked`.

Please verify that this release works for you.

**Comment by ankit-harness** [comment]
Thanks a lot @theigl . I will try it out. Is artifact uploaded to maven central repo too?

**Comment by theigl** [comment]
Yes. It should make it to central in the next hours.
