### ISSUE TITLE
NegativeArraySizeException when writing large files

### ISSUE THREAD

**Issue by asmirn1** [EsotericSoftware/kryo#996]
**Describe the bug**
When writing large files (2GB and more), I'm getting this error:
```shell
Caused by: java.lang.NegativeArraySizeException: -2147483645
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.resize(IdentityObjectIntMap.java:542) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putStash(IdentityObjectIntMap.java:306) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.push(IdentityObjectIntMap.java:300) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putResize(IdentityObjectIntMap.java:209) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.resize(IdentityObjectIntMap.java:551) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putStash(IdentityObjectIntMap.java:306) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.push(IdentityObjectIntMap.java:300) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.put(IdentityObjectIntMap.java:162) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.util.MapReferenceResolver.addWrittenObject(MapReferenceResolver.java:41) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeReferenceOrNull(Kryo.java:681) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:570) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.VersionFieldSerializer.write(VersionFieldSerializer.java:97) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:113) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:39) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.VersionFieldSerializer.write(VersionFieldSerializer.java:97) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:113) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:39) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.VersionFieldSerializer.write(VersionFieldSerializer.java:97) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.VersionFieldSerializer.write(VersionFieldSerializer.java:97) ~[kryo-4.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.3.jar:?]
	at org.dulab.adapbig.base.commons.WritableObject.toFile(WritableObject.java:118) ~[classes/:?]
	at org.dulab.adapbig.base.commons.WritableObject.toFile(WritableObject.java:87) ~[classes/:?]
	at org.dulab.adapbig.base.FeatureList.featureListToFile(FeatureList.java:180) ~[classes/:?]
	at org.dulab.adapbig.betweenbatchjoinaligner.BetweenBatchJoinAlignerModule.run(BetweenBatchJoinAlignerModule.java:83) ~[classes/:?]
	at org.dulab.adapbig.base.commons.Module.safeRun(Module.java:102) ~[classes/:?]
	... 6 more
```

I saw some solutions like calling `kryo.setReferences(false)` in #497 , but it seems to break compatibility with previously saved Kryo files. Is there a way to resolve this issue without breaking backward compatibility?

**To Reproduce**
My code for saving files:
```java
Kryo kryo = new Kryo();
kryo.setDefaultSerializer(VersionFieldSerializer.class);
kryo.register(this.getClass());
try (Output output = new Output(new DeflaterOutputStream(new FileOutputStream(filePath)))) {
    kryo.writeClassAndObject(output, this);
}
```

**Environment:**
 - OS: Windows 10
 - JDK Version: 19.0.1
 - Kryo Version: 4.0.3

**Comment by theigl** [comment]
`IdentityObjectIntMap` uses arrays to track references. Arrays cannot be larger than ~ Integer.MAX_VALUE. If your object graph is larger than that, then there is currently no way to get references to work. You can either turn off references completely, or disable them selectively by overriding `ReferenceResolver.useReferences`.

It's hard to give advice without knowing your dataset. E.g. if most of your data is `String`, then you can simply disable references for `String`.

Disabling references will break backwards-compatibility. The only solution is to use 2 Kryo instances and use the instance with references for older data, and the instance without references for newer data.

**Comment by NathanSweet** [comment]
You could implement your own ReferenceResolver that can handle > Integer.MAX_VALUE references by using your own special data structures that can support that.

**Comment by asmirn1** [comment]
@theigl @NathanSweet Thank you for your answers. Are references enabled by default? Will `kryo.setReferences(false)` disable references completely? I'll try it.

**Comment by theigl** [comment]
In Kryo 4, references are enabled by default. `kryo.setReferences(false)` will disable references completely.
